import {escape as e,choice,pill} from '../design-system/controls.mjs';
import {analyzeProject} from '../../smart-analysis.mjs';
import {icon} from '../design-system/icons.mjs';
import {gridPresentation,moveColumn,originalCell,fieldContext,rowContext} from '../../workspace-core.mjs';
export function mountGrid(host,project,{inspect,edit,tableId=null,onTableChange=()=>{}}){
 let table=project.tables.find(t=>t.id===tableId)||project.tables[0],q='',offset=0,sort=-1,ascending=true,layer='working',filters={},view={};
 let stored={};try{stored=JSON.parse(localStorage.getItem('biorescue-grid-views')||'{}')||{};}catch{}
 const findings=analyzeProject(project).items;
 if(!table){host.innerHTML='<p>No extracted tables. Add a tabular source to begin.</p>';return;}
 const key=()=>project.id+':'+table.id;
 const load=()=>{const state=stored[key()]||{};view=gridPresentation(state,table.headers.length);q=typeof state.query==='string'?state.query:'';filters=Object.fromEntries(Object.entries(state.filters||{}).filter(([c,v])=>Number.isInteger(+c)&&+c>=0&&+c<table.headers.length&&typeof v==='string')); sort=Number.isInteger(state.sort)&&state.sort<table.headers.length?state.sort:-1;ascending=state.ascending!==false;layer=['source','working','reviewed'].includes(state.layer)?state.layer:'working';offset=Math.max(0,Number(state.offset)||0);};load();
 function save(){stored[key()]={...view,query:q,filters,sort,ascending,layer,offset};try{localStorage.setItem('biorescue-grid-views',JSON.stringify(stored));}catch{/* Presentation remains usable when local storage is unavailable. */}}
 function draw(){
  const visible=view.order.filter(c=>!view.hidden.includes(c)),cols=[...visible.filter(c=>view.pinned.includes(c)),...visible.filter(c=>!view.pinned.includes(c))],pinLeft=c=>50+cols.slice(0,cols.indexOf(c)).filter(x=>view.pinned.includes(x)).reduce((n,x)=>n+(view.widths[x]||160),0),pinStyle=c=>view.pinned.includes(c)?`left:${pinLeft(c)}px;`:'',rows=table.rows.map((r,i)=>({r,i})).filter(({r})=>(!q||r.some(v=>v.toLowerCase().includes(q.toLowerCase())))&&Object.entries(filters).every(([c,v])=>!v||r[c].toLowerCase().includes(v.toLowerCase())));
  if(sort>=0)rows.sort((a,b)=>(ascending?1:-1)*(a.r[sort].localeCompare(b.r[sort],undefined,{numeric:true})||a.i-b.i));
  offset=Math.min(offset,Math.max(0,rows.length-1));const slice=rows.slice(offset,offset+60);
  const fieldFindings=c=>findings.filter(f=>f.tableId===table.id&&f.field===table.headers[c]);
  const renderRows=(start)=>{const end=Math.min(rows.length,start+60),spacer=(count)=>count?`<tr class="virtual-spacer" aria-hidden="true"><td colspan="${cols.length+1}" data-spacer="${count*40}"></td></tr>`:'';return spacer(start)+rows.slice(start,end).map(({r,i},rowIndex)=>`<tr data-source-row="${i}" aria-rowindex="${start+rowIndex+3}"><th><button data-row="${i}" aria-label="Inspect row ${i+1}">${i+1}</button></th>${cols.map(c=>{const original=originalCell(table,i,c),value=layer==='source'?original:layer==='reviewed'&&table.columns[c].status!=='Confirmed'?null:r[c],items=fieldFindings(c);return `<td data-grid-column="${c}" class="${view.pinned.includes(c)?'pinned ':''}${original!==r[c]&&original!==null?'changed':''}"><button class="grid-cell" data-cell="${i}:${c}" aria-label="Row ${i+1}, ${e(table.headers[c])}: ${e(value===null?'Not asserted':value===''?'Empty literal':value)}${items.length?'; field has '+items.length+' review candidates':''}">${items.length?'<span class="grid-finding-dot" aria-hidden="true"></span>':''}${value===null?'<span class="not-asserted">Not asserted</span>':value===''?'<span class="blank-value">empty</span>':e(value)}</button></td>`;}).join('')}</tr>`).join('')+spacer(rows.length-end);};
  host.innerHTML=`<div class="grid-command"><div class="grid-table-choice">${e(table.name)} · ${table.rows.length.toLocaleString()} records <div>${project.tables.map(t=>`<button data-grid-table="${e(t.id)}" aria-pressed="${t===table}">${e(t.name)}</button>`).join('')}</div></div><div class="segmented" aria-label="Data layer">${['source','working','reviewed'].map(x=>`<button data-layer="${x}" aria-pressed="${x===layer}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div></div><div class="grid-toolbar"><label class="search-field">${icon('search')}<input id="grid-search" placeholder="Search literal values" value="${e(q)}" aria-label="Search literal values"></label><button class="button compact" data-grid-columns>Columns</button><span>${rows.length.toLocaleString()} matched · ${offset+1}–${Math.min(offset+60,rows.length)}</span></div><div class="grid-scroll" tabindex="0" aria-label="Scientific data grid"><table class="data-grid" aria-rowcount="${rows.length+2}"><thead><tr><th class="row-number">ROW</th>${cols.map(c=>`<th data-grid-column="${c}" class="${view.pinned.includes(c)?'pinned':''}"><button data-field="${c}">${e(table.headers[c])}${pill(table.columns[c].status)}</button><button class="sort-field" aria-label="Sort ${e(table.headers[c])}" data-sort="${c}">↕</button><span class="resize-handle" data-resize="${c}" role="separator" tabindex="0" aria-label="Resize ${e(table.headers[c])}"></span></th>`).join('')}</tr><tr class="grid-filters"><th></th>${cols.map(c=>`<th class="${view.pinned.includes(c)?'pinned':''}" data-grid-column="${c}"><input data-filter="${c}" aria-label="Filter ${e(table.headers[c])}" placeholder="Filter…" value="${e(filters[c]||'')}"></th>`).join('')}</tr></thead><tbody>${renderRows(offset)}</tbody></table></div><div class="grid-pagination"><button data-grid-prev ${offset===0?'disabled':''}>Previous 60</button><span>Scroll through ${rows.length.toLocaleString()} matched rows; up to 60 rows render at once. Source indexes are retained.</span><button data-grid-next ${offset+60>=rows.length?'disabled':''}>Next 60</button></div><p class="safety-note">Reviewed view shows only explicitly Confirmed field values. It is not a scientific certification. Double-click a working value to preview an audited edit.</p>`;
  // CSSOM styling obeys the existing strict CSP; parsed HTML style attributes do not.
  const dataTable=host.querySelector('.data-grid');dataTable.style.tableLayout='fixed';dataTable.style.minWidth='0';dataTable.style.width=(50+cols.reduce((n,c)=>n+(view.widths[c]||160),0))+'px';
  const styleCells=()=>{host.querySelectorAll('[data-spacer]').forEach(cell=>cell.style.height=cell.dataset.spacer+'px');host.querySelectorAll('[data-grid-column]').forEach(cell=>{const c=+cell.dataset.gridColumn,width=(view.widths[c]||160)+'px';cell.style.width=width;cell.style.minWidth=width;cell.style.maxWidth=width;if(view.pinned.includes(c))cell.style.left=pinLeft(c)+'px';});};styleCells();
  host.querySelectorAll('[data-grid-table]').forEach(b=>b.onclick=()=>{table=project.tables.find(t=>t.id===b.dataset.gridTable);onTableChange(table.id);offset=0;sort=-1;filters={};load();draw();});
  host.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;save();draw();});
  const preserveInput=(id,run)=>{run();const input=host.querySelector(id);input?.focus();input?.setSelectionRange(input.value.length,input.value.length);};
  host.querySelector('#grid-search').oninput=event=>{q=event.target.value;offset=0;save();preserveInput('#grid-search',draw);};
  host.querySelectorAll('[data-filter]').forEach(input=>input.oninput=()=>{filters[input.dataset.filter]=input.value;offset=0;save();preserveInput(`[data-filter="${input.dataset.filter}"]`,draw);});
  host.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{if(sort===+b.dataset.sort)ascending=!ascending;else{sort=+b.dataset.sort;ascending=true;}save();draw();});
  host.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>inspect(fieldContext(project,table,+b.dataset.field)));
  const bindRows=()=>{
  host.querySelectorAll('[data-row]').forEach(b=>b.onclick=()=>inspect(rowContext(project,table,+b.dataset.row)));
  host.querySelectorAll('[data-cell]').forEach(b=>{let clickTimer;b.onclick=()=>{clearTimeout(clickTimer);clickTimer=setTimeout(()=>{const [r,c]=b.dataset.cell.split(':').map(Number);inspect({...fieldContext(project,table,c),row:r,source:originalCell(table,r,c),working:table.rows[r][c]});},240);};b.ondblclick=()=>{clearTimeout(clickTimer);if(layer==='working'){const [r,c]=b.dataset.cell.split(':').map(Number);edit(table,r,c);}};b.onkeydown=event=>{const [sourceRow,column]=b.dataset.cell.split(':').map(Number),position=rows.findIndex(row=>row.i===sourceRow),index=position*cols.length+cols.indexOf(column),delta=({ArrowRight:1,ArrowLeft:-1,ArrowDown:cols.length,ArrowUp:-cols.length})[event.key];if(delta!==undefined){event.preventDefault();const target=Math.max(0,Math.min(rows.length*cols.length-1,index+delta)),row=Math.floor(target/cols.length),field=cols[target%cols.length],selector=`[data-cell="${rows[row].i}:${field}"]`;if(row<offset||row>=offset+60){offset=Math.max(0,row-5);save();draw();}host.querySelector(selector)?.focus();}};});
  };bindRows();
  const scroller=host.querySelector('.grid-scroll');scroller.style.height='570px';scroller.scrollTop=offset*40;let scheduled=false;scroller.onscroll=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;if(!scroller.isConnected)return;const start=Math.min(Math.max(0,rows.length-1),Math.max(0,Math.floor(scroller.scrollTop/40)-5));if(start===offset)return;const focused=document.activeElement?.dataset.cell;offset=start;host.querySelector('tbody').innerHTML=renderRows(offset);styleCells();bindRows();if(focused){const cell=host.querySelector(`[data-cell="${focused}"]`);if(cell)cell.focus({preventScroll:true});else scroller.focus({preventScroll:true});}save();host.querySelector('.grid-toolbar>span').textContent=rows.length.toLocaleString()+' matched · '+(offset+1)+'–'+Math.min(offset+60,rows.length);host.querySelector('[data-grid-prev]').disabled=offset===0;host.querySelector('[data-grid-next]').disabled=offset+60>=rows.length;});};
  host.querySelector('[data-grid-prev]').onclick=()=>{offset=Math.max(0,offset-60);save();draw();};host.querySelector('[data-grid-next]').onclick=()=>{offset+=60;save();draw();};
  host.querySelector('[data-grid-columns]').onclick=()=>{inspect({kind:'columns',html:`<h2>Column presentation</h2><p>Reordering, pinning and hiding affect this view only.</p>${view.order.map(c=>`<div class="column-option"><strong>${e(table.headers[c])}</strong><button data-col-hide="${c}">${view.hidden.includes(c)?'Show':'Hide'}</button><button data-col-pin="${c}">${view.pinned.includes(c)?'Unpin':'Pin'}</button><button data-col-move="${c}:-1" aria-label="Move ${e(table.headers[c])} left">←</button><button data-col-move="${c}:1" aria-label="Move ${e(table.headers[c])} right">→</button></div>`).join('')}`});document.querySelectorAll('[data-col-hide]').forEach(b=>b.onclick=()=>{const c=+b.dataset.colHide;view.hidden=view.hidden.includes(c)?view.hidden.filter(x=>x!==c):[...view.hidden,c];view=gridPresentation(view,table.headers.length);save();draw();host.querySelector('[data-grid-columns]').click();});document.querySelectorAll('[data-col-pin]').forEach(b=>b.onclick=()=>{const c=+b.dataset.colPin;view.pinned=view.pinned.includes(c)?view.pinned.filter(x=>x!==c):[...view.pinned,c].slice(-3);save();draw();host.querySelector('[data-grid-columns]').click();});document.querySelectorAll('[data-col-move]').forEach(b=>b.onclick=()=>{const [c,d]=b.dataset.colMove.split(':').map(Number);view=moveColumn(view,c,d,table.headers.length);save();draw();host.querySelector('[data-grid-columns]').click();});};
  host.querySelectorAll('[data-resize]').forEach(handle=>{handle.onpointerdown=event=>{const column=+handle.dataset.resize,start=event.clientX,width=handle.parentElement.getBoundingClientRect().width;handle.setPointerCapture(event.pointerId);handle.onpointermove=e2=>{view.widths[column]=Math.max(90,Math.min(600,width+e2.clientX-start));handle.parentElement.style.minWidth=view.widths[column]+'px';};handle.onpointerup=()=>{handle.onpointermove=null;save();draw();};};handle.onkeydown=event=>{if(['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const c=+handle.dataset.resize;view.widths[c]=Math.max(90,Math.min(600,(view.widths[c]||160)+(event.key==='ArrowRight'?20:-20)));save();draw();host.querySelector(`[data-resize="${c}"]`).focus();}};});
 }draw();
}
