import {helpExperience} from './help-experience.mjs';
import {knowledge} from '../../knowledge.mjs';
import {tutorialLessons} from '../../tutorial-registry.mjs';
import {getGlossary} from '../../glossary.mjs';
import {escape as e,button as b,pill} from '../design-system/controls.mjs';
import {icon} from '../design-system/icons.mjs';
import {heading} from './screens.mjs';
const routeMap={'Project':'Overview','Inspect':'Understand','Metadata':'Advanced','Evidence':'Advanced','Relationships':'Advanced','Review queue':'Review','Translate & standardize':'Standardize','Standards Center':'Package','Export':'Package','Storage & Recovery':'Advanced','Snapshots':'Advanced','Large CSV':'Package','Help':'Help','Settings':'Settings','Sources':'Sources','Validate':'Validate','Repair':'Repair'};
const topic=(route,selector,title,text,extra={})=>({route,selector,title,text,...extra});
const operation={missingness:'missing',dates:'date',units:'unit',codebooks:'codes',coordinates:'coordinate-pair',taxonomy:'taxonomy',translation:'unit'};
const registry={
 'first-rescue':[topic('Overview','.journey-dashboard','Read the rescue context','Inspect evidence and the next candidate decision. Progress is not scientific certification.'),topic('Sources','[data-action=verify]','Verify retained originals','Verification checks actual source bytes, separately from field meaning.'),topic('Understand','.data-grid','Read source and working literals','Keep empty, zero and source-defined missing tokens distinct. Field candidate markers remain unconfirmed.',{grid:true}),topic('Review','.review-tools','Review organizational decisions','Queue annotations do not confirm meanings or change scientific values.'),topic('Package','[data-action=verify-package]','Verify an actual saved package','Select preservation or sharing deliberately. Verify the package you saved before relying on it.')],
 import:[topic('Sources','[data-action=import]','Inspect before preserving','Choose explicit encoding, delimiter and header conventions. The lesson never imports a file.'),topic('Sources','[data-action=verify]','Verify independently','A successful extraction does not establish scientific interpretation.')],
 understand:[topic('Understand','.grid-toolbar','Choose a view','Search and presentation settings leave scientific data unchanged.',{grid:true}),topic('Understand','.data-grid','Inspect exact literals','Arrow keys move across the virtual grid. Row numbers and field headers open provenance context.',{grid:true})],
 layers:[topic('Understand','.segmented','Separate data layers','Source is the retained origin for each working row; Working contains explicit edits; Reviewed displays only Confirmed field values. Download the original to inspect every source record.',{grid:true})],
 evidence:[topic('Advanced','.evidence-documents','Read retained evidence','Recovered previews may be incomplete. Inspect the original before citing it.',{tab:'Evidence'}),topic('Advanced','#evidence-form','Record an assertion with a locator','Competing assertions remain retained. A correction supersedes rather than erases.',{tab:'Evidence'})],
 uncertainty:[topic('Standardize','.mapping-row','Keep interpretation status explicit','Unknown, Inferred and Conflicting remain valid reviewed outcomes.'),topic('Review','.review-tools','Separate queue status from science','A completed queue decision can still retain Unknown meaning.')],
 relationships:[topic('Advanced','[data-action=relationship]','Review real record relationships','Use exact fields and evidence. Overlap and name similarity are candidate clues.'),topic('Advanced','[data-action=primary-key]','Inspect key identity','A composite key uses exact literal tuples. Uniqueness alone does not establish identity.',{tab:'Relationships'})],
 'safe-repair':[topic('Repair','[data-action=operation]','Choose an explicit working operation','Preview the actual affected cells. Original bytes remain retained.'),topic('Advanced','[data-action=snapshots]','Keep a recovery point','Compare local snapshots and prove a separate backup restore before important changes.')],
 validation:[topic('Validate','.validation-summary','Read structural findings','Blocking, review and advisory issues have separate effects. No quality badge replaces scientific judgment.')],
 standards:[topic('Package','[data-action=standards-capabilities]','Read support levels','Pinned local capabilities and partial-conformance limits stay explicit.'),topic('Package','[data-action=dwc-preparation]','Inspect prerequisites','Review-provider preparation does not establish ratified schema conformance.')],
 preservation:[topic('Package','[data-action=preflight]','Choose private preservation','Retain originals, working values, evidence, uncertainty and history.'),topic('Package','[data-action=verify-package]','Verify saved bytes','Integrity against a manifest is separate from authenticity and scientific correctness.')],
 sharing:[topic('Package','[data-action=public-package]','Inspect the actual sharing projection','Review coordinate suppression, free text and identifiers. Suppression does not guarantee anonymity.')],
 recovery:[topic('Advanced','[data-action=recover-forms]','Keep pending work separate','Resume drafts for review. Stale forms and retained window copies never apply automatically.'),topic('Advanced','[data-action=snapshots]','Restore a separate copy','Compare before restoring and retain current work.')],
 large:[topic('Package','[data-action=large-investigations]','Use bounded large-data workflows','CSV investigations use separate editing authority and revisions. Paired keys retain missing, unmatched and conflicting outcomes.')],
 privacy:[topic('Package','[data-action=public-package]','Review sharing risk','Precise locations, contacts, identifiers and free text may be private.'),topic('Help','#help-query','Find context before sending diagnostics','Support drafts stay local. Attach research material only after deliberate review.')],
 settings:[topic('Settings','.preferences-rail','Choose a category','Presentation preferences do not translate or confirm scientific data.'),topic('Settings','.theme-gallery','Inspect your environment','Palettes, materials and motion change immediately; system accessibility preferences remain respected.')]
};
export const v7Lessons=tutorialLessons.map(l=>({...l,steps:operation[l.id]?[topic('Standardize',`[data-action="operation:${operation[l.id]}"]`,'Prepare a reviewed representation',l.summary+' Source literals and unresolved outcomes remain retained.'),topic('Review','.review-tools','Investigate the candidate scope','Review evidence, uncertainty and task disposition separately. The walkthrough never applies a proposal.')]:registry[l.id]||[topic(routeMap[l.steps[0].route]||'Overview','#main','Inspect the supported workflow',l.summary)]}));
const progressKey='biorescue-product-tour-v7-lessons';
export function learningCenter(api){const {getProject,getFacts,navigate,prepareStop,safe,notice,download,practice}=api;let helpId='home',search='',filter='Recommended',lesson=null,index=0,coach=null,target=null,observer=null,epoch=0;
 const progress=()=>{try{return JSON.parse(localStorage.getItem(progressKey)||'{}')||{};}catch{return {};}};
 const scope=()=>getProject()?.id||'no-project';
 const state=id=>progress()[scope()+':'+id]||{index:0,done:[],skipped:[],complete:false};
 function store(id,value){const all=progress();all[scope()+':'+id]=value;localStorage.setItem(progressKey,JSON.stringify(all));}
 const recommendations=()=>{const ids=new Set(['first-rescue','understand','uncertainty']);for(const finding of getFacts()?.pending||[])ids.add(({date:'dates',unit:'units',missing:'missingness',codebook:'codebooks',coordinate:'coordinates',taxonomy:'taxonomy',relationship:'relationships',privacy:'privacy',conflict:'evidence'})[finding.kind]);return ids;};
 const guide=helpExperience({getProject,start,state,navigate,download,safe,notice,onSelect:id=>{const params=new URLSearchParams(location.hash.slice(1));params.set('view','Help');params.set('help',id);history.replaceState(null,'','#'+params);}});
 function help(host){guide.mount(host);}
 function center(host){const recommended=recommendations(),all=v7Lessons.filter(l=>filter==='Recommended'?recommended.has(l.id):filter==='Completed'?state(l.id).complete:filter==='Standards'?['standards','preservation','sharing'].includes(l.id):filter==='Advanced'?['relationships','large','recovery','privacy'].includes(l.id):filter==='Beginner'?['first-rescue','import','understand','layers','uncertainty'].includes(l.id):true);host.innerHTML=heading('LEARNING STUDIO','Learn by investigating.','Lessons observe controls. Scientific decisions, repairs and exports remain explicit actions.')+`<div class="learning-feature"><div><span class="eyebrow">BEGINNER / FICTIONAL PRACTICE</span><h2>Your first data rescue.</h2><p>Create a separate fictional project and follow the seven-stop introduction.</p>${b('Create practice & start tour','tour','primary','learning')}</div><div class="lesson-path"><span><b>01</b>Preserve</span><span><b>02</b>Investigate</span><span><b>03</b>Review</span><span><b>04</b>Leave with evidence</span></div></div><div class="lesson-filters">${['Recommended','Beginner','Workflow','Standards','Advanced','Completed'].map(label=>`<button data-lesson-filter="${label}" aria-pressed="${label===filter}">${label}</button>`).join('')}</div><div class="lesson-library">${all.map(l=>`<section>${icon('learning')}<h2>${e(l.title)}</h2><p>${e(l.summary)}</p><small>${l.steps.length} registered target stops · ${state(l.id).complete?'Completed':state(l.id).done.length?'In progress':'Ready to explore'}</small><button class="button" data-lesson="${e(l.id)}">${state(l.id).done.length&&!state(l.id).complete?'Resume':'Start lesson'}</button></section>`).join('')||'<p>No lessons in this scope yet.</p>'}</div>`;host.querySelectorAll('[data-lesson-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.lessonFilter;center(host);});}
 function clear(){epoch++;target?.classList.remove('lesson-target');observer?.disconnect();window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true);coach?.remove();coach=null;target=null;}
 function measure(){if(!target?.isConnected||!coach)return;const r=target.getBoundingClientRect();coach.style.setProperty('--target-top',r.top+'px');coach.style.setProperty('--target-left',r.left+'px');}
 async function show(){clear();const token=epoch,step=lesson.steps[index];await prepareStop(step);if(token!==epoch)return;for(let tries=0;tries<30;tries++){target=document.querySelector(step.selector);if(target&&target.getBoundingClientRect().width>0)break;await new Promise(r=>setTimeout(r,30));}const available=!!target&&target.getBoundingClientRect().width>0;coach=document.createElement('aside');coach.className='v7-lesson-coach';coach.setAttribute('aria-label','Guided lesson');coach.innerHTML=`<div class="eyebrow">${e(lesson.title)} · ${index+1}/${lesson.steps.length}</div><h2>${e(step.title)}</h2><p>${e(step.text)}</p>${available?'<p>Next records that you observed this control. It does not apply a scientific change.</p>':'<p class="privacy-callout">The registered target is unavailable. Add the prerequisite context or skip explicitly; this lesson cannot be marked complete with skipped targets.</p>'}<div class="heading-actions"><button class="button" id="lesson-pause">Pause</button>${index?'<button class="button" id="lesson-back">Back</button>':''}<button class="button" id="lesson-skip">Skip stop</button><button class="button primary" id="lesson-next" ${available?'':'disabled'}>${index===lesson.steps.length-1?'Finish lesson':'Next observed stop'}</button></div>`;document.body.append(coach);if(available){target.scrollIntoView({block:'center',behavior:'auto'});target.classList.add('lesson-target');observer=new ResizeObserver(measure);observer.observe(target);window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);measure();}coach.querySelector('#lesson-pause').onclick=()=>{store(lesson.id,{...state(lesson.id),index});clear();notice('Lesson paused. No scientific decisions were applied.');};coach.querySelector('#lesson-back')?.addEventListener('click',safe(async()=>{index--;await show();}));const advance=async skipped=>{const record=state(lesson.id),field=skipped?'skipped':'done';record[field]=[...new Set([...record[field],index])];if(!skipped)record.skipped=record.skipped.filter(n=>n!==index);record.index=Math.min(index+1,lesson.steps.length-1);const finished=index===lesson.steps.length-1;record.complete=finished&&record.skipped.length===0&&record.done.length===lesson.steps.length;record.updatedAt=new Date().toISOString();store(lesson.id,record);if(finished){clear();navigate('Learning');notice(record.complete?'Lesson completed; every registered target was observed. Scientific data were not changed.':'Lesson remains incomplete because one or more registered targets were skipped.');}else{index++;await show();}};coach.querySelector('#lesson-next').onclick=safe(()=>advance(false));coach.querySelector('#lesson-skip').onclick=safe(()=>advance(true));coach.querySelector('#lesson-next').focus({preventScroll:true});}
 async function start(id){const selected=v7Lessons.find(l=>l.id===id);if(!selected)return;if(!getProject())await practice();lesson=selected;index=state(id).complete?0:Math.min(state(id).index,lesson.steps.length-1);await show();}
 return {help,center,start,stop:clear,openHelp:id=>guide.open(id),currentHelp:guide.current};
}
