import {escape as e,choice,bindChoices,pill,button as b} from '../design-system/controls.mjs';
import {icon} from '../design-system/icons.mjs';
import {projectFacts,nextStep} from '../domain/journey.mjs';
const date=value=>value?e(new Date(value).toLocaleString()):'Not recorded';

export function projectLibrary(api){
 const {json,modal,safe,notice,manage}=api;let q='',scope='active',kind='all',selected=null,hub=null,previewToken=0;
 async function mount(host){host.innerHTML='<span class="eyebrow">LOCAL COLLECTION</span><h1>Projects</h1><p>Reading the saved project catalogue…</p>';hub=await json('/api/project-hub');if(!host.isConnected)return;draw(host);}
 function rows(){return hub.projects.filter(p=>(scope==='all'||p.state===scope)&&(kind==='all'||p.kind===kind)&&(!q||(p.title+' '+(p.description||'')+' '+(p.tags||[]).join(' ')).toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(b.updatedAt||'').localeCompare(a.updatedAt||''));}
 function draw(host){const list=rows();if(!list.some(p=>p.id===selected))selected=list[0]?.id||null;
  host.innerHTML=`<div class="workspace-heading"><div><span class="eyebrow">YOUR LOCAL COLLECTION</span><h1>Projects</h1><p>Inspect a rescue before continuing. Sources, unknowns and backup records stay explicit.</p></div><div class="heading-actions">${b('New rescue','import','primary','plus')}${b('Open backup','restore','secondary','backup')}${b('Open encrypted backup','encrypted-restore','secondary','privacy')}</div></div><div class="library-toolbar"><label class="search-field">${icon('search')}<input id="library-search" placeholder="Title, description or tag" value="${e(q)}" aria-label="Search project collection"></label>${choice('libraryScope','Collection',scope,[['active','Active'],['archived','Archived'],['trash','Trash'],['all','All']])}${choice('libraryKind','Project kind',kind,[['all','All kinds'],['research','Research'],['tutorial','Tutorial'],['example','Example']])}<span>${list.length} projects</span></div><div class="collection-workspace"><section class="collection-list">${list.map(p=>`<button class="collection-row ${p.id===selected?'selected':''}" data-library-select="${e(p.id)}"><span class="project-symbol">${icon(p.error?'recovery':'library')}</span><span><strong>${e(p.title||'Title unavailable')}</strong><small>${p.error?'Recovery required':`${p.resources??'Unknown'} sources · ${p.tables??'Unknown'} tables`} · ${e(p.kind||'research')}</small><small>${p.pinned?'Pinned · ':''}${date(p.updatedAt)}</small></span>${pill(p.state||'Unknown',p.error?'warning':'neutral')}${icon('arrow')}</button>`).join('')||'<p>No projects in this scope. Try another collection or search.</p>'}</section><aside id="collection-preview" class="collection-preview" aria-label="Selected project preview"><p>Select a saved rescue to inspect its current context.</p></aside></div>`;
  bindChoices(host);host.querySelector('#library-search').oninput=event=>{q=event.target.value;draw(host);const input=host.querySelector('#library-search');input.focus();input.setSelectionRange(q.length,q.length);};host.querySelectorAll('[name=libraryScope],[name=libraryKind]').forEach(input=>input.onchange=()=>{if(input.name==='libraryScope')scope=input.value;else kind=input.value;draw(host);});host.querySelectorAll('[data-library-select]').forEach(button=>button.onclick=()=>{selected=button.dataset.librarySelect;draw(host);});if(selected)showPreview(host,hub.projects.find(p=>p.id===selected)).catch(error=>notice(error.message,true));
 }
 async function showPreview(host,item){const token=++previewToken,node=host.querySelector('#collection-preview');node.innerHTML=`<span class="eyebrow">SELECTED RESCUE</span><h2>${e(item.title)}</h2><p>Reading its saved evidence and working annotations…</p>`;if(item.error){node.innerHTML=`<h2>${e(item.title)}</h2><p class="privacy-callout">${e(item.error)}</p><p>The source of the recovery error is retained. Open a verified backup or inspect previous revisions before changing this project.</p>${b('Open backup','restore','secondary','recovery')}`;return;}
  const [p,workspace]=await Promise.all([json('/api/project?id='+encodeURIComponent(item.id)),json('/api/workspace-state?id='+encodeURIComponent(item.id))]);if(token!==previewToken||!host.isConnected)return;const f=projectFacts(p,workspace),[route,title]=nextStep(f),state=item.state||'active';
  node.innerHTML=`<span class="eyebrow">SELECTED RESCUE</span><h2>${e(item.title)}</h2><p>${e(item.description||'Description not recorded.')}</p><div class="collection-facts"><div><strong>${f.sources}</strong><small>preserved sources</small></div><div><strong>${f.rows.toLocaleString()}</strong><small>working records</small></div><div><strong>${f.pending.length}</strong><small>queue decisions pending</small></div><div><strong>${f.unknown}</strong><small>unconfirmed definitions</small></div></div><div class="preview-next"><span class="eyebrow">CURRENT NEXT ACTION</span><strong>${e(title)}</strong><small>${e(route)} · bounded local analysis</small></div><dl><dt>Saved revision</dt><dd>${p.revision}</dd><dt>Original integrity</dt><dd>Verify inside Sources; not inferred from a save.</dd><dt>Last backup completion</dt><dd>${item.lastBackup?date(item.lastBackup):'Not recorded'}${!item.lastBackup&&item.lastBackupRequested?`<small>Requested ${date(item.lastBackupRequested)}; completion unknown.</small>`:''}</dd><dt>Last opened</dt><dd>${date(item.lastOpened)}</dd><dt>Location</dt><dd>Local workspace · ${e(item.state||'active')}</dd></dl><div class="preview-actions">${state==='active'?`<button class="button primary" data-project="${e(item.id)}">${icon('arrow')}Continue rescue</button>`:`<button class="button primary" data-library-action="restore">Restore to active collection</button>`}<button class="button" data-library-action="pin">${icon('library')}${item.pinned?'Unpin':'Pin'}</button><button class="button" data-library-action="duplicate">${icon('window')}Duplicate separately</button>${state==='active'?'<button class="button" data-library-action="rename">Rename</button><button class="button" data-library-action="archive">Archive</button><button class="button" data-library-action="trash">Move to Trash</button>':''}${state==='trash'?'<button class="button" data-library-action="delete">Review permanent deletion</button>':''}</div>`;
  node.querySelectorAll('[data-library-action]').forEach(button=>button.onclick=safe(async()=>{const action=button.dataset.libraryAction;if(action==='delete'){await deletion(item);return;}if(action==='rename'){modal('Rename this rescue',`<form id="library-rename" data-context="${e(item.id)}"><label>Project title<input name="name" maxlength="200" required value="${e(item.title)}"></label><button class="button primary">Save explicit title change</button></form>`);document.querySelector('#library-rename').onsubmit=safe(async ev=>{ev.preventDefault();await manage({id:item.id,action,managementRevision:hub.revision,projectRevision:p.revision,name:new FormData(ev.target).get('name')});notice('Project title changed with an audit record.');});return;}if(action==='restore'||action==='duplicate')scope='active';const result=await manage({id:item.id,action,managementRevision:hub.revision,projectRevision:p.revision});if(result.project)selected=result.project.id;notice(action==='duplicate'?'Separate duplicate created; source project retained.':'Collection updated.');}));
 }
 async function deletion(item){const inventory=await json('/api/delete-preview?id='+encodeURIComponent(item.id));modal('Review permanent deletion',`<p class="privacy-callout">This removes the project manifests, draft history, snapshots and working annotations listed below. Shared originals and external exported files are retained. Review a separate backup before proceeding.</p><h3>${e(inventory.title)}</h3><ul>${inventory.files.map(f=>`<li>${e(f)}</li>`).join('')}</ul><p>Backup request recorded: ${inventory.backupRecorded?'Yes — completion still requires your verification':'No'}</p><form id="permanent-delete"><label>Type the exact project ID to confirm<input name="confirm" required autocomplete="off" placeholder="${e(item.id)}"></label><button class="button">Permanently delete this project</button></form>`);document.querySelector('#permanent-delete').onsubmit=safe(async ev=>{ev.preventDefault();const confirm=new FormData(ev.target).get('confirm');if(confirm!==item.id)throw Error('The confirmation must match the exact project ID.');await manage({...inventory,action:'delete',confirm});notice('The explicitly confirmed Trash project was deleted. Shared originals were retained.');});}
 return {mount};
}
