import {applyRepair,transform,change,validation,recipe} from '../../project.mjs';
import {CONVERSION_UNITS,codebookSpec,evidenceGuard} from '../../translation-core.mjs';
import {taxonomyReference} from '../../taxonomy-review.mjs';
import {escape as e,choice,button as b,pill} from '../design-system/controls.mjs';
import {icon} from '../design-system/icons.mjs';

const operations=[['trim whitespace','Trim whitespace'],['rename column','Rename working field'],['replace value','Replace an exact literal'],['uppercase','Uppercase working literals'],['lowercase','Lowercase working literals'],['remove duplicate rows','Remove exact duplicate rows'],['derive field','Copy a derived field'],['split column','Derive a split component'],['merge columns','Derive joined fields'],['date','Reviewed date representation'],['unit','Reviewed unit conversion'],['missing','Reviewed missing tokens'],['codes','Reviewed codebook translation'],['coordinate','Reviewed angular coordinate'],['coordinate-pair','Reviewed projected coordinate pair'],['taxonomy','Reviewed local taxonomy reference']];
const reviewed=new Set(['date','unit','missing','codes','coordinate','coordinate-pair','taxonomy']);
const input=(name,label,value='',type='text')=>`<label>${e(label)}<input name="${name}" type="${type}" value="${e(value)}"></label>`;
const area=(name,label,value='',rows=3)=>`<label>${e(label)}<textarea name="${name}" rows="${rows}">${e(value)}</textarea></label>`;
const tableChoice=(p,name,value,label='Table')=>choice(name,label,value,p.tables.map(t=>[t.id,t.name]));
const columns=(table,name,value,label)=>choice(name,label,value,table.headers.map((h,i)=>[i,h]));
const citations=p=>`<fieldset><legend>Preserved evidence & exact locator</legend>${p.resources.map(r=>`<div class="citation-choice"><label class="checkbox-label"><input type="checkbox" name="evidence" value="${e(r.id)}">${e(r.name)}</label>${input('locator:'+r.id,'Page / row / section / line')}</div>`).join('')}</fieldset>`;
const summary=preview=>`<div class="operation-outcomes">${preview.counts?Object.entries(preview.counts).map(([name,count])=>`<span>${pill(name)}<strong>${count.toLocaleString()}</strong></span>`).join(''):`<p>${preview.affected.toLocaleString()} working changes in the full table.</p>`}</div><div class="repair-preview">${preview.examples.map(x=>`<div><span>Original row ${x.row??'definition'}</span><code>${e(typeof x.before==='object'?JSON.stringify(x.before):x.before)}</code>${icon('arrow')}<code>${e(typeof x.after==='object'?JSON.stringify(x.after):x.after)}</code>${x.state?pill(x.state,x.state==='unresolved'||x.state==='conflicting'?'warning':'neutral'):''}</div>`).join('')}</div>`;

export function operationDialogs(api){
 const {getProject,modal,save,safe,json,notice,download,openProject}=api;
 function operation(kind='trim whitespace',tableId=null){
  const p=getProject(),table=p.tables.find(t=>t.id===tableId)||p.tables[0];if(!table)throw Error('Import a table before reviewing a transformation.');
  const isReviewed=reviewed.has(kind),reference=p.tables.find(t=>t.id!==table.id)||table;
  let extra='';
  if(['rename column','replace value'].includes(kind))extra=input('value',kind==='rename column'?'New working field name':'Replacement literal')+(kind==='replace value'?input('match','Exact literal to replace'):'');
  if(['derive field','split column','merge columns'].includes(kind)||isReviewed)extra+=input('name','New derived field name',table.headers[0]+'_reviewed');
  if(kind==='split column')extra+=input('separator','Exact separator')+input('part','Component number (starting at 1)','1','number');
  if(kind==='merge columns')extra+=columns(table,'other',1,'Second source field')+input('separator','Separator',' ');
  if(kind==='remove duplicate rows')extra+=`<p class="privacy-callout">Identical rows may represent separate real observations. This operation keeps the first row only. Confirm the intended record identity and inspect the full preview.</p><fieldset><legend>Exact duplicate comparison fields</legend>${table.headers.map((h,c)=>`<label class="checkbox-label"><input type="checkbox" name="keys" value="${c}" checked>${e(h)}</label>`).join('')}</fieldset>`;
  if(kind==='date')extra+=choice('format','Explicit recorded date convention','ISO',['ISO','year','month','DMY','MDY','excel1900','excel1904','ISO-datetime'].map(x=>[x,x]))+input('dateCentury','Two-digit-year century (leave empty if unknown)','','number')+input('dateTimeColumn','Optional separate time field name')+input('dateUTCOffset','Explicit UTC offset (leave empty if unknown)');
  if(kind==='unit')extra+=choice('sourceUnit','Reviewed source unit','m',CONVERSION_UNITS.map(x=>[x,x]))+choice('targetUnit','Target unit','cm',CONVERSION_UNITS.map(x=>[x,x]))+input('unitColumn','Optional per-row unit field name');
  if(kind==='missing')extra+=area('missingTokens','Exact missing tokens, one per line')+`<p>Known zero and blank are separate states. Only the tokens you explicitly list are translated in the derived representation.</p>`;
  if(kind==='codes'||kind==='taxonomy')extra+=tableChoice(p,'referenceTable',reference.id,'Explicit local reference table')+input('referenceCode','Recorded-code field name',reference.headers[0])+input('referenceMeaning','Meaning / target-name field name',reference.headers[1]||'');
  if(kind==='taxonomy')extra+=input('referenceIdentifier','Optional identifier field name')+input('referenceRelease','Reference title / release / date')+`<p>No online or fuzzy taxon lookup. Unmatched or ambiguous names remain unresolved; original recorded names are retained.</p>`;
  if(kind==='coordinate')extra+=choice('axis','Explicit axis','latitude',[['latitude','Latitude'],['longitude','Longitude']])+input('datum','Reviewed datum / coordinate reference system');
  if(kind==='coordinate-pair')extra+=columns(table,'pairedColumn',1,'Northing field')+choice('sourceCrs','Reviewed source CRS','unknown',[['unknown','Unknown — retain unresolved'],['EPSG:3857','EPSG:3857']])+`<p>Target: EPSG:4326. EPSG:3857 requires cited evidence, a named reviewer and confirmed easting/northing metre axes. No CRS is inferred from numeric magnitude.</p><label class="checkbox-label"><input type="checkbox" name="axes">Evidence establishes easting / northing in metres</label>`;
  modal(isReviewed?'Review a derived representation':'Preview a working-data operation',`<p>Inspect the full-table preview before applying. Original bytes and source fields remain retained. Changes create an audited, reversible working revision.</p><form id="operation-form" data-context="${e(table.id)}:${e(kind)}"><div class="form-grid">${tableChoice(p,'table',table.id)}${choice('kind','Operation',kind,operations)}${columns(table,'column',0,'Recorded source field')}${extra}</div>${isReviewed?choice('basis','Review basis','evidence',[['evidence','Cited preserved evidence'],['human','Explicit human assertion']]):''}${input('reviewer','Reviewer')}${area('reason','Reason and scientific scope')}${citations(p)}<button class="button primary">${icon('search')}Review exact preview</button></form><div id="operation-preview"></div>`);
  const form=document.querySelector('#operation-form');let previewSpec=null,previewRevision=p.revision;
  form.addEventListener('change',event=>{previewSpec=null;document.querySelector('#operation-preview').innerHTML='';if(event.target.name==='kind')operation(event.target.value,table.id);else if(event.target.name==='table')operation(kind,event.target.value);});
  form.addEventListener('input',()=>{previewSpec=null;document.querySelector('#operation-preview').innerHTML='';});
  form.onsubmit=safe(async ev=>{
   ev.preventDefault();const values=new FormData(form),v=Object.fromEntries(values),current=getProject();if(current.id!==p.id||current.revision!==previewRevision)throw Error('The project changed. Reopen the operation and inspect a fresh preview.');
   if(!v.reason.trim())throw Error('Record a reason before previewing this operation.');
   const refs=values.getAll('evidence').map(id=>{const r=current.resources.find(r=>r.id===id);return {id,sha256:r.sha256,bytes:r.bytes,locator:v['locator:'+id]||''};});
   const review={basis:v.basis||'human',reason:v.reason,reviewer:v.reviewer,evidence:refs};
   let spec={op:isReviewed?'reviewed translation':kind,column:+v.column,reason:v.reason,review,name:v.name,value:v.value,match:v.match,separator:v.separator,part:+v.part,expectedInputName:table.headers[+v.column]};
   if(kind==='remove duplicate rows'){spec.keys=values.getAll('keys').map(c=>table.headers[+c]);if(!spec.keys.length)throw Error('Choose at least one comparison field.');}
   if(kind==='merge columns')spec.other=table.headers[+v.other];
   if(isReviewed){spec.action=kind;spec.upstreamOutcomePolicy='propagate';}
   if(kind==='date')Object.assign(spec,{format:v.format,datePolicy:'calendar-v2',dateCentury:v.dateCentury===''?null:+v.dateCentury,dateTimeColumn:v.dateTimeColumn,dateUTCOffset:v.dateUTCOffset,...(v.dateTimeColumn||v.format==='ISO-datetime'?{dateTimePolicy:'offset-v1'}:{})});
   if(kind==='unit')Object.assign(spec,{sourceUnit:v.sourceUnit,targetUnit:v.targetUnit,unitColumn:v.unitColumn});
   if(kind==='missing')spec.missingTokens=v.missingTokens.split(/\r?\n/).filter(x=>x!=='');
   if(kind==='coordinate')Object.assign(spec,{axis:v.axis,datum:v.datum});
   if(kind==='coordinate-pair')Object.assign(spec,{pairedColumn:+v.pairedColumn,expectedPairedName:table.headers[+v.pairedColumn],coordinatePolicy:'webmerc-inverse-v1',sourceCrs:v.sourceCrs,sourceAxes:v.axes?'easting-northing-metres':'unknown',targetCrs:'EPSG:4326'});
   if(kind==='codes'||kind==='taxonomy'){const reference=current.tables.find(t=>t.id===v.referenceTable),code=reference.headers.indexOf(v.referenceCode),meaning=reference.headers.indexOf(v.referenceMeaning);if(kind==='codes')spec.codebook=codebookSpec(current,reference.id,code,meaning);else spec.taxonomy=taxonomyReference(current,reference.id,code,meaning,v.referenceIdentifier?reference.headers.indexOf(v.referenceIdentifier):null,v.referenceRelease);}
   evidenceGuard(current,spec);const preview=transform(table,spec);previewSpec=structuredClone(spec);
   const host=document.querySelector('#operation-preview');host.innerHTML=`<h3>Full-table preview</h3>${summary(preview)}<p class="safety-note">Unresolved and conflicting translations retain the literal input. Review outcomes before interpreting derived values.</p><label class="checkbox-label"><input type="checkbox" id="operation-ack">I reviewed the preview and intend this working revision.</label><button class="button primary" id="apply-operation" disabled>Apply reviewed operation</button>`;
   document.querySelector('#operation-ack').onchange=ev=>document.querySelector('#apply-operation').disabled=!ev.target.checked;
   document.querySelector('#apply-operation').onclick=safe(async()=>{if(!previewSpec||getProject().revision!==previewRevision)throw Error('Preview is stale. Reopen and inspect the operation again.');const next=applyRepair(getProject(),table.id,previewSpec,v.reason);document.querySelector('#dialog').close();await save(next);});
  });
 }
 function relationship(){const p=getProject();if(p.tables.length<2)throw Error('Import two tables before defining a relationship.');const first=p.tables[0],second=p.tables[1];modal('Review a relationship',`<p>Name equality and overlapping values are candidate evidence only. Define the real child-to-parent relationship and record its rationale.</p><form id="relationship-form"><div class="form-grid">${tableChoice(p,'fromTable',first.id,'Child table')}${input('fromField','Child field name',first.headers[0])}${tableChoice(p,'toTable',second.id,'Parent table')}${input('toField','Parent field name',second.headers[0])}${choice('status','Interpretation status','Unknown',['Unknown','Inferred','Confirmed','Conflicting','Not Applicable'].map(x=>[x,x]))}</div>${area('reason','Rationale and evidence locator')}${citations(p)}<button class="button primary">Preview relationship checks</button></form><div id="relationship-preview"></div>`);const form=document.querySelector('#relationship-form');for(const type of ['input','change'])form.addEventListener(type,()=>document.querySelector('#relationship-preview').innerHTML='');form.onsubmit=safe(async ev=>{ev.preventDefault();const data=new FormData(form),v=Object.fromEntries(data),from=p.tables.find(t=>t.id===v.fromTable),to=p.tables.find(t=>t.id===v.toTable);if(from===to||!from.headers.includes(v.fromField)||!to.headers.includes(v.toField))throw Error('Select distinct tables and exact existing field names.');if(!v.reason.trim())throw Error('Record a relationship rationale.');if(p.relationships.some(r=>r.fromTable===v.fromTable&&r.fromField===v.fromField&&r.toTable===v.toTable&&r.toField===v.toField))throw Error('This exact relationship already exists; preserve its current assertion.');const evidence=data.getAll('evidence');if(v.status==='Confirmed'&&!evidence.length)throw Error('Cite preserved evidence before confirming a relationship.');const rel={id:crypto.randomUUID(),fromTable:v.fromTable,fromField:v.fromField,toTable:v.toTable,toField:v.toField,status:v.status,rationale:v.reason,evidence};const next=change(p,'review relationship',v.reason,next=>next.relationships.push(rel));const issues=validation(next).filter(x=>x.layer==='relationships');document.querySelector('#relationship-preview').innerHTML=`<h3>Relationship diagnostics</h3>${issues.map(i=>`<p>${pill(i.severity)} ${e(i.title)} — ${e(i.detail)}</p>`).join('')||'<p>No local relationship issues found. This does not establish scientific identity.</p>'}<button class="button primary" id="save-relationship">Save explicit relationship</button>`;document.querySelector('#save-relationship').onclick=safe(async()=>{if(getProject().revision!==p.revision)throw Error('Project changed; inspect a fresh relationship preview.');document.querySelector('#dialog').close();await save(next);});});}
 async function snapshots(){const p=getProject(),list=await json('/api/snapshots?id='+encodeURIComponent(p.id));modal('Recovery checkpoints',`<p>Compare a checkpoint, or restore it as a separate project. Current work remains retained.</p><div id="snapshot-list">${list.map(s=>`<section class="source-row"><h3>${e(s.name)}</h3><p>${e(s.at||s.createdAt||'Time unknown')}</p><button class="button" data-snapshot-compare="${e(s.id)}">Compare</button><button class="button" data-snapshot-restore="${e(s.id)}">Restore separately</button></section>`).join('')||'<p>No named snapshots yet. Create one in project recovery.</p>'}</div><div id="snapshot-comparison"></div>`);document.querySelectorAll('[data-snapshot-compare]').forEach(button=>button.onclick=safe(async()=>{const diff=await json('/api/snapshot-compare',{project:p,snapshotId:button.dataset.snapshotCompare});document.querySelector('#snapshot-comparison').innerHTML=`<h3>Checkpoint comparison</h3><pre>${e(JSON.stringify(diff,null,2))}</pre>`;}));document.querySelectorAll('[data-snapshot-restore]').forEach(button=>button.onclick=safe(async()=>{const result=await json('/api/snapshot-restore',{projectId:p.id,snapshotId:button.dataset.snapshotRestore});document.querySelector('#dialog').close();await openProject(result.id);notice('Verified checkpoint restored as a separate project.');}));}
 async function standardUpload(){modal('Validate a supplied standards package',`<p>Choose the actual package to inspect. A structural validation result does not certify scientific content or unknown target schemas.</p><form id="standard-upload"><label>Standards package<input type="file" name="file" required></label><button class="button primary">Run local validation</button></form><div id="standard-report"></div>`);document.querySelector('#standard-upload').onsubmit=safe(async ev=>{ev.preventDefault();const file=ev.target.elements.file.files[0];if(file.size>20*1024*1024)throw Error('Use the retained large-data workflow for packages above 20 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));const report=await json('/api/validate-standard',{source:{name:file.name,base64:btoa(binary)}});document.querySelector('#standard-report').innerHTML=`<h3>Local validation report</h3><pre>${e(JSON.stringify(report,null,2))}</pre>`;});}
 return async action=>{if(action==='operation'){operation();return true;}if(action.startsWith('operation:')){operation(action.slice(10));return true;}if(action==='relationship'){relationship();return true;}if(action==='snapshots'){await snapshots();return true;}if(action==='standard-upload'){await standardUpload();return true;}return false;};
}
