import {APP_VERSION} from '../../project.mjs';
import {escape as e,choice,bindChoices,pill} from '../design-system/controls.mjs';
import {icon} from '../design-system/icons.mjs';

function preview(resource){
 const p=resource.archaeology?.documentPreview;
 if(p)return `<p class="safety-note">Recovered preview may be partial. It is evidence to review; it does not replace the original or establish a scientific interpretation.</p>${p.reasonCode?`<p>${e(p.reasonCode)}</p>`:''}${(p.blocks||[]).slice(0,100).map(block=>`<article class="document-excerpt"><small>${e(block.kind)} · ${e(block.paragraph||block.page||block.cpStart||'Recorded location')}</small>${block.kind==='table'?`<pre>${e(JSON.stringify(block.rows,null,2))}</pre>`:`<blockquote>${e(block.text||'No recovered text')}</blockquote>`}${block.truncated?'<small>Preview truncated; inspect the retained original.</small>':''}</article>`).join('')}${p.trackedChanges?.length?`<details><summary>Recovered tracked changes</summary><pre>${e(JSON.stringify(p.trackedChanges,null,2))}</pre></details>`:''}${p.comments?.length?`<details><summary>Recovered comments</summary><pre>${e(JSON.stringify(p.comments,null,2))}</pre></details>`:''}`;
 if(/\.(txt|md)$/i.test(resource.name)&&resource.bytes<=128*1024){try{const text=new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(resource.base64),c=>c.charCodeAt(0)));return `<p class="safety-note">Literal UTF-8 preview. No meaning has been assigned.</p><pre>${e(text.slice(0,12000))}</pre>${text.length>12000?'<p>Preview bounded to 12,000 characters; retained original is complete.</p>':''}`;}catch{return '<p>No safe UTF-8 preview. Download the retained original and inspect its encoding.</p>';}}
 return `<p>No recovered document text is available here. Download the original to review its contents.</p><details><summary>Import archaeology and limitations</summary><pre>${e(JSON.stringify(resource.archaeology||{},null,2))}</pre></details>`;
}

export function mountEvidence(host,api){
 const {getProject,save,safe,notice}=api,p=getProject();let supersedes=null;
 host.innerHTML=`<div class="section-title"><div><span class="eyebrow">EVIDENCE RECORD</span><h2>Keep the source beside the assertion.</h2></div><button class="button" data-action="ocr-review">Review optional local OCR</button></div><div class="evidence-workbench"><section class="evidence-documents">${p.resources.map(r=>`<details class="source-row"><summary><strong>${e(r.name)}</strong> ${pill(r.role||'data')}</summary><p class="hash">${e(r.sha256)}</p><button class="button compact" data-action="original:${e(r.id)}">${icon('backup')}Download retained original</button>${preview(r)}</details>`).join('')}</section><section><h3>Record a reviewed assertion</h3><p>A citation does not overwrite a field definition or working value. Preserve competing assertions and record corrections as superseding entries.</p><form id="evidence-form"><div class="form-grid">${choice('table','Table',p.tables[0]?.id||'',p.tables.map(t=>[t.id,t.name]))}<label>Exact field name<input name="field" required></label>${choice('status','Interpretation status','Unknown',['Unknown','Inferred','Confirmed','Conflicting','Not Applicable'].map(x=>[x,x]))}${choice('source','Preserved source','',[['','No cited source'],...p.resources.map(r=>[r.id,r.name])])}</div><label>Recorded assertion<textarea name="value" required rows="3"></textarea></label><label>Exact locator<input name="locator" placeholder="Page, paragraph, row, cell, or line"></label><label>Rationale<textarea name="reason" required rows="3"></textarea></label><div class="form-grid"><label>Confidence as reported<input name="confidence"></label><label>Reviewer<input name="reviewer"></label></div><p id="superseded-context"></p><button class="button primary">Save immutable evidence entry</button></form></section></div><section><h3>Recorded assertions</h3>${(p.evidenceAssertions||[]).slice().reverse().map(a=>`<article class="assertion-row"><div>${pill(a.status,a.status==='Conflicting'?'warning':'neutral')}<strong>${e(a.field)}</strong><small>${e(a.at)}</small></div><blockquote>${e(a.value)}</blockquote><p>${e(a.rationale)}</p><small>${e(p.resources.find(r=>r.id===a.sourceId)?.name||'No cited source')} · ${e(a.locator||'No locator recorded')} · ${e(a.reviewer||'Reviewer unknown')}${a.supersedes?` · Supersedes ${e(a.supersedes)}`:''}</small><button class="button compact" data-correct-assertion="${e(a.id)}">Record a correction</button></article>`).join('')||'<p>No reviewed assertions recorded. Unknown remains a valid state.</p>'}</section>`;
 bindChoices(host);const form=host.querySelector('#evidence-form');
 host.querySelectorAll('[data-correct-assertion]').forEach(button=>button.onclick=()=>{const a=p.evidenceAssertions.find(a=>a.id===button.dataset.correctAssertion);supersedes=a.id;form.elements.field.value=a.field;const tableInput=form.querySelector('[name=table]');tableInput.value=a.tableId;form.querySelector('[name=table]').closest('.choice').querySelector('.choice-trigger').firstChild.textContent=p.tables.find(t=>t.id===a.tableId)?.name||a.tableId;host.querySelector('#superseded-context').textContent='Correction will supersede '+a.id+'. The earlier entry stays intact.';form.elements.value.focus();});
 form.onsubmit=safe(async ev=>{ev.preventDefault();const current=getProject();if(current.id!==p.id||current.revision!==p.revision)throw Error('Project changed. Reopen the evidence editor before recording this assertion.');const v=Object.fromEntries(new FormData(form)),table=p.tables.find(t=>t.id===v.table),resource=p.resources.find(r=>r.id===v.source);if(!table?.headers.includes(v.field))throw Error('Use an exact existing field name.');if(v.status==='Confirmed'&&(!resource||!v.locator.trim()))throw Error('Confirmed assertions require a preserved source and an exact locator.');if(supersedes){const old=p.evidenceAssertions.find(a=>a.id===supersedes);if(old.tableId!==table.id||old.field!==v.field)throw Error('A correction must address the same table and field as its earlier assertion.');}
  const at=new Date().toISOString(),assertion={id:crypto.randomUUID(),at,tableId:table.id,field:v.field,value:v.value,status:v.status,sourceId:resource?.id||'',sourceSha256:resource?.sha256||'',sourceBytes:resource?.bytes??null,locator:v.locator,rationale:v.reason,confidence:v.confidence,reviewer:v.reviewer,supersedes};const next=structuredClone(p);next.evidenceAssertions??=[];next.evidenceAssertions.push(assertion);next.audit.push({id:crypto.randomUUID(),at,action:'record evidence assertion',reason:v.reason,assertionId:assertion.id,applicationVersion:APP_VERSION});next.updatedAt=at;await save(next);mountEvidence(document.querySelector('#advanced-content'),api);notice('Evidence entry recorded. Original and competing assertions retained.');
 });
}

export function mountNotes(host,api){
 const {getWorkspace,getProject,saveWorkspace,safe}=api,workspace=getWorkspace();
 host.innerHTML=`<div class="section-title"><div><span class="eyebrow">INVESTIGATION NOTES</span><h2>A place for questions and context.</h2></div></div><p>Working annotations are separate from scientific assertions and exports. Record an observation here, then cite evidence explicitly when reviewing a meaning.</p><form id="note-form"><label>Note<textarea name="text" required maxlength="4000" rows="4"></textarea></label><button class="button primary">Save investigation note</button></form><div class="investigation-notes">${(workspace.notes||[]).slice().reverse().map(n=>`<article><small>${e(n.at||'Time unknown')}</small><p>${e(n.text)}</p></article>`).join('')||'<p>No investigation notes yet.</p>'}</div><h3>Bookmarked findings</h3>${(workspace.bookmarks||[]).map(b=>`<button class="digest-row" data-finding="${e(b.issue)}">${icon('review')}<span>${e(b.title||b.issue||b.view)}</span>${icon('arrow')}</button>`).join('')||'<p>No bookmarked findings.</p>'}`;
 host.querySelector('#note-form').onsubmit=safe(async ev=>{ev.preventDefault();const text=new FormData(ev.target).get('text');await saveWorkspace('notes',[...(getWorkspace().notes||[]),{id:crypto.randomUUID(),at:new Date().toISOString(),text,projectId:getProject().id}]);mountNotes(document.querySelector('#advanced-content'),api);});
}
