import {checkImportSelection,collectDroppedFiles} from '../../import-discovery.mjs';
import {escape as e,choice} from '../design-system/controls.mjs';
import {icon} from '../design-system/icons.mjs';
export const intakeLimits={files:100,perFile:20*1024*1024,total:50*1024*1024};
export function intakeMarkup(p,title){return `<p>Preserve exact source bytes. Inspect extraction before saving a working table.</p><form id="intake"><button type="button" class="source-drop-zone" id="source-drop-zone" aria-describedby="intake-limits"><span class="drop-icon">${icon('import')}</span><strong id="drop-heading">Drop files here</strong><span>or click anywhere to browse</span><small>CSV · TSV · Excel · text · documents · supporting evidence</small></button><input id="intake-files" name="file" type="file" multiple hidden tabindex="-1"><input id="intake-folder" name="folder" type="file" webkitdirectory multiple hidden tabindex="-1"><div class="heading-actions intake-add-actions"><button type="button" class="button" id="intake-add">${icon('plus')}Add more</button><button type="button" class="button" id="intake-choose-folder">${icon('library')}Choose folder</button><small>Paste copied Explorer files with Ctrl+V while this dialog is focused.</small></div><small id="intake-limits">100 files · 20 MiB per file · 50 MiB total. Bounded local extraction keeps memory use predictable. Use Large Data for larger CSVs.</small><p id="intake-error" role="alert" hidden></p><div id="source-queue" aria-live="polite"></div><div class="intake-title"><label>Project title<input name="title" maxlength="200" value="${e(title)}" required></label><label class="checkbox-label"><input name="support" type="checkbox">Supporting evidence only · preserve without data extraction</label></div><details class="intake-options"><summary>Parsing options · change only if extraction needs it</summary><p>Detection is a candidate configuration. These options apply to every queued file; inspect incompatible layouts separately.</p><div class="form-grid">${choice('textFormat','Text layout','delimited',[['delimited','Detect / delimited'],['fixed-width','Fixed width']])}<label>Fixed widths (decoded characters)<input name="fixedWidths" placeholder="8,12,6"></label>${choice('encoding','Text encoding',p.importEncoding||'auto',['auto','utf-8','utf-8-sig','utf-16','cp1252','latin-1'].map(x=>[x,x]))}${choice('delimiter','Separator',p.importDelimiter||'auto',[['auto','Detect'],[',','Comma'],['tab','Tab'],[';','Semicolon'],['|','Pipe']])}<label>Header row<input type="number" name="headerRow" min="1" max="1000" value="${p.importHeaderRow||1}"></label></div></details><div id="intake-preview" role="status"></div><div class="dialog-actions intake-sticky-actions"><small id="intake-readiness">Choose at least one file first.</small><button type="button" class="button primary" data-action="inspect-import" id="inspect-import" disabled>${icon('search')}Inspect extraction</button><button class="button primary" id="commit-import" disabled>${icon('validate')}Preserve & import</button></div></form>`;}
export function mountIntake(dialog,{native,invalidate,notice}){let queue=[],pending=false,disposed=false;const form=dialog.querySelector('#intake'),zone=form.querySelector('#source-drop-zone'),error=form.querySelector('#intake-error');dialog.classList.add('source-intake-dialog');const controller=new AbortController(),signal=controller.signal;dialog.addEventListener('close',()=>{disposed=true;controller.abort();dialog.classList.remove('source-intake-dialog');invalidate();},{once:true});
 const fail=problem=>{error.hidden=false;error.textContent=String(problem.message||problem);};
 function draw(){form.querySelector('#source-queue').innerHTML=queue.length?`<h3>${queue.length} ${queue.length===1?'file':'files'} ready to inspect</h3><div class="file-queue">${queue.map((f,i)=>`<div class="file-queue-row">${icon('sources')}<span><strong>${e(f.webkitRelativePath||f.name)}</strong><small>${e(f.name.split('.').pop()?.toUpperCase()||'File')} · ${(f.size/1024).toFixed(1)} KiB · Pending inspection</small></span><button class="icon-button" type="button" data-remove-source="${i}" aria-label="Remove ${e(f.name)}">${icon('close')}</button></div>`).join('')}</div>`:'';form.querySelector('#inspect-import').disabled=!queue.length;form.querySelector('#intake-readiness').textContent=queue.length?'Inspect extraction before preserving.':'Choose at least one file first.';}
 function add(files){if(disposed)return false;try{const next=[...queue,...files];checkImportSelection(next);queue=next;error.hidden=true;invalidate();draw();return true;}catch(problem){fail(problem);return false;}}
 function entries(items){if(disposed)return false;try{return add(items.map(entry=>{const file=new File([Uint8Array.from(atob(entry.base64),c=>c.charCodeAt(0))],entry.name.split('/').pop());Object.defineProperty(file,'webkitRelativePath',{value:entry.name});return file;}));}catch(problem){fail(problem);return false;}}
 async function choose(folder=false){if(pending)return;pending=true;try{if(native){const items=await native('native_intake',{folder});if(items.length)entries(items);}else form.querySelector(folder?'#intake-folder':'#intake-files').click();}catch(problem){fail(problem);}finally{pending=false;}}
 zone.onclick=()=>choose();form.querySelector('#intake-add').onclick=()=>choose();form.querySelector('#intake-choose-folder').onclick=()=>choose(true);for(const input of form.querySelectorAll('input[type=file]'))input.onchange=()=>{add([...input.files]);input.value='';};form.querySelector('#source-queue').onclick=ev=>{const b=ev.target.closest('[data-remove-source]');if(b){queue.splice(+b.dataset.removeSource,1);invalidate();draw();}};
 form.addEventListener('change',ev=>{if(ev.target.type!=='file'&&ev.target.name!=='title'){invalidate();form.querySelector('#intake-readiness').textContent='Options changed. Inspect extraction again.';}});
 for(const name of ['dragenter','dragover'])zone.addEventListener(name,ev=>{ev.preventDefault();zone.classList.add('drag-over');form.querySelector('#drop-heading').textContent='Release to add files';});zone.addEventListener('dragleave',()=>{zone.classList.remove('drag-over');form.querySelector('#drop-heading').textContent='Drop files here';});zone.addEventListener('drop',async ev=>{ev.preventDefault();zone.classList.remove('drag-over');form.querySelector('#drop-heading').textContent='Drop files here';try{const roots=[...(ev.dataTransfer?.items||[])].map(item=>item.webkitGetAsEntry?.()).filter(Boolean);add(roots.some(x=>x.isDirectory)?await collectDroppedFiles(roots):[...ev.dataTransfer.files]);}catch(problem){fail(problem);}});
 document.addEventListener('paste',ev=>{if(!dialog.open||!dialog.contains(document.activeElement)||document.activeElement.closest('input,textarea,[contenteditable=true]'))return;const files=[...(ev.clipboardData?.files||[])];if(files.length){ev.preventDefault();add(files);}},{signal});dialog.addEventListener('keydown',async ev=>{if(!native||!ev.ctrlKey||ev.key.toLowerCase()!=='v'||ev.target.closest('input,textarea,[contenteditable=true]'))return;ev.preventDefault();if(pending)return;pending=true;try{const items=await native('native_clipboard_intake');if(items.length)entries(items);else notice('No copied files found. Use Copy on files in Explorer, or browse. Clipboard text is not imported as a file.');}catch(problem){fail(problem);}finally{pending=false;}},{signal});
 draw();zone.focus();return {files:()=>queue.slice(),entries};
}
