import test from 'node:test';import assert from 'node:assert/strict';import {field} from '../web/project.mjs';import {comparisonPage} from '../web/comparison.mjs';
import {transform} from '../web/project.mjs';
test('comparison exposes literal duplicate/blank headers and distinguishes absent padded cells from recorded empty values',()=>{const table={headers:['id','id_2','column_3'],originalHeaders:['id','id'],columns:[field('id','id',0),field('id_2','id',1),field('column_3','column_3',2)],rows:[['001','',''],['002','','']],rowWidths:[1,3],originalTable:{headers:['id','id_2','column_3'],rows:[['001','',''],['002','','']]}};const page=comparisonPage(table,1);assert.equal(page.originalName,'id');assert.equal(page.rows[0].original,null);assert.equal(page.rows[1].original,'');assert.equal(comparisonPage(table,2).originalName,null);table.originalHeaders[1]='';assert.equal(comparisonPage(table,1).originalName,'');});
test('comparison retains original/working names and every primary derivation stage with companion inputs, mapping state and cited review basis',()=>{
 const table={headers:['speciesCode','unit','scientificName','scientificName__review','displayName','displayName__review'],columns:[field('speciesCode','sp',0),field('unit','u',1),{...field('scientificName'),status:'Inferred',term:'scientificName',derivation:{sourceFields:['speciesCode','unit'],operation:'codes',outcomeField:'scientificName__review'},confirmation:{basis:'evidence',reviewer:'Fictional reviewer',reason:'Fictional codebook',evidence:[{id:'r',sha256:'a'.repeat(64),bytes:40,locator:'row 1'}]},reviewBasis:'evidence'},field('scientificName__review'),{...field('displayName'),derivation:{sourceFields:['scientificName'],operation:'codes',outcomeField:'displayName__review'}},field('displayName__review')],rows:[['RAPI','literal companion','Rana pipiens','converted','Fictional display name','converted']],originalTable:{headers:['sp','u'],rows:[['RAPI','literal companion']]}};
 const before=structuredClone(table),page=comparisonPage(table,4);assert.deepEqual(table,before);assert.equal(page.originalName,'sp');assert.equal(page.field,'speciesCode');assert.equal(page.rows[0].original,'RAPI');assert.equal(page.rows[0].representations.length,2);const value=page.rows[0].representations[1];assert.deepEqual(value.trace,['speciesCode','scientificName','displayName']);assert.equal(value.inputs[0].working,'Rana pipiens');assert.equal(page.rows[0].representations[0].inputs[1].originalName,'u');assert.equal(page.rows[0].representations[0].inputs[1].original,'literal companion');assert.equal(page.rows[0].representations[0].term,'scientificName');assert.equal(page.rows[0].representations[0].mappingStatus,'Inferred');assert.equal(page.rows[0].representations[0].evidence[0].locator,'row 1');assert.deepEqual(comparisonPage(table,1).rows[0].representations.map(value=>value.trace),[['unit','scientificName'],['unit','scientificName','displayName']]);
});
test('comparison rejects cyclic, missing-primary and invalid-row provenance rather than inventing a trace',()=>{
 const table={headers:['a','b'],columns:[{...field('a'),derivation:{sourceFields:['b']}},{...field('b'),derivation:{sourceFields:['a']}}],rows:[['001','0']]};assert.throws(()=>comparisonPage(table,0),/CYCLE/);table.columns[0].derivation.sourceFields=['missing'];assert.throws(()=>comparisonPage(table,0),/REFERENCE/);delete table.columns[0].derivation;delete table.columns[1].derivation;table.rowOrigins=[-1];assert.throws(()=>comparisonPage(table,0),/REFERENCE/);
});
test('a derived measured value is compared with its primary source value rather than presented as a converted companion unit label',()=>{const table={headers:['temp','unit','reviewed_C','reviewed_C__review'],columns:[field('temp','temp',0),field('unit','unit',1),{...field('reviewed_C'),derivation:{sourceFields:['temp','unit'],outcomeField:'reviewed_C__review'}},field('reviewed_C__review')],rows:[['32','F','0','converted']],originalTable:{rows:[['32','F']]}};assert.equal(comparisonPage(table,0).rows[0].representations[0].value,'0');assert.deepEqual(comparisonPage(table,1).rows[0].representations.map(value=>value.trace),[['unit','reviewed_C']]);});
test('comparison follows reviewed outcomes through source/result renames and column reorder instead of reading adjacent values',()=>{const table={headers:['n','reviewed','reviewed__review','other'],columns:[field('n','n',0),{...field('reviewed'),derivation:{sourceFields:['n'],outcomeField:'reviewed__review',coverage:{converted:1}}},field('reviewed__review'),field('other','other',1)],rows:[[' NA ','','converted','unrelated literal']],rowOrigins:[0],primaryKey:[],originalTable:{headers:['n','other'],rows:[[' NA ','unrelated literal']]}};let current=transform(table,{op:'rename column',column:0,value:'recorded_count'}).table;current=transform(current,{op:'rename column',column:2,value:'row_outcome'}).table;current=transform(current,{op:'reorder column',column:2,value:'4'}).table;const representation=comparisonPage(current,1).rows[0].representations[0];assert.equal(representation.outcome,'converted');assert.equal(representation.value,'');assert.equal(comparisonPage(current,1).rows[0].original,' NA ');assert.deepEqual(table.rows,[[' NA ','','converted','unrelated literal']]);});
test('legacy reviewed outcomes use retained field identity and ordinary derived fields never acquire a guessed neighbor outcome',()=>{const table={headers:['n','outcome renamed','legacy_reviewed','other'],columns:[field('n','n',0),field('outcome renamed','legacy_reviewed__review'),{...field('legacy_reviewed'),derivation:{sourceFields:['n'],coverage:{converted:1}}},field('other')],rows:[['NA','converted','','literal']],originalTable:{rows:[['NA']]}};assert.equal(comparisonPage(table,0).rows[0].representations[0].outcome,'converted');delete table.columns[2].derivation.coverage;assert.equal(comparisonPage(table,0).rows[0].representations[0].outcome,null);});
test('comparison uses retained source-row origins after reordering and distinguishes recorded, working and derived literals',()=>{const table={headers:['count','reviewed_count','reviewed_count__review'],columns:[field('count','old_n',0),{...field('reviewed_count'),derivation:{sourceFields:['count']},reviewBasis:'evidence',status:'Inferred'},field('reviewed_count__review')],rows:[['0','0','unchanged'],[' NA ','','converted']],rowOrigins:[2,0],originalTable:{headers:['old_n'],rows:[[' NA '],['001'],['0']]}};const before=structuredClone(table),page=comparisonPage(table,1);assert.deepEqual(table,before);assert.equal(page.rows[0].sourceRow,3);assert.equal(page.rows[0].original,'0');assert.equal(page.rows[1].original,' NA ');assert.equal(page.rows[1].working,' NA ');assert.equal(page.rows[1].representations[0].value,'');assert.equal(page.rows[1].representations[0].basis,'evidence');});
test('comparison paginates without inferring unavailable original values or inventing representations',()=>{const table={headers:['n'],columns:[field('n')],rows:Array.from({length:100},(_,i)=>[String(i)])},page=comparisonPage(table,0,25,25);assert.equal(page.rows.length,25);assert.equal(page.rows[0].working,'25');assert.equal(page.rows[0].original,null);assert.deepEqual(page.rows[0].representations,[]);assert.throws(()=>comparisonPage(table,4),/INPUT/);assert.throws(()=>comparisonPage(table,0,0,10000),/INPUT/);});
