import test from 'node:test';import assert from 'node:assert/strict';import {DraftQueue,WriteBarrier} from '../web/drafts.mjs';
test('rapid A/B switching and delayed writes bind to immutable IDs',async()=>{const sent=[];const q=new DraftQueue(async p=>{sent.push(p);return {draftRevision:p.draftRevision+1};},{delay:()=>10000});q.schedule('A',4,{value:'A'});q.schedule('B',8,{value:'B'});await q.flush('A');q.schedule('A',4,{value:'A2'});await q.flushAll();assert.deepEqual(sent.map(p=>[p.projectId,p.baseRevision,p.forms.value,p.draftRevision]),[['A',4,'A',0],['A',4,'A2',1],['B',8,'B',0]]);assert.equal(q.pending,false);});
test('navigation waits through delayed save responses and their model assignment',async()=>{let release,active='A';const locks=[],barrier=new WriteBarrier(value=>locks.push(value)),gate=new Promise(resolve=>release=resolve);const saving=barrier.run(async()=>{await gate;active='saved A';});await Promise.resolve();let navigated=false;const navigation=barrier.flush().then(()=>{navigated=true;active='B';});await Promise.resolve();assert.equal(navigated,false);assert.equal(barrier.busy,true);release();await saving;await navigation;assert.equal(active,'B');assert.deepEqual(locks,[true,false]);});
test('failed in-flight committed save blocks the waiting navigation and releases controls',async()=>{let reject;const gate=new Promise((_,r)=>reject=r),barrier=new WriteBarrier();const save=barrier.run(()=>gate);await Promise.resolve();const switching=barrier.flush();reject(new Error('disk full'));await assert.rejects(save,/disk full/);await assert.rejects(switching,/disk full/);assert.equal(barrier.busy,false);});
test('all queued committed operations finish before navigation, without overlapping locks',async()=>{let release;const gate=new Promise(r=>release=r),events=[],locks=[],barrier=new WriteBarrier(x=>locks.push(x));const a=barrier.run(async()=>{events.push('A start');await gate;events.push('A done');});const b=barrier.run(()=>events.push('B'));const c=barrier.run(()=>events.push('C'));const nav=barrier.flush().then(()=>events.push('navigate'));release();await Promise.all([a,b,c,nav]);assert.deepEqual(events,['A start','A done','B','C','navigate']);assert.deepEqual(locks,[true,false]);});
test('draft forms are copied before later edits or project switches',async()=>{let captured;const q=new DraftQueue(async p=>{captured=p;return {draftRevision:1};},{delay:()=>10000});const forms={field:'literal'};q.schedule('A',1,forms);forms.field='changed';await q.flushAll();assert.equal(captured.forms.field,'literal');});
test('failed persistence blocks switching and preserves retry payload',async()=>{let fail=true;const q=new DraftQueue(async p=>{if(fail)throw Error('disk full');return {draftRevision:p.draftRevision+1};},{delay:()=>10000});q.schedule('A',1,{draft:'keep'});await assert.rejects(q.flush('A'),/disk full/);assert.equal(q.pending,true);fail=false;await q.flushAll();assert.equal(q.pending,false);});
test('edits arriving during persistence are sequenced using returned revision',async()=>{let finish;const sent=[];const q=new DraftQueue(p=>{sent.push(p);return sent.length===1?new Promise(r=>{finish=r;}):Promise.resolve({draftRevision:2});},{delay:()=>10000});q.schedule('A',1,{value:'first'});const flushing=q.flush('A');q.schedule('A',1,{value:'second'});finish({draftRevision:1});await flushing;assert.deepEqual(sent.map(p=>[p.forms.value,p.draftRevision]),[['first',0],['second',1]]);});
test('displaced draft is retained before explicit revision rebase',async()=>{const q=new DraftQueue(async()=>{throw Error('EDIT_AUTHORITY_LOST');},{delay:()=>10000});q.schedule('A',4,{value:'keep'});await assert.rejects(q.flush('A'),/AUTHORITY_LOST/);const retained=await q.suspend('A');assert.deepEqual(retained.forms,{value:'keep'});q.rebase('A',8);assert.equal(q.pending,false);assert.equal(q.entries.get('A').revision,8);assert.deepEqual(retained.forms,{value:'keep'});});

test('loss of editing authority pauses queued writes without discarding the payload',async()=>{const sent=[],q=new DraftQueue(async p=>{sent.push(p);return {draftRevision:1};},{delay:()=>10000});q.schedule('A',2,{description:'keep 001'});q.pause('A');await q.flushAll();assert.deepEqual(sent,[]);assert.equal(q.pending,true);const retained=await q.suspend('A');assert.equal(retained.forms.description,'keep 001');q.retire('A');assert.equal(q.pending,false);q.initialize('A',8);q.schedule('A',3,{description:'explicit new work'});await q.flush('A');assert.equal(sent[0].draftRevision,8);});
test('paused queue does not send edits queued during an in-flight rejected write',async()=>{let reject,sent=0;const q=new DraftQueue(()=>{sent++;return new Promise((_,r)=>reject=r);},{delay:()=>10000});q.schedule('A',2,{description:'first'});const running=q.flush('A');q.schedule('A',2,{description:'newest 001'});q.pause('A');reject(Error('EDIT_AUTHORITY_LOST'));await assert.rejects(running,/AUTHORITY_LOST/);assert.equal(sent,1);const retained=await q.suspend('A');assert.equal(retained.forms.description,'newest 001');q.retire('A');assert.equal(q.pending,false);});
