import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {screenImport,verifyImportRoundTrip,prepareImportReview} from '../web/import-screening.mjs';import {sanitize,rememberedParsing,useGuidedImport} from '../web/preferences.mjs';
const fixture=()=>({resource:{name:'fictional.csv',base64:Buffer.from('Fictional original').toString('base64'),bytes:18,sha256:createHash('sha256').update('Fictional original').digest('hex'),archaeology:{}},tables:[{headers:['recordID','date','lat','lon'],rows:[['001','04/05/08','91','0'],['NA','05/04/08','45','-180'],['0','2020-01-01','0','0'],['001','06/07/08','0x10','181'],['','2020','-90','NA']],parsing:{format:'delimited',encoding:'cp1252',delimiter:'\t',headerRow:2}}]});
test('bounded supplemental screening flags literal candidates without changing values or metadata',()=>{const imported=fixture(),before=structuredClone(imported),review=screenImport(imported,{});assert.deepEqual(imported,before);assert.equal(review.tables[0].coverageComplete,true);const f=review.tables[0].findings;assert.equal(f.find(f=>f.kind==='ambiguousDate').affectedSampleRecords,3);assert.equal(f.find(f=>f.kind==='identifierRepeat').examples[0].literalValue,'001');assert.equal(f.find(f=>f.kind==='identifierBlank').affectedSampleRecords,1);assert.equal(f.find(f=>f.kind==='coordinateRange'&&f.field==='lat').affectedSampleRecords,2);assert.equal(f.find(f=>f.kind==='coordinateRange'&&f.field==='lon').affectedSampleRecords,2);assert.ok(f.every(f=>f.candidateOnly));});
test('preferences actually disable supplemental passes while retaining coverage and original values',()=>{const imported=fixture(),review=screenImport(imported,{importCheckDates:false,importCheckCoordinates:false,importCheckIdentifiers:false});assert.deepEqual(review.tables[0].findings,[]);assert.equal(review.tables[0].sampledRecords,5);assert.equal(imported.tables[0].rows[0][0],'001');});
test('sample ceilings apply across tables and disclose incomplete coverage',()=>{const imported=fixture();imported.tables=[{headers:Array.from({length:100},(_,i)=>'field_'+i),rows:Array.from({length:2000},()=>Array(100).fill('0'))},{headers:['id'],rows:[['001']]}];const review=screenImport(imported,{});assert.equal(review.tables[0].sampledRecords,500);assert.equal(review.tables[0].coverageComplete,false);assert.equal(review.tables[1].sampledRecords,0);assert.equal(review.tables[1].coverageComplete,false);});
test('source round-trip verification rejects changed bytes, names, lengths and checksums before review receipt',async()=>{const imported=fixture(),source={name:imported.resource.name,base64:imported.resource.base64};assert.equal((await verifyImportRoundTrip(imported,source)).exactSourceRoundTrip,true);for(const change of [{base64:Buffer.from('changed').toString('base64')},{name:'other.csv'},{bytes:19},{sha256:'0'.repeat(64)}]){const changed={...imported,resource:{...imported.resource,...change}};await assert.rejects(prepareImportReview(changed,source,{}),/original|checksum/);assert.equal(changed.resource.archaeology.importScreening,undefined);}const reviewed=await prepareImportReview(imported,source,{importCheckDates:false});assert.equal(reviewed.resource.archaeology.importScreening.enabled.dates,false);assert.equal(reviewed.resource.archaeology.importScreening.integrity.sourceSha256,imported.resource.sha256);});
test('remembered parsing is opt-in and refuses mixed recipes, unsupported sources or fixed-width boundaries',()=>{const imported=fixture();assert.equal(rememberedParsing({},[imported]).importEncoding,'auto');const p=rememberedParsing({rememberImportChoices:true},[imported]);assert.equal(p.importEncoding,'cp1252');assert.equal(p.importDelimiter,'tab');assert.equal(p.importHeaderRow,2);for(const other of [{tables:[]},{tables:[{parsing:{format:'fixed-width',fixedWidths:[3,1]}}]},{tables:[{parsing:{...imported.tables[0].parsing,headerRow:3}}]}])assert.equal(rememberedParsing({rememberImportChoices:true},[imported,other]).importEncoding,'auto');});
test('guided/technical defaults are presentation choices and corrupted settings cannot invent scientific conventions',()=>{assert.equal(useGuidedImport({},'beginner'),true);assert.equal(useGuidedImport({},'advanced'),false);assert.equal(useGuidedImport({importReviewStyle:'guided'},'advanced'),true);assert.equal(useGuidedImport({importReviewStyle:'technical'},'beginner'),false);for(const importHeaderRow of [0,1001,true,'2',NaN])assert.equal(sanitize({importHeaderRow}).importHeaderRow,1);assert.equal(sanitize({importHeaderRow:1000}).importHeaderRow,1000);assert.equal(sanitize({importCheckDates:'false',dateOrder:'invented'}).importCheckDates,true);assert.equal('dateOrder' in sanitize({dateOrder:'invented'}),false);});
