import {knowledge} from '../../knowledge.mjs';
import {tutorialLessons} from '../../tutorial-registry.mjs';
import {helpWorkflows} from '../../help-workflows.mjs';
import {t} from '../../i18n.mjs';
import {getGlossary} from '../../glossary.mjs';
export const helpCategories=[['start','Getting started','Begin a rescue with preserved originals.'],['concepts','Understanding Bio','Evidence, uncertainty and responsible review.'],['data','Working with data','Read files, fields and relationships.'],['workflows','Workflows','Move from preservation to a verified package.'],['trouble','Troubleshooting','Investigate extraction and recovery problems.'],['access','Shortcuts & accessibility','Make the workspace work for you.']];
export const workspaceFor=route=>({'Project':'Overview','Inspect':'Understand','Metadata':'Advanced','Evidence':'Advanced','Relationships':'Advanced','Review queue':'Review','Translate & standardize':'Standardize','Standards Center':'Package','Export':'Package','Storage & Recovery':'Advanced','Snapshots':'Advanced','Large CSV':'Package'}[route]||route);
const additional=[
 ['project','What is a rescue project?','A rescue project keeps preserved files, working tables, reviewed meanings and an audit trail together.','Start with a survey and its protocol. Record unresolved meanings alongside documented ones.','A project is not a claim that all scientific meanings have been recovered.','Overview','start'],
 ['import','How do I import a CSV?','Add sources, choose or drop files, inspect extraction, then preserve the reviewed extraction. Automatic format detection is a parsing candidate, not scientific interpretation.','Check sample columns, encoding, separator and header row. Expand parsing options when a preview looks wrong.','Importing successfully does not establish a field’s scientific meaning.','Sources','data'],
 ['interpretation','Interpretation vs repair','Interpretation records what a value means and why. A repair changes an explicit working representation with a preview, reason and history.','Document that a source-defined token means missing before considering an explicit normalization of working values.','Do not apply a repair just to hide an unresolved interpretation.','Repair','concepts'],
 ['conflicts','What happens when evidence conflicts?','Retain competing assertions and their provenance. Record Conflicting when the available evidence disagrees; do not silently choose one source.','Two codebooks disagree about code 2. Keep both locators and investigate the applicable year and protocol.','A later filename alone does not establish authority.','Advanced','concepts'],
 ['no-guess','Why does Bio not guess?','A plausible pattern cannot establish a scientific meaning. Bio reports candidates with coverage and limits; a reviewer must examine supporting evidence.','A column called lat does not establish its coordinate reference system.','A confident-looking suggestion is not confirmation.','Review','concepts'],
 ['preserve','What does Preserve mean?','Keep the exact supplied source bytes and a recorded fingerprint separately from the working extraction.','Verify original-byte integrity and keep an independent backup before relying on a rescue.','A checksum supports byte integrity, not authenticity or scientific correctness.','Sources','workflows'],
 ['package','What is included in a rescue package?','Contents depend on the selected package purpose. Inspect the actual preview and verify the saved package: originals, working values, metadata, evidence, uncertainty and history may have different sharing rules.','Choose private preservation or a reviewed public sharing projection deliberately.','A private backup is not automatically safe to publish.','Package','workflows'],
 ['encoding','Why does my import look wrong?','Inspect extraction before committing. Check text encoding, separator, header row and, for fixed-width text, explicit character widths.','If a table has one wide column, review the separator. If characters are garbled, review the encoding against the original.','Do not repair garbled text until the extraction settings have been checked.','Sources','trouble'],
 ['file-open','Why will a file not open?','Read the exact extraction message. The file may be unsupported, encrypted, malformed or beyond a supported limit. Retain the original and consider preserving it as supporting evidence without extraction.','Use the existing Large Data workflow for larger CSVs; it has separate bounds and recovery rules.','Renaming a file extension does not convert its format.','Sources','trouble'],
 ['launcher','Launcher, updates and rollback','Open the root Launch Workbench.exe. It selects the explicitly active verified runtime. Updates require a configured source; local builds use the existing toolchain.','Save and close Workbench before activating a previous runtime from the launcher’s version history.','Do not launch a staging executable as the canonical application or assume an update service is configured.','Help','trouble'],
 ['accessibility','Keyboard shortcuts & accessibility','Ctrl+K opens global search; Up/Down select a result, Enter opens it, and Escape closes search. Tab and Shift+Tab traverse controls. Appearance settings include motion and contrast preferences.','Use the skip link to reach the workspace, and the native title bar for Windows dragging, snapping and window controls.','Reduced motion and a high-contrast palette do not substitute for screen-reader testing.','Settings','access'],
];
const categoryFor=id=>['rescue','originals','layers'].includes(id)?'start':['unknown','inferred','confirmation','evidence','integrity'].includes(id)?'concepts':['crash','restore','storage','large','encrypted','snapshots'].includes(id)?'trouble':['keyboard','selection'].includes(id)?'access':['repairs','share','blocked','warnings'].includes(id)?'workflows':'data';
const articles=[...knowledge.map(a=>({...a,category:categoryFor(a.id)})),...additional.map(([id,title,summary,example,mistake,route,category])=>({id,title,summary,example,mistake,route,category,keywords:[id],related:['unknown','evidence','confirmation']}))];
export const learningResources=[...articles.map(a=>({...a,id:'article/'+a.id,articleId:a.id,kind:'Help',workspace:workspaceFor(a.route),concepts:a.related||[],difficulty:'Foundation',content:[a.summary,a.example,a.mistake],relatedArticles:(a.related||[]).map(id=>'article/'+id)})),...tutorialLessons.map(l=>({id:'lesson/'+l.id,lessonId:l.id,title:l.title,summary:l.summary,keywords:[l.id,...l.steps.map(s=>s.route)],category:'workflows',workspace:workspaceFor(l.steps[0].route),concepts:[],difficulty:'Guided',kind:'Tutorial',content:l.steps.map(s=>s.body),relatedArticles:['article/evidence','article/originals']})),...Object.entries(helpWorkflows).map(([route,keys])=>({id:'workflow/'+route.toLowerCase().replace(/[^a-z]+/g,'-'),title:route+' workflow',summary:keys.map(key=>t('v07x.help.'+key)).join(' '),content:keys.map(key=>t('v07x.help.'+key)),keywords:[route,'workflow'],category:'workflows',workspace:workspaceFor(route),concepts:[],difficulty:'Workflow',kind:'Workflow',relatedArticles:['article/evidence','article/preserve']})),...getGlossary().map(([title,summary],i)=>({id:'concept/'+title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-'),title,summary,keywords:[title],category:'concepts',workspace:'Help',concepts:[title],difficulty:'Reference',kind:'Concept',content:[summary],relatedArticles:['article/unknown','article/evidence']}))];
export const learningPaths=[{id:'start',title:'Start here',summary:'Preserve first, then read the data and its limits.',lessons:['first-rescue','layers','understand','uncertainty']},{id:'investigate',title:'Investigate',summary:'Build a supported interpretation without guessing.',lessons:['evidence','uncertainty','missingness','codebooks','relationships']},{id:'repair',title:'Repair',summary:'Preview explicit changes and retain a recovery path.',lessons:['safe-repair','recovery','validation']}];
export function resource(id){return learningResources.find(r=>r.id===id||r.articleId===id);}
export function searchKnowledge(query,{limit=12,workspace}={}){const words=String(query).toLowerCase().match(/[\p{L}\p{N}]+/gu)||[];const stop=new Set(['what','is','a','the','how','do','i','why','does','bio','my','this','of','to','will','and','it','still','with','can','me']);const terms=words.filter(w=>!stop.has(w));if(!terms.length)return [];return learningResources.map(r=>{const title=r.title.toLowerCase(),keywords=r.keywords.join(' ').toLowerCase(),body=[r.summary,...r.content].join(' ').toLowerCase();let score=terms.reduce((n,w)=>n+(title.includes(w)?8:0)+(keywords.includes(w)?5:0)+(body.includes(w)?1:0),0);if(score&&workspace===r.workspace)score++;return {resource:r,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.resource.id.localeCompare(b.resource.id)).slice(0,limit).map(x=>x.resource);}
export function buddyAnswer(query,context={}){let id;if(/unknown|inferred|confirm/i.test(query))id=/inferred/i.test(query)?'inferred':/confirm/i.test(query)?'confirmation':'unknown';else if(/interpretation.*repair|repair.*interpretation/i.test(query))id='interpretation';else if(/missing|sentinel/i.test(query))id='missing';else if(/original|change.*file/i.test(query))id='originals';else if(/import|csv/i.test(query))id='import';else if(/evidence/i.test(query))id='evidence';else if(/guess/i.test(query))id='no-guess';const matches=id?[resource(id),...searchKnowledge(query,{limit:4,workspace:context.workspace}).filter(r=>r.articleId!==id)].filter(Boolean):searchKnowledge(query,{limit:4,workspace:context.workspace});const first=matches[0];return {summary:first?first.summary:'I could not find a supported explanation in the local field guide. Try a specific control, concept or workflow, or open Troubleshooting.',steps:first?.articleId==='unknown'?['Check the source protocol or codebook.','Inspect related columns and supporting files.','Record evidence, its locator and any remaining uncertainty.']:first?[first.example||first.content[0]].filter(Boolean):[],resources:matches.slice(0,3),workspace:first?.workspace||'Help',scientificChange:false};}
