import {uiLabel} from './i18n.mjs';
import {htmlMessage as uiText,t as uiValue} from './i18n.mjs';
// The native select owns the machine value; presentation never changes option values.
let serial=0;const refreshers=new WeakMap();
export function choicePlacement(rect,viewport,height=260){const gap=4,edge=8,width=Math.min(Math.max(rect.width,180),viewport.width-edge*2),below=viewport.height-rect.bottom-gap-edge,above=rect.top-gap-edge,up=below<Math.min(height,160)&&above>below,maxHeight=Math.max(48,Math.min(height,up?above:below));return {left:Math.max(edge,Math.min(rect.left,viewport.width-width-edge)),top:up?Math.max(edge,rect.top-gap-maxHeight):rect.bottom+gap,width,maxHeight,up};}
export function typeaheadIndex(labels,current,prefix){const repeated=[...prefix].every(x=>x===prefix[0]),query=repeated?prefix[0]:prefix,start=repeated?current+1:0;for(let n=0;n<labels.length;n++){const i=(start+n)%labels.length;if(labels[i].trim().toLocaleLowerCase().startsWith(query))return i;}return current;}
export function refreshChoices(){for(const select of document.querySelectorAll('select[data-enhanced]'))refreshers.get(select)?.();}
export function enhanceSelect(select){
 if(select.dataset.enhanced||select.multiple||select.size>1)return;
 const wrap=document.createElement('span');wrap.className='choice-control';const button=document.createElement('button');button.type='button';button.className='choice-button';button.setAttribute('role','combobox');button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');
 const value=document.createElement('span');value.className='choice-value';const arrow=document.createElement('span');arrow.className='choice-chevron';arrow.setAttribute('aria-hidden','true');arrow.innerHTML=`<svg viewBox="0 0 20 20" fill="none"><path d="m5 7 5 5 5-5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;button.append(value,arrow);
 const list=document.createElement('div');list.className='choice-list';list.id='choices-'+(++serial);list.role='listbox';list.hidden=true;button.setAttribute('aria-controls',list.id);
 const labelText=()=>select.getAttribute('aria-label')||[...(select.labels||[])].map(x=>[...x.childNodes].filter(n=>n!==select&&!n.classList?.contains('choice-control')).map(n=>n.textContent).join(' ').trim()).join(' ')||select.getAttribute('aria-label')||uiLabel('Choose an option');const label=labelText();button.setAttribute('aria-label',label);if(select.getAttribute('aria-describedby'))button.setAttribute('aria-describedby',select.getAttribute('aria-describedby'));list.setAttribute('aria-label',label);
 let active=select.selectedIndex,prefix='',timer,resize;
 const enabled=()=>[...select.options].map((o,i)=>i).filter(i=>!select.options[i].disabled&&!select.options[i].hidden&&!select.options[i].parentElement?.disabled);
 function paint(){const label=labelText();button.setAttribute('aria-label',label);list.setAttribute('aria-label',label);value.textContent=select.selectedOptions[0]?.textContent||uiLabel('Choose');button.disabled=select.disabled;button.setAttribute('aria-required',String(select.required));if(select.disabled)close();}
 function position(event){if(list.hidden||event?.target===list)return;if(!button.isConnected){close();return;}const place=choicePlacement(button.getBoundingClientRect(),{width:innerWidth,height:innerHeight},Math.min(260,list.scrollHeight));Object.assign(list.style,{left:place.left+'px',top:place.top+'px',width:place.width+'px',maxHeight:place.maxHeight+'px'});list.dataset.direction=place.up?'above':'below';}
 function highlight(){for(const node of list.children){node.classList.toggle('highlighted',+node.dataset.index===active);node.setAttribute('aria-selected',String(+node.dataset.index===select.selectedIndex));}const node=list.querySelector(`[data-index="${active}"]`);if(node){button.setAttribute('aria-activedescendant',node.id);node.scrollIntoView({block:'nearest'});}}
 function close(){list.hidden=true;button.setAttribute('aria-expanded','false');button.removeAttribute('aria-activedescendant');window.removeEventListener('resize',position);document.removeEventListener('scroll',position,true);resize?.disconnect();}
 function choose(index){if(select.disabled||index===undefined||!enabled().includes(index)){close();return;}select.selectedIndex=index;button.removeAttribute('aria-invalid');paint();close();select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));if(button.isConnected)button.focus();}
 function open(){paint();if(select.disabled)return;list.replaceChildren();for(const i of enabled()){const item=document.createElement('div');item.role='option';item.id=list.id+'-'+i;item.dataset.index=i;const text=document.createElement('span');text.textContent=select.options[i].textContent;const check=document.createElement('span');check.className='choice-check';check.textContent='✓';check.setAttribute('aria-hidden','true');item.append(text,check);item.onpointerdown=e=>e.preventDefault();item.onclick=()=>choose(i);list.append(item);}active=enabled().includes(select.selectedIndex)?select.selectedIndex:enabled()[0];list.hidden=false;button.setAttribute('aria-expanded','true');position();highlight();window.addEventListener('resize',position);document.addEventListener('scroll',position,true);if('ResizeObserver' in window){resize=new ResizeObserver(()=>position());resize.observe(button);}}
 button.onclick=()=>list.hidden?open():close();button.onkeydown=e=>{if(select.disabled){close();return;}const keys=['ArrowDown','ArrowUp','Home','End','Enter',' ','Escape','Tab'];if(keys.includes(e.key)){if(e.key==='Tab'){close();return;}e.preventDefault();if(e.key==='Escape'){close();return;}if(list.hidden){open();if(['Enter',' '].includes(e.key))return;}else if(['Enter',' '].includes(e.key)){choose(active);return;}const options=enabled(),i=options.indexOf(active);if(e.key==='Home')active=options[0];else if(e.key==='End')active=options.at(-1);else if(e.key==='ArrowDown')active=options[Math.min(i+1,options.length-1)];else if(e.key==='ArrowUp')active=options[Math.max(i-1,0)];highlight();}else if(e.key.length===1&&!e.ctrlKey&&!e.altKey&&!e.metaKey){e.preventDefault();clearTimeout(timer);prefix+=e.key.toLocaleLowerCase();timer=setTimeout(()=>prefix='',700);if(list.hidden)open();const options=enabled(),i=typeaheadIndex(options.map(i=>select.options[i].textContent),options.indexOf(active),prefix);active=options[i];highlight();}};
 button.onblur=close;button.onfocus=paint;select.addEventListener('change',paint);select.addEventListener('focus',()=>button.focus());select.addEventListener('invalid',()=>{button.setAttribute('aria-invalid','true');button.focus();});
 select.before(wrap);wrap.append(select,button,list);select.dataset.enhanced='true';select.classList.add('choice-native');select.tabIndex=-1;select.setAttribute('aria-hidden','true');refreshers.set(select,paint);paint();
}
export function startChoices(){for(const select of document.querySelectorAll('select'))enhanceSelect(select);const observer=new MutationObserver(records=>{if(records.some(r=>[...r.addedNodes].some(n=>n.nodeType===1&&!n.closest?.('.choice-control'))))for(const select of document.querySelectorAll('select:not([data-enhanced])'))enhanceSelect(select);if(records.some(r=>['SELECT','OPTION','OPTGROUP'].includes(r.target.tagName)))refreshChoices();});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['disabled','hidden','selected','required','aria-label','aria-describedby']});window.addEventListener('biorescue-language',refreshChoices);return observer;}
