import {t as structuralText,htmlMessage as structuralHtml} from './i18n.mjs';
import {field} from './project.mjs';
const fail=key=>{throw new Error('V062_'+key);};
export const WEBMERC_RADIUS=6378137,WEBMERC_EXTENT=Math.PI*WEBMERC_RADIUS;
const numeric=value=>{if(typeof value!=='string'||!/^[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?$/i.test(value)||!Number.isFinite(Number(value)))throw new Error(structuralText('v07.migrated.098ba5786af5'));return Number(value);};
export function inverseWebMercator(xLiteral,yLiteral){const x=numeric(xLiteral),y=numeric(yLiteral);if(Math.abs(x)>WEBMERC_EXTENT||Math.abs(y)>WEBMERC_EXTENT)throw new Error(structuralText('v07.migrated.7aefa7dad947'));const longitude=x/WEBMERC_RADIUS*180/Math.PI,latitude=(Math.PI/2-2*Math.atan(Math.exp(-y/WEBMERC_RADIUS)))*180/Math.PI;return {latitude:String(Number(latitude.toPrecision(15))),longitude:String(Number(longitude.toPrecision(15)))};}
export function translateCoordinatePair(table,spec){
 const column=spec.column,second=spec.pairedColumn,name=spec.name?.trim(),latName=name+'_latitude',lonName=name+'_longitude',stateName=name+'__review';if(spec.coordinatePolicy!=='webmerc-inverse-v1'||spec.targetCrs!=='EPSG:4326'||!['unknown','EPSG:3857'].includes(spec.sourceCrs))fail('COORDINATE_CRS');if(!Number.isInteger(column)||!Number.isInteger(second)||column===second||table.headers[column]!==spec.expectedInputName||table.headers[second]!==spec.expectedPairedName)fail('FIELD_CHANGED');if(!name||table.headers.length>247||[latName,lonName,stateName].some(n=>table.headers.includes(n)))fail('DERIVED_NAME');if(!spec.review?.reviewer?.trim())fail('COORDINATE_REVIEWER');if(spec.sourceCrs==='EPSG:3857'&&(spec.sourceAxes!=='easting-northing-metres'||spec.review.basis!=='evidence'||!spec.review.evidence.length))fail('COORDINATE_EVIDENCE');if(table.rows.length>100000)fail('COORDINATE_LIMIT');if(spec.upstreamOutcomePolicy!==undefined&&!['propagate','legacy-literal'].includes(spec.upstreamOutcomePolicy))fail('OPERATION');
 const next=structuredClone(table),counts={converted:0,unchanged:0,unresolved:0,conflicting:0,empty:0},examples=[],outcomes=[];const upstream=[column,second].map(index=>{const name=table.columns[index].derivation?.outcomeField;return {name,index:name?table.headers.indexOf(name):-1};});
 for(const [index,row]of next.rows.entries()){const x=row[column],y=row[second];if(typeof x!=='string'||typeof y!=='string')fail('FIELD_CHANGED');let state='unresolved',after={latitude:'',longitude:''},issue=null;const states=upstream.map(item=>{if(spec.upstreamOutcomePolicy!=='legacy-literal'&&item.name&&(item.index<0||!Object.hasOwn(counts,row[item.index])))fail('FIELD_CHANGED');return item.index>=0?row[item.index]:null;});
  if(x===''&&y==='')state='empty';else if(spec.upstreamOutcomePolicy!=='legacy-literal'&&states.includes('conflicting')){state='conflicting';issue='upstream';}else if(spec.upstreamOutcomePolicy!=='legacy-literal'&&states.includes('unresolved'))issue='upstream';else if(spec.sourceCrs==='unknown')issue='unknownCrs';else if(x===''||y==='')issue='missingComponent';else try{after=inverseWebMercator(x,y);state='converted';}catch(error){issue=error.message;}
  counts[state]++;outcomes.push(state);row.push(after.latitude,after.longitude,state);if(examples.length<10)examples.push({row:(table.rowOrigins?.[index]??index)+1,before:{easting:x,northing:y},after,state,coordinateIssue:issue});
 }
 // Classifying explicitly reviewed coordinate inputs is an audited privacy change.
 next.columns[column].sensitive=true;next.columns[second].sensitive=true;
 const common={status:spec.sourceCrs==='unknown'?'Unknown':counts.unresolved||counts.conflicting?'Inferred':'Confirmed',rationale:spec.review.reason,evidence:spec.review.evidence.map(e=>e.id),reviewerNotes:spec.review.reviewer,reviewBasis:spec.review.basis,confirmation:structuredClone(spec.review),sensitive:true,unit:'decimal degrees',derivation:{operation:'coordinate-pair',coordinatePolicy:spec.coordinatePolicy,sourceCrs:spec.sourceCrs,targetCrs:spec.targetCrs,sourceAxes:spec.sourceAxes||'unknown',targetAxes:'separate latitude and longitude fields in decimal degrees',radiusMetres:WEBMERC_RADIUS,implementedSquareExtentMetres:WEBMERC_EXTENT,sourceFields:[table.headers[column],table.headers[second]],outcomeField:stateName,coverage:counts,upstreamOutcomePolicy:spec.upstreamOutcomePolicy||'propagate',sourceSensitivityPolicy:'classify both reviewed inputs and outputs',unresolvedPolicy:'blank derived coordinates; literal source pair retained',accuracy:'No measurement accuracy, uncertainty improvement, epoch or datum-grid transformation asserted.'}};
 const latitude=field(latName),longitude=field(lonName),status=field(stateName);Object.assign(latitude,structuredClone(common),{description:'Reviewed inverse Web Mercator latitude; literal projected inputs retained.'});Object.assign(longitude,structuredClone(common),{description:'Reviewed inverse Web Mercator longitude; literal projected inputs retained.'});Object.assign(status,{status:'Confirmed',description:'Per-row reviewed coordinate-pair outcome; unresolved derived coordinates remain blank.',allowedValues:Object.keys(counts),rationale:spec.review.reason});next.headers.push(latName,lonName,stateName);next.columns.push(latitude,longitude,status);return {table:next,affected:counts.converted,examples,counts,outcomes};
}
