import {t,htmlMessage as h,localizeMessage} from './i18n.mjs';
const DWC='http://rs.tdwg.org/dwc/terms/';
const coreTypes=['Occurrence','Event','Taxon'];
const extensionTypes=[...coreTypes,'MeasurementOrFact','Identification','ResourceRelationship'];
export function mountDwcaExport(host,{getProject,json,esc,notice}){
 const project=getProject();if(!project)return;
 const tables=project.tables||[];let report=null,generation=0;
 const option=(value,label)=>`<option value="${esc(value)}">${esc(label)}</option>`;
 host.innerHTML=`<details class="panel" data-dwca><summary>${h('workspace.dwcaTitle')}</summary><p>${h('workspace.dwcaSafety')}</p><form data-dwca-form><label>${h('workspace.dwcaCore')}<select name="coreTable" required>${option('',t('workspace.dwcaChoose'))}${tables.map(table=>option(table.id,table.name||table.id)).join('')}</select></label><div data-dwca-config></div><button class="button secondary" type="submit">${h('workspace.dwcaPreview')}</button></form><div data-dwca-report role="status" aria-live="polite"></div><form data-dwca-download hidden><label>${h('workspace.dwcaReviewer')}<input name="reviewer" required maxlength="2000" autocomplete="off"></label><label>${h('workspace.dwcaReason')}<textarea name="reason" required maxlength="2000"></textarea></label><label class="checkbox-label"><input name="reviewed" type="checkbox" required>${h('workspace.dwcaAcknowledge')}</label><button class="button secondary" disabled>${h('workspace.dwcaSave')}</button></form></details>`;
 const form=host.querySelector('[data-dwca-form]'),config=host.querySelector('[data-dwca-config]'),output=host.querySelector('[data-dwca-report]'),saveForm=host.querySelector('[data-dwca-download]'),saveButton=saveForm.querySelector('button');
 const invalidate=()=>{generation++;report=null;saveButton.disabled=true;saveForm.hidden=true;output.textContent=t('workspace.dwcaNotPrepared');};
 const tableControls=(table,isCore)=>`<fieldset data-dwca-table="${esc(table.id)}"><legend>${isCore?h('workspace.dwcaCore'):h('workspace.dwcaExtension')}: ${esc(table.name||table.id)}</legend>${isCore?'':`<label class="checkbox-label"><input type="checkbox" data-dwca-include>${h('workspace.dwcaInclude')}</label>`}<label>${h('workspace.dwcaRowType')}<select data-dwca-type required>${option('',t('workspace.dwcaChoose'))}${(isCore?coreTypes:extensionTypes).map(type=>option(DWC+type,type)).join('')}</select></label><label>${h(isCore?'workspace.dwcaIdentifier':'workspace.dwcaLink')}<select data-dwca-key required>${option('',t('workspace.dwcaChoose'))}${table.headers.map((header,index)=>option(String(index),header)).join('')}</select></label><p>${h('workspace.dwcaMappingSafety')}</p>${table.headers.map((header,index)=>{const column=table.columns?.[index],recorded=column?.termIri||column?.termIRI||column?.termURI||(column?.term?(/^https?:\/\//.test(column.term)?column.term:DWC+column.term):'');return `<label>${esc(header)}<input data-dwca-term="${index}" type="url" maxlength="500" value="${esc(recorded)}" placeholder="${DWC}…"></label>`;}).join('')}</fieldset>`;
 form.elements.coreTable.onchange=()=>{const table=tables.find(item=>item.id===form.elements.coreTable.value);config.innerHTML=table?[tableControls(table,true),...tables.filter(item=>item.id!==table.id).map(item=>tableControls(item,false))].join(''):'';for(const fieldset of config.querySelectorAll('fieldset')){const include=fieldset.querySelector('[data-dwca-include]');if(include){const controls=[...fieldset.querySelectorAll('input,select')].filter(control=>control!==include);const enable=()=>{for(const control of controls)control.disabled=!include.checked;};include.onchange=enable;enable();}}invalidate();};
 form.addEventListener('input',invalidate);
 const selection=()=>{const specs=[...config.querySelectorAll('fieldset')].filter(node=>!node.querySelector('[data-dwca-include]')||node.querySelector('[data-dwca-include]').checked).map(node=>({tableId:node.dataset.dwcaTable,rowType:node.querySelector('[data-dwca-type]').value,key:node.querySelector('[data-dwca-key]').value===''?null:Number(node.querySelector('[data-dwca-key]').value),fields:[...node.querySelectorAll('[data-dwca-term]')].filter(input=>input.value.trim()).map(input=>({column:Number(input.dataset.dwcaTerm),term:input.value.trim()}))}));return {core:specs[0],extensions:specs.slice(1)};};
 form.onsubmit=async event=>{event.preventDefault();invalidate();const button=form.querySelector('[type=submit]');button.disabled=true;const requestGeneration=generation;try{const next=await json('/api/dwca-preview',{project:getProject(),selection:selection()});if(!host.isConnected||requestGeneration!==generation)return;report=next;output.innerHTML=`<p>${h('workspace.dwcaLocalPassed')}</p><ul>${next.tables.map(table=>`<li>${esc(table.name||table.tableId)} · ${table.rows} · ${table.mappedFields} ${h('workspace.dwcaMapped')} · ${table.unmappedFields} ${h('workspace.dwcaUnmapped')}</li>`).join('')}</ul><p>${h('workspace.dwcaExcluded',{count:next.excludedTableIds.length})}</p><p>${h('workspace.dwcaNoConformance')}</p><details><summary>${h('workspace.dwcaValidationDetails')}</summary><pre></pre></details>`;output.querySelector('pre').textContent=JSON.stringify(next.officialDescriptor,null,2);saveForm.hidden=false;saveForm.elements.reviewed.checked=false;saveButton.disabled=true;}catch(error){notice(localizeMessage(error.message),true);output.textContent=localizeMessage(error.message);}finally{button.disabled=false;}};
 saveForm.elements.reviewed.onchange=()=>{saveButton.disabled=!report||!saveForm.elements.reviewed.checked;};
 saveForm.onsubmit=async event=>{event.preventDefault();if(!report)return;saveButton.disabled=true;try{const result=await json('/api/dwca-export',{project:getProject(),selection:selection(),review:{reviewed:saveForm.elements.reviewed.checked,fingerprint:report.fingerprint,reviewer:saveForm.elements.reviewer.value,reason:saveForm.elements.reason.value}});if(!host.isConnected)return;const link=document.createElement('a');link.href='/api/large-link-download?token='+encodeURIComponent(result.token);link.download='private-reviewed-dwca.zip';link.click();notice(t('v065.downloadReady'));}catch(error){notice(localizeMessage(error.message),true);}finally{saveButton.disabled=!report||!saveForm.elements.reviewed.checked;}};
}
