import {t,htmlMessage as h} from './i18n.mjs';
import {getProfile,setProfile,ROLES,EXPERIENCES} from './workspace-profile.mjs';
export function firstRun(){
 const old=getProfile();let index=0;const selected={role:old.role,experience:old.experience};const focus=document.activeElement,dialog=document.createElement('dialog');dialog.className='first-run-dialog';dialog.setAttribute('aria-labelledby','first-run-title');
 const titles=['v07.welcomeTitle','v06.role.question','v06.experience.question','v07.safety','v07.readyTitle'];
 const bodies=['v07.welcomeBody','v06.presentationOnly','v06.beginnerExplanation','v07.safetyBody','v07.readyBody'];
 const choose=(name,keys)=>`<div class="onboarding-choices">${keys.map(key=>`<label><input type="radio" name="${name}" value="${key}" ${selected[name]===key?'checked':''}><span>${h('v06.'+name+'.'+key)}</span></label>`).join('')}</div>`;
 function finish(practice=false){setProfile({...old,...selected,configured:true});dialog.close();dialog.remove();focus?.isConnected&&focus.focus();if(practice)document.querySelector('[data-action=demo]')?.click();else document.querySelector('[data-action=new]')?.click();}
 function draw(){dialog.innerHTML=`<form><div class="eyebrow">${h('v07.onboardingStep',{step:index+1})}</div><h1 id="first-run-title">${h(titles[index])}</h1><p>${h(bodies[index])}</p>${index===1?choose('role',ROLES):index===2?choose('experience',EXPERIENCES):''}<div class="small-actions">${index?`<button type="button" class="button secondary" data-back>${h('previous')}</button>`:''}${index<4?`<button class="button primary">${h('next')}</button>`:`<button type="button" class="button primary" data-start>${h('v07.start')}</button><button type="button" class="button secondary" data-practice>${h('v07.practice')}</button>`}<button type="button" class="text-button" data-later>${h('v07.setupLater')}</button></div></form>`;dialog.querySelector('form').onchange=event=>{if(event.target.name)selected[event.target.name]=event.target.value;};dialog.querySelector('form').onsubmit=event=>{event.preventDefault();index++;draw();};dialog.querySelector('[data-back]')?.addEventListener('click',()=>{index--;draw();});dialog.querySelector('[data-start]')?.addEventListener('click',()=>finish());dialog.querySelector('[data-practice]')?.addEventListener('click',()=>finish(true));dialog.querySelector('[data-later]').onclick=()=>{setProfile({...old,...selected,configured:true});dialog.close();dialog.remove();};}
 dialog.oncancel=()=>{setProfile({...old,...selected,configured:true});dialog.remove();};document.body.append(dialog);draw();dialog.showModal();return dialog;
}
