import {analyzeProject} from './smart-analysis.mjs';
import {practiceCases} from './practice-catalog.mjs';
import {tutorialLessons,recommendedLessons,lessonFor} from './tutorial-registry.mjs';
import {getProfile} from './workspace-profile.mjs';
import {workflowHelp} from './help-workflows.mjs';
import {knowledge} from './knowledge.mjs';
import {htmlMessage as h,t} from './i18n.mjs';
import {toolLabel} from './workspace-profile.mjs';
import {esc} from './components.mjs';
import {getGlossary} from './glossary.mjs';
import {nativeSave} from './desktop-bridge.mjs';
import {privacyDiagnostics} from './workstation.mjs';
let category='home',lessonFilter='Recommended';
export function selectHelpArticle(id){if(knowledge.some(article=>article.id===id))category=id;}

const topics=['Project','Sources','Inspect','Evidence','Review queue','Repair','Translate & standardize','Standards Center','Validate','Export','Storage & Recovery','Large CSV','Settings'];
export function showHelpCenter({tour,getProject=()=>null}){
 const main=document.querySelector('#main');main.innerHTML=`<header class="page-heading"><div class="eyebrow">${h('v07.learn')}</div><h1>${h('v07.helpTitle')}</h1><p>${h('studio.helpIntro')}</p></header><label class="help-search">${h('v07.helpSearch')}<input id="help-search" type="search" data-tour-id="help-search"></label><div class="help-layout"><nav class="help-rail" aria-label="${h('v07.helpCategories')}">${['home',...topics,'glossary','tutorials','support'].map(key=>`<button data-help-topic="${key}" ${category===key?'aria-current="page"':''}>${esc(topics.includes(key)?toolLabel(key):t(key==='home'?'studio.helpHome':'v07.'+key))}</button>`).join('')}</nav><article id="help-reader" class="help-reader"></article></div>`;
 const reader=main.querySelector('#help-reader');
 const article=a=>`<div class="eyebrow">${h('v07.helpTitle')}</div><h2>${h('knowledge.'+a.id+'.title')}</h2><p class="article-summary">${h('knowledge.'+a.id+'.summary')}</p><section class="help-example"><h3>${h('studio.example')}</h3><p>${h('knowledge.'+a.id+'.example')}</p></section><h3>${h('studio.mistake')}</h3><p>${h('knowledge.'+a.id+'.mistake')}</p>${workflowHelp(a.route)}<div class="help-related"><button class="button primary" data-section="${a.route}">${h('v07.showMe')}</button><button class="button secondary" data-help-lesson="${lessonFor(a.id)?.id||lessonFor(a.route)?.id||a.route}">${h('v07.tutorials')}</button>${(a.related||[]).filter(id=>id!==a.id).map(id=>`<button class="button secondary" data-knowledge="${id}">${h('knowledge.'+id+'.title')}</button>`).join('')}</div>`;
 function draw(){const term=main.querySelector('#help-search').value.trim().toLocaleLowerCase();
  if(term){const found=knowledge.filter(a=>[a.title,a.summary,a.example,a.mistake,...(a.keywords||[]),toolLabel(a.route)].join(' ').toLocaleLowerCase().includes(term)),definitions=getGlossary().filter(e=>e.join(' ').toLocaleLowerCase().includes(term));reader.innerHTML=`<div class="help-question-list">${found.map(a=>`<button data-knowledge="${a.id}">${h('knowledge.'+a.id+'.title')}</button>`).join('')}</div>`+definitions.map(([title,body])=>`<section class="help-result"><h2>${esc(title)}</h2><p>${esc(body)}</p></section>`).join('')||`<p role="status">${h('v07.noMatches')}</p>`;if(!found.length&&!definitions.length)reader.innerHTML=`<p role="status">${h('v07.noMatches')}</p>`;return;}
  const selected=knowledge.find(a=>a.id===category);if(selected){reader.innerHTML=article(selected);return;}
  if(topics.includes(category)){const a=knowledge.find(a=>a.route===category);reader.innerHTML=a?article(a):`<h2>${esc(toolLabel(category))}</h2><p>${h('v06.help.'+category)}</p>${workflowHelp(category)}<button class="button primary" data-section="${category}">${h('v07.showMe')}</button>`;return;}
  if(category==='home'){const project=getProject(),findings=project?analyzeProject(project).items:[],suggested=[...new Set(findings.map(item=>({coordinate:'coordinates',date:'dates',missing:'missing',taxonomy:'codebook',mapping:'dwc',privacy:'coordinates',conflict:'conflict'})[item.kind]).filter(id=>knowledge.some(article=>article.id===id)))].slice(0,3);reader.innerHTML=`<span class="eyebrow">LEARN WITH YOUR DATA</span><h2>What would you like to understand?</h2><p class="article-summary">Find a practical answer, explore a workflow, or learn safely with a fictional dataset.</p><div class="v6-help-recommendations"><h3>${project?'Recommended for this project':'Start here'}</h3><div class="help-question-list">${(suggested.length?suggested:['rescue','unknown','inferred']).filter(id=>knowledge.some(article=>article.id===id)).map(id=>`<button data-knowledge="${id}">${h('knowledge.'+id+'.title')} ↗</button>`).join('')}</div><small>${project?'Recommendations come from candidate patterns; they do not confirm meaning.':'Preserve first. Scientific decisions require evidence.'}</small></div><div class="help-home-grid"><button data-help-home="tutorials"><strong>Tutorial Center</strong><p>Short lessons, real controls, and project-scoped progress.</p></button><button data-knowledge="crash"><strong>Recover your work</strong><p>Drafts, saved revisions, snapshots and backups.</p></button></div><h3>Browse by workflow</h3><div class="v6-help-workflow">${topics.slice(0,10).map(route=>`<button class="text-button" data-help-home="${route}">${esc(toolLabel(route))} ↗</button>`).join('')}</div><h3>Popular questions</h3><div class="help-question-list">${knowledge.slice(0,12).map(article=>`<button data-knowledge="${article.id}">${h('knowledge.'+article.id+'.title')}</button>`).join('')}</div><button class="text-button" data-help-home="support">Prepare a support request ↗</button>`;return;}

  if(category==='glossary'){reader.innerHTML=`<h2>${h('v07.glossary')}</h2><dl class="glossary-list">${getGlossary().map(([title,body])=>`<div><dt>${esc(title)}</dt><dd>${esc(body)}</dd></div>`).join('')}</dl>`;return;}
  if(category==='tutorials'){const project=getProject(),recommended=new Set(recommendedLessons(getProfile(),project).map(l=>l.id));const completed=id=>{try{const saved=JSON.parse(localStorage.getItem('biorescue-product-tour-v3-'+id+'-'+(project?.id||'workspace')));return saved?.state==='complete'&&!saved.failed?.length;}catch{return false;}};const lessons=tutorialLessons.filter(l=>lessonFilter==='Recommended'?recommended.has(l.id):lessonFilter==='Completed'?completed(l.id):lessonFilter==='Standards'?/dwc|standard|crate|eml|camtrap/i.test(l.id):lessonFilter==='Beginner'?['first-rescue','import','understand','uncertainty','evidence','repair'].includes(l.id):lessonFilter==='Advanced'?/relationship|date|coordinate|large|recovery/i.test(l.id):true);reader.innerHTML=`<span class="eyebrow">SHORT LESSONS, REAL WORKFLOWS</span><h2>Tutorial Center</h2><button class="button secondary" data-help-tour>Meet the Workbench ↗</button><p>${h('workspace.lessonBoundary')}</p><nav class="v6-tutorial-filters" aria-label="Tutorial categories">${['Recommended','Beginner','Workflow','Standards','Advanced','Completed'].map(label=>`<button class="button secondary" data-lesson-filter="${label}" aria-pressed="${lessonFilter===label}">${label}</button>`).join('')}</nav><div class="lesson-grid">${lessons.map(l=>`<article><span class="eyebrow">${completed(l.id)?'CONTROLS OBSERVED':l.steps.length+' STEPS'}</span><h3>${h('lesson.'+l.id+'.title')}</h3><p>${h('lesson.'+l.id+'.summary')}</p><button class="button secondary" data-help-lesson="${l.id}">${completed(l.id)?'Revisit lesson':'Begin lesson'} ↗</button></article>`).join('')||'<p>No lessons in this category yet.</p>'}</div><h3>Practice with fictional data</h3>${practiceCases.map(p=>`<article><h3>${h('practice.'+p.id+'.title')}</h3><p>${h('practice.'+p.id+'.focus')}</p><button class="button secondary" data-action="${p.action||'practice'}" data-practice="${p.id}">${h('v07.open')}</button></article>`).join('')}`;return;}

  support(reader);
 }
 main.querySelector('#help-search').oninput=draw;main.querySelectorAll('[data-help-topic]').forEach(button=>button.onclick=()=>{category=button.dataset.helpTopic;main.querySelector('#help-search').value='';main.querySelectorAll('[data-help-topic]').forEach(node=>node.setAttribute('aria-current',node===button?'page':'false'));draw();});reader.addEventListener('click',event=>{const question=event.target.closest('[data-knowledge],[data-help-home]');if(question){category=question.dataset.knowledge||question.dataset.helpHome;main.querySelector('#help-search').value='';draw();reader.scrollIntoView({block:'start'});}const filter=event.target.closest('[data-lesson-filter]');if(filter){lessonFilter=filter.dataset.lessonFilter;draw();}const lesson=event.target.closest('[data-help-lesson]');if(lesson)tour({module:lesson.dataset.helpLesson});if(event.target.closest('[data-help-tour]'))tour({module:'interface'});});draw();
}
function support(reader){
 const categories=['question','bug','improvement','backup','importProblem','standards','access','desktop','other'];const diagnostics={...privacyDiagnostics(),operatingSystem:navigator.platform||'Not exposed',storageHealth:'Requires Recovery inspection',errorIds:[]};
 reader.innerHTML=`<div class="eyebrow">${h('studio.support')}</div><h2>${h('v07.support')}</h2><p>${h('studio.delivery')}</p><div class="support-types">${categories.map(key=>`<button type="button" class="button secondary" data-support-category="${key}">${h('studio.'+key)}</button>`).join('')}</div><div class="support-layout"><form id="support-form"><label>${h('v07.category')}<select name="category">${categories.map(key=>`<option value="${key}">${h('studio.'+key)}</option>`).join('')}</select></label><label>${h('v07.subject')}<input name="subject" maxlength="200" required></label><label>${h('v07.description')}<textarea name="description" rows="4" maxlength="10000" required></textarea></label><label>${h('studio.trying')}<textarea name="trying" rows="2" maxlength="4000"></textarea></label><label>${h('studio.happened')}<textarea name="happened" rows="2" maxlength="4000"></textarea></label><label>${h('v07.contact')}<input name="contact" maxlength="300"></label><label>${h('studio.screenshot')}<input type="file" data-support-screenshot accept="image/png,image/jpeg"></label><p class="muted">${h('studio.screenshotHelp')}</p><img data-screenshot-preview hidden alt="Selected support screenshot"><label class="checkbox-label"><input name="diagnostics" type="checkbox">${h('v07.diagnostics')}</label><button class="button primary">${h('v07.prepare')}</button></form><aside><h3>${h('studio.diagnosticPreview')}</h3><pre class="diagnostic-preview">${esc(JSON.stringify(diagnostics,null,2))}</pre><p>${h('v07.supportPrivacy')}</p></aside></div><p data-support-status role="alert" hidden></p><section id="support-result" hidden><p role="status">${h('v07.prepared')}</p><pre id="support-preview" class="diagnostic-preview"></pre><button class="button secondary" data-support-copy>${h('v07.copy')}</button><button class="button secondary" data-support-download>${h('v07.download')}</button></section>`;
 let request=null,screenshot=null,url=null;reader.querySelectorAll('[data-support-category]').forEach(button=>button.onclick=()=>{reader.querySelector('[name=category]').value=button.dataset.supportCategory;reader.querySelector('[name=subject]').focus();});
 reader.querySelector('[data-support-screenshot]').onchange=async event=>{screenshot=null;if(url)URL.revokeObjectURL(url);const preview=reader.querySelector('[data-screenshot-preview]');preview.hidden=true;const file=event.target.files[0];if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024){event.target.value='';reader.querySelector('[data-support-status]').hidden=false;reader.querySelector('[data-support-status]').textContent=t('studio.attachmentLimit');return;}reader.querySelector('[data-support-status]').hidden=true;reader.querySelector('#support-form button.primary').disabled=true;try{const base64=await new Promise((resolve,reject)=>{const loader=new FileReader();loader.onload=()=>resolve(loader.result.split(',')[1]);loader.onerror=()=>reject(loader.error);loader.readAsDataURL(file);});screenshot={name:file.name,type:file.type,base64};preview.src='data:'+file.type+';base64,'+base64;preview.hidden=false;}catch{event.target.value='';reader.querySelector('[data-support-status]').hidden=false;reader.querySelector('[data-support-status]').textContent=t('studio.screenshotReadFailed');}finally{reader.querySelector('#support-form button.primary').disabled=false;}};
 reader.querySelector('form').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target);request={category:t('studio.'+form.get('category')),subject:form.get('subject'),description:form.get('description'),trying:form.get('trying'),happened:form.get('happened'),contact:form.get('contact'),...(form.has('diagnostics')?{diagnostics}:{}),...(screenshot?{screenshot}:{}),delivery:'Prepared locally; not submitted.'};reader.querySelector('#support-preview').textContent=JSON.stringify({...request,...(screenshot?{screenshot:{name:screenshot.name,type:screenshot.type,included:true}}:{})},null,2);reader.querySelector('#support-result').hidden=false;};
 reader.querySelector('[data-support-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(request,null,2));reader.querySelector('[role=status]').textContent=t('v07.copied');}catch{reader.querySelector('[data-support-status]').hidden=false;reader.querySelector('[data-support-status]').textContent=t('studio.copyFailed');}};
 reader.querySelector('[data-support-download]').onclick=async()=>{const contents=JSON.stringify(request,null,2);if(window.__TAURI_INTERNALS__){try{const saved=await nativeSave(contents,'workbench-support-request.json');reader.querySelector('[role=status]').textContent=t(saved?'studio.saved':'studio.cancelled');}catch(error){reader.querySelector('[role=status]').textContent=String(error);}return;}const download=URL.createObjectURL(new Blob([contents],{type:'application/json'})),link=document.createElement('a');link.href=download;link.download='workbench-support-request.json';link.click();setTimeout(()=>URL.revokeObjectURL(download),30000);};
}

