// Product guidance only; no research values or automatic scientific decisions.
export const knowledge=[
 ['rescue','What is biodiversity data rescue?','Recover an archive’s usability while keeping its original bytes, uncertainty and evidence. A useful rescue can preserve an unresolved meaning rather than invent an answer.','A 2001 survey contains observations and a separate codebook. Preserve both, inspect the columns, then record meanings supported by the codebook.','Treating a clean-looking table as proof that its scientific interpretation is correct.','Project'],
 ['originals','Will Workbench change my original files?','Imported sources are preserved separately from the working table. Repairs act on a working representation; original-byte verification remains a separate check.','A working value changes from " AM01 " to "AM01" after a reviewed trim. The source download still contains the original spaces.','Assuming a saved project is an independent backup of all original bytes.','Sources'],
 ['layers','What are Source, Working copy and Reviewed output?','Source shows imported material; Working copy contains reversible repairs; Reviewed output contains explicit interpretations and derived values. These views do not mean three different levels of scientific truth.','A source date "03/04/01" remains literal until a researcher establishes the convention. A reviewed derived date may then be recorded with evidence.','Assuming Reviewed output means every row or field has been confirmed.','Inspect'],
 ['inferred','What does Inferred mean?','A plausible interpretation has been recorded, with its basis and limits. It is weaker than confirmation by suitable evidence and review.','A header named lat is a coordinate candidate. That pattern alone cannot establish the coordinate reference system.','Promoting a pattern match to Confirmed without supporting evidence.','Review queue'],
 ['unknown','What does Unknown mean?','There is not enough evidence to assign a meaning or value. Unknown is a valid research outcome and can remain in a preservation package.','A column marked C has values 1 and 2, but no surviving codebook. Record the uncertainty instead of choosing a meaning.','Replacing uncertainty with a convenient guess to make validation pass.','Metadata'],
 ['dates','Why will Workbench not guess this date?','Dates can have multiple valid conventions. The assistant reports candidates and ambiguous examples without selecting day/month order, calendar or century.','03/04/01 might be 3 April or March 4. Review documentation and geographic context, then explicitly choose a supported convention.','Using the operating system’s date display locale to reinterpret scientific source values.','Translate & standardize'],
 ['evidence','What is evidence?','Preserved documents, codebooks, methods and recorded assertions help explain an interpretation. A citation should include a useful locator and a rationale.','Link count to Methods.txt, section “Counts”, and record the wording that defines what was counted.','Linking a whole document without explaining which passage supports the field meaning.','Evidence'],
 ['confirmation','What counts as confirmation?','A responsible reviewer records a supported interpretation, its evidence, rationale and limits. Completing a queue task or running a validator does not automatically confirm a field.','A methods document states that distance_m is measured in metres; cite that statement when reviewing the unit.','Confusing an Accepted queue disposition with a Confirmed scientific status.','Metadata'],
 ['missing','What is a missing-value token?','A literal token may represent missing data, a code or a valid observation. The assistant identifies candidates, but the researcher must establish the convention.','0 may be a recorded zero count; NA may be a source-defined category or missing marker. Preserve both literals until documentation resolves their meaning.','Treating zero, blank, NA and unknown as equivalent.','Review queue'],
 ['warnings','What does a warning mean?','Warnings identify attention points with evidence and limits. Blocking errors prevent particular actions; review warnings may require judgment; informational notes disclose context.','A candidate date convention needs human review, while a malformed package dependency may block a particular standards export.','Ignoring every warning because an earlier warning was only advisory.','Validate'],
 ['blocked','Why is a standards export blocked?','A target may require fields, relationships, profile dependencies or explicit interpretations that are not yet available. Read the actual blocking report and support level.','A package requiring a location key cannot establish it from a similarly named field alone. Review the relationship and check again.','Removing a safeguard solely to obtain a standards badge.','Standards Center'],
 ['dwc','What is Darwin Core?','Darwin Core provides biodiversity terms for sharing information about organisms, occurrences, events and related context. Candidate mappings need review; mapping alone does not guarantee a valid or complete publication.','A documented species-name field may map to scientificName. An undocumented abbreviation sp is only a candidate.','Assuming every spreadsheet has an occurrence-based data model.','Standards Center'],
 ['eml','What is EML?','Ecological Metadata Language describes ecological datasets and their research context. Metadata completeness, schema checks and scientific quality are separate questions.','Methods, coverage and licensing help another researcher understand a survey even when some field meanings remain Unknown.','Claiming full EML support or scientific validity from a guide-level check.','Standards Center'],
 ['share','What should I do before sharing data?','Verify preserved sources, review unresolved interpretations, choose a package purpose, examine privacy rules and inspect the actual export preview.','A public package may omit exact sensitive locations while a private preservation package retains material needed for recovery.','Sharing a private backup because its filename resembles a public package.','Export'],
 ['storage','Where is my project stored?','Desktop data normally live in the local Workbench data directory. Browser developer storage depends on the server’s selected data directory. The two workspaces are not silently merged.','A repository browser project does not automatically appear in a new desktop workspace. Use an explicit verified backup/copy workflow.','Moving an active workspace or assuming uninstalling the application is a backup strategy.','Storage & Recovery'],
 ['restore','How do I restore a project?','Keep the current project and independent backup first. Open a supported backup through the existing restore workflow, inspect the result and verify original-byte integrity.','Restore a fictional backup into a separate test workspace before relying on it for a research recovery.','Deleting the only working copy before proving a backup can be restored.','Storage & Recovery'],
 ['crash','What happens if Workbench crashes?','Committed revisions, recoverable drafts and retained window copies have different roles. Review Recovery after relaunch; never assume every in-memory change was committed.','A takeover retains the former editor’s unsaved forms separately. Download and compare that retained copy before deciding what to restore.','Overwriting the current project with an older copy before comparing revisions.','Storage & Recovery'],
 ['codebook','How do I use a codebook?','Import the codebook as evidence, inspect exact code overlap and conflicting definitions, then record an explicit reviewed derivation with a locator and rationale.','AM01 has one codebook definition in one year and another in a later year. Preserve both meanings as a conflict until the context is resolved.','Automatically replacing every code with the first matching label.','Evidence'],
 ['species','How do I review species names?','Inspect the literal field, documentation and appropriate taxonomic context. Workbench can identify candidate taxonomy fields; it does not establish species identity from a header or pattern.','A legacy abbreviation may refer to a local species list. Cite that list and record the interpretation’s uncertainty.','Treating text normalization or a candidate mapping as a taxonomic determination.','Inspect'],
 ['keys','What is a relationship key?','A key connects records through an exact shared value. Check blank values, repeated parent keys, matches and orphan records before accepting a scientific relationship.','001 and 1 are distinct literals unless an explicitly reviewed transformation establishes equivalence.','Trimming or parsing identifiers before reviewing whether that changes their identity.','Relationships'],
 ['coordinates','How do I handle sensitive coordinates?','Identify potential location fields, review their meaning and privacy status, and inspect the public export policy. Candidate detection cannot establish sensitivity, datum or permission to publish.','An exact nest location may need omission or a reviewed coarsening policy before a public package is prepared.','Publishing precise values because the assistant did not flag an unusual column name.','Export'],
 ['large','How does Large Data mode work?','Large CSV tools use separate bounded server-side workflows. The ordinary assistant samples rows and cells; its coverage statement must accompany candidate findings.','A 500,000-row file is not fully assessed because a 1,000-row sample looks consistent. Use the large-data tools for the supported task and retain the source.','Claiming that a bounded sample establishes complete absence of errors.','Large CSV'],
 ['units','How should I review units?','A column suffix or neighboring unit field provides a candidate, not a scientific unit definition. Review documentation before choosing a conversion or creating a derived field.','length_cm suggests centimetres, but a methods note may describe a legacy coding system. Review the note before converting values.','Converting units based only on a field name.','Translate & standardize'],
 ['repairs','Which repairs are safe?','Mechanical repairs can be reversible and still change important literals. Preview every affected example and supply a reason; interpretive changes require appropriate evidence and explicit review.','Leading whitespace in a comment may be harmless, while whitespace in a specimen identifier may be significant.','Applying a batch because it is labelled mechanical without inspecting its effect.','Repair']
 ,['integrity','What does a checksum prove?','Matching SHA-256 values support byte-for-byte source integrity. They do not establish who authored the file, whether the data are correct or whether a meaning is supported.','A preserved workbook verifies against its recorded hash while its count convention remains Unknown.','Treating an integrity pass as a scientific validation pass.','Sources']
 ,['citation','How do I cite the rescued collection?','Record creators, dates, rights, related publications and the citation in project metadata. Keep source provenance separate from your interpretation and release description.','Cite the original collection and describe the reviewed working version with its limitations.','Claiming that Workbench created the original observations or assigning rights that were not documented.','Metadata']
 ,['snapshots','Is a snapshot a backup?','A snapshot records a local recovery point. An independent portable backup retains a separate copy that should be verified and restored in a test workspace.','Create a named checkpoint before repair and keep a verified portable backup outside the active workspace.','Relying on a snapshot stored beside the only source files after disk loss.','Snapshots']
 ,['encrypted','What should I check with encrypted backups?','Keep the passphrase separately, preserve the encrypted file and test restore into a separate copy. Encryption does not remove the need to verify that the backup includes the intended material.','Restore a fictional encrypted backup before using the process for important research.','Losing the passphrase or assuming an encrypted project automatically contains separate large-data indexes.','Export']
 ,['differences','What does a difference between tables mean?','A comparison identifies changed literals, records or structure. It cannot decide which version is authoritative or whether two scientific observations are equivalent.','Two files called FINAL disagree on one count. Record the disagreement and investigate the evidence.','Selecting the newer filename as the scientifically correct version.','Inspect']
 ,['selection','Does selecting rows change my data?','Grid selection, column visibility, widths, order and pinning are presentation state. Scientific edits remain separate reviewed actions.','Hide a wide comment column while inspecting identifiers, then show it again without changing its values.','Assuming hidden columns have been removed from an export or marked private.','Inspect']
 ,['tutorial-progress','Does completing a tutorial confirm my data?','Next records observation of a control. It does not run a validator, approve a repair or confirm a field. Missing targets prevent a clean lesson completion.','Finish the coordinate lesson while retaining Unknown datum until suitable evidence is available.','Treating a completed lesson or checklist as scientific certification.','Help']
 ,['ocr','Can I rely on extracted document text?','Extraction and optional OCR can lose layout, codes and characters. Preserve the original document, inspect the actual extraction status and compare passages before citing them.','An extracted count looks like 1 but the scanned page may contain a handwritten 7. Review the source image.','Confirming a scientific assertion from unchecked OCR or assuming every legacy document supports extraction.','Evidence']
 ,['dwcdp','What does DwC-DP preparation establish?','The preparation workspace reports its actual support level, dependencies and local checks. Preparation output and an independently validated target package are separate outcomes.','Resolve a missing relationship prerequisite, then inspect the resulting package and validator evidence.','Calling a prepared package conformant when independent validation has not succeeded.','DwC-DP preparation']
 ,['camtrap','How should I prepare camera-trap data?','Review deployment, media and observation grain, exact identifiers, effort and documented non-detections. Inspect the current standards capability entry before selecting a package target.','A deployment with no observation rows retains recorded effort; its meaning still depends on the protocol.','Treating missing observation rows as a proved zero count or claiming absent media files were preserved.','Standards Center']
 ,['keyboard','How do I use the data grid with a keyboard?','Arrow keys move between visible working cells; Home and End move within a row. Enter opens the existing reviewed edit dialog. Escape closes the context inspector and restores focus.','Focus a cell, move to the next field, then open a field header or row number to inspect context.','Assuming arrow navigation applies edits or that keyboard checks substitute for actual screen-reader testing.','Inspect']
].map(([id,title,summary,example,mistake,route])=>({id,title,summary,example,mistake,route,keywords:[id,route],related:route==='Inspect'?['layers','selection','differences']:route==='Export'?['share','restore','encrypted']:route==='Evidence'?['evidence','confirmation','ocr']:['unknown','evidence']}));
export const knowledgeCopy=Object.fromEntries(knowledge.flatMap(article=>['title','summary','example','mistake'].map(key=>['knowledge.'+article.id+'.'+key,article[key]])));
