import {t,localizeMessage} from './i18n.mjs';import {esc} from './components.mjs';
export function mountLargeRestore(host,{json,notice,open}){
 let token=null,report=null,busy=false,generation=0;const n=value=>new Intl.NumberFormat(document.documentElement.lang).format(value);
 host.innerHTML=`<details class="large-metadata-panel"><summary>${esc(t('v066.restoreTitle'))}</summary><p>${esc(t('v066.restoreSafety'))}</p><form data-large-restore-form><button type="button" class="drop-zone" data-restore-choose>${esc(t('v066.choosePackage'))}</button><input type="file" accept=".zip,.biorescue-encrypted,application/zip" data-restore-file hidden><p data-restore-file-name></p><label>${esc(t('workspace.unlockPassword'))}<input type="password" name="password" maxlength="1024" autocomplete="off"></label><p>${esc(t('workspace.cryptoSafety'))}</p><p>${esc(t('v066.restoreLimits'))}</p><button type="submit" class="button secondary" data-restore-check formnovalidate disabled>${esc(t('v066.verifyReplay'))}</button><p data-restore-progress role="status"></p><div data-restore-report></div><label>${esc(t('v066.reviewer'))}<input name="reviewer" maxlength="200" required></label><label>${esc(t('v06.reason'))}<textarea name="reason" maxlength="2000" required></textarea></label><button type="button" class="button primary" data-restore-publish disabled>${esc(t('v066.restoreSeparate'))}</button><button type="button" class="button secondary" data-restore-cancel>${esc(t('cancel'))}</button></form></details>`;
 const inventory=document.createElement('div');inventory.dataset.restoreInventory='';host.append(inventory);
 json('/api/large-restore-inventory').then(value=>{if(!host.isConnected)return;inventory.innerHTML=value.items.length?`<details><summary>${esc(t('workspace.interruptedPairs'))} (${value.items.length})</summary><p>${esc(t('workspace.interruptedPairsSafety'))}</p>${value.items.map(item=>`<p><bdi>${esc(item.directory)}</bdi> — ${esc(item.state)}; ${esc(t(item.originalRetained?'workspace.originalRetained':'workspace.originalUnavailable'))}</p>`).join('')}${value.truncated?`<p>${esc(t('workspace.inventoryBound'))}</p>`:''}</details>`:'';}).catch(()=>{if(host.isConnected)inventory.textContent=t('workspace.inventoryUnavailable');});
 const form=host.querySelector('form'),input=form.querySelector('[data-restore-file]'),choose=form.querySelector('[data-restore-choose]'),check=form.querySelector('[data-restore-check]'),publish=form.querySelector('[data-restore-publish]'),progress=form.querySelector('[data-restore-progress]'),result=form.querySelector('[data-restore-report]');let file=null;
 async function cancel(){form.elements.password.value='';generation++;report=null;publish.disabled=true;result.textContent='';const old=token;token=null;if(old)try{await json('/api/large-restore-cancel',{token:old});}catch{}busy=false;check.disabled=!file;}
 function failed(error){const code=error.message.match(/LARGE_RESTORE_[A-Z_]+/)?.[0];notice(code?t('v066.error.'+code):t('v066.verificationFailed',{detail:localizeMessage(error.message)}),true);}
 async function select(next){await cancel();file=next||null;form.querySelector('[data-restore-file-name]').textContent=file?.name||'';check.disabled=!file;progress.textContent='';}
 choose.onclick=()=>input.click();input.onchange=()=>select(input.files[0]);choose.ondragover=event=>{event.preventDefault();choose.classList.add('dragover');};choose.ondragleave=()=>choose.classList.remove('dragover');choose.ondrop=event=>{event.preventDefault();choose.classList.remove('dragover');select(event.dataTransfer.files[0]);};form.querySelector('[data-restore-cancel]').onclick=cancel;
 form.onsubmit=async event=>{event.preventDefault();if(!file||busy)return;const password=form.elements.password.value;await cancel();const selected=file,requestGeneration=generation;busy=true;check.disabled=true;let requestToken=null;try{
  const upload=await json('/api/large-restore-create',{size:selected.size});const uploadToken=upload.token;requestToken=uploadToken;if(requestGeneration!==generation||!host.isConnected){await json('/api/large-restore-cancel',{token:uploadToken});return;}token=uploadToken;
  for(let offset=0;offset<selected.size;offset+=1048576){if(!host.isConnected||requestGeneration!==generation)throw Error('LARGE_RESTORE_EXPIRED');const bytes=new Uint8Array(await selected.slice(offset,offset+1048576).arrayBuffer());let encoded='';for(let index=0;index<bytes.length;index+=32768)encoded+=String.fromCharCode(...bytes.subarray(index,index+32768));await json('/api/large-restore-chunk',{token:uploadToken,offset,data:btoa(encoded)});if(requestGeneration!==generation)throw Error('LARGE_RESTORE_EXPIRED');progress.textContent=t('v066.uploadProgress',{received:n(Math.min(offset+1048576,selected.size)),total:n(selected.size)});}
  progress.textContent=t('v066.replaying');const checked=await json('/api/large-restore-preview',{token:uploadToken,password});if(!host.isConnected||requestGeneration!==generation){await json('/api/large-restore-cancel',{token:uploadToken});return;}report=checked;result.innerHTML=`<h3>${esc(t('v066.verifiedReplay'))}</h3><p><bdi>${esc(checked.sourceName)}</bdi></p><dl class="translation-counts">${[['rows','v066.records'],['fields','v066.fields'],...(!checked.investigations?[['workingRevision','v066.workingRevision'],['metadataRevision','v066.metadataRevision']]:[]),['historyCells','v066.historyCells']].map(([key,label])=>`<div><dt>${esc(t(label))}</dt><dd>${esc(n(checked[key]))}</dd></div>`).join('')}</dl>${checked.investigations?`<p>${esc(t('workspace.pairedRestore'))}</p>${checked.investigations.map(i=>`<article><h4><bdi>${esc(i.sourceName)}</bdi></h4><p>${esc(t('workspace.pairedRevisions',{rows:n(i.rows),working:n(i.workingRevision),metadata:n(i.metadataRevision)}))}</p></article>`).join('')}`:''}<p>${esc(t('v066.previewSafety'))}</p>`;publish.disabled=false;progress.textContent=t('v066.ready');
 }catch(error){if(requestGeneration===generation){await cancel();failed(error);}else if(requestToken)try{await json('/api/large-restore-cancel',{token:requestToken});}catch{}}finally{if(requestGeneration===generation){busy=false;check.disabled=!file;}}};
 publish.onclick=async()=>{if(!report||busy||!form.reportValidity())return;busy=true;publish.disabled=true;try{const values=new FormData(form),restored=await json('/api/large-restore-publish',{token,digest:report.packageSha256,reviewer:values.get('reviewer'),reason:values.get('reason')});token=null;report=null;notice(t('v066.restored'));await open(restored.id);}catch(error){failed(error);publish.disabled=!report;}finally{busy=false;}};
}
