import {libraryV6,projectPreviewV6} from './workflow-experience.mjs';
import {uiLabel,localizeMessage} from './i18n.mjs';
import {htmlMessage as uiText,t as uiValue} from './i18n.mjs';
import {htmlMessage as tr} from './i18n.mjs';
import {esc,icon,ask} from './components.mjs';
import {formatDate,number} from './preferences.mjs';
import {newWindow} from './desktop-bridge.mjs';
export function setupManagement(ctx){
 const {api,getProject,closeProject,refresh,getList,setList,leave,open,notice,download}=ctx;
 let purgePending=false;
 let revision=0,filter='active',query='',sort='modified',view='list';
 async function load(){const r=await(await api('/api/project-hub')).json();revision=r.revision;purgePending=!!r.purgeCleanupPending;setList(r.projects);return r;}
 function sidebar(){const p=getProject(),list=getList().filter(x=>x.state==='active'&&x.kind==='research');const recent=list.filter(x=>x.id!==p?.id).sort((a,b)=>String(b.lastOpened||b.updatedAt).localeCompare(String(a.lastOpened||a.updatedAt))).slice(0,3);document.querySelector('#project-list').innerHTML=`${p?`<div class="side-label">${tr("ui.72ec80986277")}</div><button class="project-item selected" data-project="${esc(p.id)}" title="${esc(p.metadata.title.value)}" aria-current="page">${icon()}<span>${esc(p.metadata.title.value)}</span></button>`:''}${recent.length?`<div class="side-label">${tr("ui.d5d42c012481")}</div>`:''}${recent.map(x=>`<button class="project-item" data-project="${esc(x.id)}" title="${esc(x.title)}">${icon()}<span>${esc(x.title)}</span></button>`).join('')}<button class="text-button" data-section="Projects" data-i18n="ui.9547ad79f693">${tr("ui.9547ad79f693")}</button>`;}
 async function perform(item,op,extra={}){if(!await leave())return;const r=await ctx.withWrite(async()=>{const response=await(await api('/api/project-action',{id:item.id,action:op,managementRevision:revision,projectRevision:item.revision,...extra})).json();if(!response.project){revision=response.revision;setList(response.projects);if(getProject()?.id===item.id&&['archive','trash'].includes(op))await closeProject();}return response;});if(r.project){await load();await open(r.project.id);}else{revision=r.revision;purgePending=!!r.purgeCleanupPending;setList(r.projects);if(getProject()?.id===item.id){if(['archive','trash'].includes(op))await closeProject();else if(['rename','snapshot'].includes(op)){await open(item.id);return r;}}hub();sidebar();}return r;}
 async function menu(item){
  const archived=item.state==='archived',trashed=item.state==='trash';
  const actions=trashed?[['restore','Restore'],['delete','Permanently delete']]:archived?[['restore','Restore to active'],['duplicate','Create a copy'],['backup','Export portable backup'],['trash','Move to Trash']]:[['open','Open'],['details','Project details'],['rename','Rename'],['pin',item.pinned?'Unpin':'Pin'],['duplicate','Duplicate / fork'],['backup','Export portable backup'],['snapshot','Create snapshot'],['archive','Archive'],['trash','Move to Trash']];
  if(window.__TAURI_INTERNALS__ && !trashed)actions.splice(1,0,['new-window',uiValue('v07.openNew')]);
  const choice=await ask({title:item.title,body:formatDate(item.updatedAt),choices:[...actions.map(([value,label])=>({value,label:uiLabel(label),danger:value==='delete'})),{value:null,label:uiValue("cancel")}]});if(!choice)return;
  const op=choice.choice;
  if(op==='open')return open(item.id);
  if(op==='new-window')return newWindow(item.id);
  if(op==='details'){await ask({title:item.title,body:uiValue("ui.358fa04fe8b7",{p0:(item.id),p1:(formatDate(item.createdAt)),p2:(formatDate(item.updatedAt)),p3:(item.lastOpened?formatDate(item.lastOpened):uiLabel('Not recorded')),p4:(item.lastAutosave?formatDate(item.lastAutosave):uiLabel('Not recorded')),p5:(item.lastBackupRequested?formatDate(item.lastBackupRequested):uiLabel('Not recorded')),p6:(item.resources||0),p7:(item.tables||0),p8:(item.bytes||0),p9:(item.unknowns||0),p10:(item.conflicts||0),p11:(item.metadataUnknowns||0),p12:(item.metadataConflicts||0),p13:(item.validationStatus||uiLabel('Not recorded')),p14:(Object.entries(item.standards||{}).filter(([,v])=>v).map(([k])=>k).join(', ')||uiLabel('None selected')),p15:(item.description||uiLabel('Not recorded'))}),choices:[{value:'close',label:uiValue("ui.7d9eb7acb13e")}]});return;}
  if(op==='rename'){const r=await ask({title:uiValue("ui.2a0478eef536"),body:uiValue("ui.10b68e925985"),fields:[{name:'name',label:uiValue("ui.25498193b898"),value:item.title,required:true}],choices:[{value:'rename',label:uiValue("ui.b7297226fd1f"),submit:true},{value:null,label:uiValue("cancel")}]});if(r){if(getList().some(x=>x.id!==item.id&&x.title===r.name))notice(uiValue("ui.901e63b5a614"));await perform(item,op,{name:r.name});}return;}
  if(op==='snapshot'){const r=await ask({title:uiValue("ui.86fba2d2cdb3"),fields:[{name:'name',label:uiValue("ui.409f7080f20e"),value:'Project checkpoint',required:true}],choices:[{value:'save',label:uiValue("ui.86fba2d2cdb3"),submit:true},{value:null,label:uiValue("cancel")}]});if(r)await perform(item,op,{name:r.name});return;}
  if(op==='backup'){const p=await(await api('/api/project?id='+encodeURIComponent(item.id))).json();download(JSON.stringify(p,null,2),`${item.title.replace(/[^\p{L}\p{N}_-]/gu,'-').slice(0,80)}-v0.5.0.biorescue.json`);await load();await api('/api/project-action',{id:item.id,action:'backup-request',managementRevision:revision});await load();notice(uiValue("ui.e14a0a6d4cad"));return;}
  if(op==='delete'){
   const preview=await(await api('/api/delete-preview?id='+encodeURIComponent(item.id))).json();const yes=await ask({title:uiValue("ui.083d86a5705d"),body:uiValue("ui.eff81d35b4f5",{p0:(preview.title),p1:(preview.id),p2:(preview.files.map(file=>uiLabel(file)).join(', ')),p3:(preview.originals),p4:(preview.backupRecorded?'A backup request is recorded; verify your copy first.':'No portable backup request is recorded.')}),fields:[{name:'confirm',label:uiValue("ui.adce66465cfe"),required:true,value:''}],choices:[{value:'delete',label:uiValue("ui.9003e1b7e7c2"),submit:true,danger:true},{value:null,label:uiValue("cancel")}]});if(yes){const r=await(await api('/api/project-delete',{id:item.id,managementRevision:preview.managementRevision,projectRevision:preview.projectRevision,confirm:yes.confirm})).json();revision=r.revision;purgePending=!!r.purgeCleanupPending;setList(r.projects);hub();sidebar();}return;
  }
  await perform(item,op);
  if(op==='trash'){const note=document.querySelector('#notice');note.textContent=uiValue("ui.4b5429f2f62a");const undo=document.createElement('button');undo.className='text-button';undo.textContent=uiValue("ui.a8283ade3185");undo.onclick=()=>perform(item,'restore').catch(e=>notice(e.message,true));note.append(undo);note.className='visible';}
 }
 function hub(){
  document.title='Projects — Biodiversity Data Rescue Workbench';let list=getList();const count=state=>list.filter(x=>x.state===state&&x.kind==='research').length;
  const terms=query.toLocaleLowerCase();let shown=list.filter(x=>filter==='cleanup'?(/^v0\.\d+ browser verification|verification|demonstration|guided fictional|Untitled rescue$/i.test(x.title)||(!x.tables&&!x.resources)):filter==='attention'?x.state==='active'&&x.kind==='research'&&(x.unknowns||x.conflicts||x.error):filter==='recent'?x.state==='active'&&x.kind==='research':filter==='pinned'?x.pinned&&x.state==='active'&&x.kind==='research':filter==='examples'?x.kind==='example':filter==='tutorials'?x.kind==='tutorial':x.state===filter&&x.kind==='research').filter(x=>[x.title,x.description,...(x.tags||[]),...(x.resourceNames||[]),...Object.keys(x.standards||{})].join(' ').toLocaleLowerCase().includes(terms));
  shown.sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):sort==='created'?String(b.createdAt).localeCompare(String(a.createdAt)):sort==='opened'?String(b.lastOpened||'').localeCompare(String(a.lastOpened||'')):Number(b.pinned)-Number(a.pinned)||String(filter==='recent'?b.lastOpened||b.updatedAt:b.updatedAt).localeCompare(String(filter==='recent'?a.lastOpened||a.updatedAt:a.updatedAt)));
  document.querySelector('#main').innerHTML=libraryV6(shown,{filter,query,sort,view,count,purgePending});

  document.querySelector('#empty-trash')?.addEventListener('click',async()=>{try{const preview=await(await api('/api/trash-preview')).json();const decision=await ask({title:uiValue("ui.7dfa88334d87"),body:uiValue("ui.9c7012d5f54f",{p0:(preview.projects.map(x=>x.title+' · '+x.id+' · '+uiLabel('Committed revision')+' '+x.projectRevision+' · '+x.files.map(file=>uiLabel(file)).join(', ')).join('\n')),p1:(localizeMessage(preview.originals))}),fields:[{name:'confirm',label:uiValue("ui.0a903c3804f4",{p0:(preview.confirmation)}),required:true}],choices:[{value:'delete',label:uiValue("ui.efd5bd40e5ec"),submit:true,danger:true},{value:null,label:uiValue("cancel")}]});if(!decision)return;const result=await ctx.withWrite(async()=>(await api('/api/empty-trash',{managementRevision:preview.managementRevision,confirm:decision.confirm,projects:preview.projects.map(x=>({id:x.id,projectRevision:x.projectRevision}))})).json());revision=result.revision;purgePending=!!result.purgeCleanupPending;setList(result.projects);hub();sidebar();notice(uiValue(purgePending?"ui.351c11acdb02":"ui.ab7849f196ed"),purgePending);}catch(error){notice(error.message,true);}});
  for(const b of document.querySelectorAll('[data-filter]'))b.onclick=()=>{filter=b.dataset.filter;hub();};
  document.querySelector('#project-search').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;hub();const node=document.querySelector('#project-search');node.focus();node.setSelectionRange(pos,pos);};
  document.querySelector('#project-sort').onchange=e=>{sort=e.target.value;hub();};document.querySelector('#project-view').onclick=()=>{view=view==='cards'?'list':'cards';hub();};
  for(const b of document.querySelectorAll('[data-menu]'))b.onclick=()=>menu(getList().find(x=>x.id===b.dataset.menu)).catch(e=>notice(e.message,true));
  for(const b of document.querySelectorAll('[data-hub-open]'))b.onclick=()=>{const item=getList().find(x=>x.id===b.dataset.hubOpen);(item.state==='active'?open(item.id):menu(item)).catch(e=>notice(e.message,true));};
  for(const button of document.querySelectorAll('[data-preview-project]'))button.onclick=()=>{const item=getList().find(item=>item.id===button.dataset.previewProject);document.querySelector('.hub-preview')?.remove();document.querySelector('#main').insertAdjacentHTML('beforeend',projectPreviewV6(item));const preview=document.querySelector('.hub-preview');preview.querySelector('[data-close-preview]').onclick=()=>{preview.remove();button.focus();};preview.querySelector('[data-preview-open]').onclick=()=>open(item.id);preview.querySelector('[data-preview-more]').onclick=()=>menu(item);preview.querySelector('[data-preview-window]')?.addEventListener('click',()=>newWindow(item.id).catch(error=>notice(String(error),true)));preview.querySelector('[data-close-preview]').focus();};
  document.querySelector('#trash-selection')?.addEventListener('click',async()=>{const ids=[...document.querySelectorAll('[data-cleanup]:checked')].map(x=>x.dataset.cleanup);if(!ids.length)return;const yes=await ask({title:uiValue("ui.5630a3afc375"),body:uiValue("ui.baa6000cce58",{p0:(ids.length)}),choices:[{value:'trash',label:uiValue("ui.9adcdf33dce1")},{value:null,label:uiValue("cancel")}]});if(!yes)return;for(const id of ids)await perform(getList().find(x=>x.id===id),'trash');});
 }
 return {load,sidebar,hub,menu,perform};
}
