import {t as structuralText,htmlMessage as structuralHtml} from './i18n.mjs';
import {translateTable,evidenceGuard} from './translation-core.mjs';
import {profile as legacyProfile, issues as legacyIssues, validateProject as validateV1, TERMS} from './model.mjs';
export const APP_VERSION = '0.7.0';
export const STATUSES = ['Confirmed', 'Inferred', 'Unknown', 'Conflicting', 'Not Applicable'];
export const META_FIELDS = [['title','Title'],['description','Abstract / description'],['purpose','Purpose'],['creator','Creators'],['contributors','Contributors'],['contact','Contacts'],['organizations','Organizations'],['citation','Citation'],['publicationDate','Publication / release date'],['license','License / rights'],['funding','Funding & acknowledgements'],['methods','Methods'],['samplingProtocol','Sampling protocol'],['studyDesign','Study design'],['temporalCoverage','Temporal coverage'],['spatialCoverage','Geographic coverage'],['taxonomicCoverage','Taxonomic coverage'],['keywords','Keywords'],['originalSoftware','Original software / system'],['publications','Related publications / DOI / URL'],['limitations','Known limitations'],['provenance','Provenance'],['sensitivity','Access restrictions'],['datum','Coordinate datum / reference system'],['coordinateUncertainty','Coordinate uncertainty']];
export const interpretation = (value = '', status = 'Unknown') => ({value, status, confidence:'', rationale:'', evidence:[], reviewerNotes:''});
export const field = (name, originalName = name, sourceIndex = null) => ({sourceIndex, originalName, workingName:name, description:'', dataType:'string', unit:'', allowedValues:[], missingToken:'', term:'', status:'Unknown', confidence:'', rationale:'', evidence:[], reviewerNotes:'', sensitive:false, constraints:{}});
export function newProject(title='Untitled rescue') {
  const at = new Date().toISOString();
  const p = {version:2, projectSchemaVersion:3, migrationHistory:[], evidenceAssertions:[], recovery:{}, appVersion:APP_VERSION, id:crypto.randomUUID(), revision:0, createdAt:at, updatedAt:at, metadata:Object.fromEntries(META_FIELDS.map(([k])=>[k,interpretation()])), resources:[], tables:[], relationships:[], audit:[], undoStack:[], redoStack:[], profiles:{frictionless:'1', darwinCoreGuide:'2026-05-26', roCrate:'1.3', eml:'2.2.0'}, mode:'beginner'};
  p.metadata.title = interpretation(title, 'Confirmed'); return p;
}
export function migrateProject(old) {
  if (old.version === 2) return validateProject(old);
  validateV1(old);
  const p = newProject(old.metadata.title || old.source.name); p.id = old.id; p.createdAt = old.createdAt;
  for (const [k,v] of Object.entries(old.metadata)) p.metadata[k] = {...interpretation(v, v ? 'Inferred' : 'Unknown'), rationale:v ? 'Migrated from v1: prior interpretation status and evidence were not recorded. Review before confirming.' : ''};
  const rid = crypto.randomUUID(); p.resources.push({...old.source, id:rid, importedAt:old.createdAt, format:old.parsing.format, archaeology:{notes:old.notes}, role:'data'});
  const t = {id:crypto.randomUUID(), resourceId:rid, name:old.source.name.replace(/\.[^.]+$/,''), sheet:old.parsing.sheet||null, headers:[...old.headers], rows:structuredClone(old.rows), originalHeaders:[...old.originalHeaders], rowWidths:[...old.rowWidths], columns:old.headers.map((h,i)=>({...field(h,old.originalHeaders[i]||h,i),...old.columns[i], status:old.columns[i].description ? 'Inferred':'Unknown', rationale:'Migrated from v1; interpretation status requires review.'})), parsing:old.parsing, notes:old.notes, primaryKey:[], originalTable:{headers:old.headers,rows:old.rows}, rowOrigins:old.rows.map((_,i)=>i),baselineNote:'Migrated v1 working table is the comparison/recipe baseline; original file bytes and legacy repair history are preserved separately.',legacyAudit:old.audit};
  p.tables.push(t); p.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),action:'migrate v1 backup',reason:'Preserved v1 working table, metadata and full legacy history; prior assertions marked Inferred.',applicationVersion:APP_VERSION}); return p;
}
const state = p => structuredClone({metadata:p.metadata,tables:p.tables,relationships:p.relationships,profiles:p.profiles});
const same = (a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function change(p, action, reason, mutate, operation=null) {
  if (!reason?.trim()) throw new Error(structuralText('v07.migrated.27bc4ebf50b2'));
  const next=structuredClone(p), before=state(p); mutate(next); const after=state(next);
  if(same(before,after)) throw new Error(structuralText('v07.migrated.c53de73b8453'));
  const event={id:crypto.randomUUID(),at:new Date().toISOString(),action,reason:reason.trim(),applicationVersion:APP_VERSION,transformationVersion:1,before,after,operation};
  next.audit.push(event);next.undoStack.push(event.id);next.redoStack=[];next.updatedAt=event.at;return next;
}
export function addImport(p, imported) {
  const next=structuredClone(p), rid=crypto.randomUUID();
  next.resources.push({...imported.resource,id:rid});
  for(const table of imported.tables) next.tables.push({...table,id:crypto.randomUUID(),resourceId:rid,rowOrigins:table.rows.map((_,i)=>i),columns:table.headers.map((h,i)=>field(h,table.originalHeaders[i]||h,i)),primaryKey:[],originalTable:{headers:structuredClone(table.headers),rows:structuredClone(table.rows)}});
  next.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),action:'preserve source',reason:'Original bytes archived; tables are independent working copies. Import structure and unsupported features remain recorded.',resourceId:rid,sourceHash:imported.resource.sha256,applicationVersion:APP_VERSION});
  next.updatedAt=new Date().toISOString();next.redoStack=[];return next;
}
export function undoRedo(p, redo=false) {
  const next=structuredClone(p), from=redo?next.redoStack:next.undoStack,to=redo?next.undoStack:next.redoStack;
  const id=from.pop();if(!id)throw new Error(redo?'Nothing to redo.':'Nothing to undo.');
  const event=next.audit.find(e=>e.id===id);if(!event?.before||!event.after)throw new Error(structuralText('v07.migrated.3a1de24a7cae'));
  const restored=structuredClone(redo?event.after:event.before);
  // Sources added later must survive undo of earlier edits; table extraction is an import boundary.
  for(const t of next.tables)if(!restored.tables.some(r=>r.id===t.id))restored.tables.push(t);
  Object.assign(next,restored);to.push(id);const at=new Date().toISOString();next.updatedAt=at;
  next.audit.push({id:crypto.randomUUID(),at,action:redo?'redo':'undo',reason:`${redo?'Reapplied':'Reverted'} ${event.action}`,target:id,applicationVersion:APP_VERSION});return next;
}
export function profiles(table) {
  const base=legacyProfile(table);
  return base.map((p,c)=>{
    const freq=new Map();for(const row of table.rows){const v=row[c];freq.set(v,(freq.get(v)||0)+1);}
    const numbers=table.rows.map(r=>r[c]).filter(v=>v.trim()&&['integer','number'].includes(p.type)&&Number.isFinite(Number(v))).map(Number);
    let min=null,max=null;for(const n of numbers){if(min===null||n<min)min=n;if(max===null||n>max)max=n;}
    return {...p,nullPercent:table.rows.length?p.missing/table.rows.length*100:0,min,max,common:[...freq].sort((a,b)=>b[1]-a[1]).slice(0,8),candidateIdentifier:table.rows.length>0&&p.missing===0&&p.unique===table.rows.length};
  });
}
const normalName = h=>h.replace(/[^a-z0-9]/gi,'').toLowerCase();
const ROLES=[['scientificName',/scientificname|taxonname|species|binomial/,'Which organism was identified?'],['vernacularName',/commonname|vernacular/,'What common name was recorded?'],['taxonID',/taxonid|taxoncode/,'Which taxon identifier was recorded?'],['decimalLatitude',/latitude|^lat$/,'Where was it observed: latitude?'],['decimalLongitude',/longitude|^lon$|^lng$/,'Where was it observed: longitude?'],['eventDate',/date|timestamp|^dt$/,'When was the observation or survey?'],['recordedBy',/observer|recorder|recordedby/,'Who recorded it?'],['occurrenceID',/occurrenceid|recordid/,'Which observation does this record identify?'],['eventID',/eventid|surveyid/,'Which survey or sampling event?'],['locality',/locality|site|locationname/,'What place or site label was recorded?'],['individualCount',/count|abundance|^n$/,'How many individuals were reported?'],['samplingEffort',/effort|duration|minutes/,'How much survey effort was recorded?']];
export function suggestions(table) {
  return table.headers.flatMap((h,c)=>ROLES.filter(([,pattern])=>pattern.test(normalName(h))).map(([term,,question])=>({column:c,term,iri:`http://rs.tdwg.org/dwc/terms/${term}`,question,confidence:normalName(h)===normalName(term)?'High':'Medium',status:'Inferred',rationale:'Column-name heuristic only; no meaning has been assigned.'})));
}
export const ALL_TERMS=[...new Set([...TERMS,...ROLES.map(r=>r[0]),'geodeticDatum','coordinateUncertaintyInMeters','verbatimLatitude','verbatimLongitude','dataGeneralizations','informationWithheld'])];
export function coordinateColumns(table){const pick=term=>table.columns.findIndex((c,i)=>c.term===term||(!c.term&&ROLES.find(r=>r[0]===term)[1].test(normalName(table.headers[i]))));return [pick('decimalLatitude'),pick('decimalLongitude')];}
export function tableIssues(table,p) {
  const legacy=legacyIssues({...table,metadata:Object.fromEntries(Object.entries(p.metadata).map(([k,v])=>[k,v.value]))}).filter(i=>!i.title.startsWith('Missing '));
  const result=legacy.map(i=>({...i,tableId:table.id,layer:i.severity==='context'?'metadata':'scientific',severity:i.severity==='review'?'Warning':'Information'}));
  const add=(title,detail,rows=[],column=null,severity='Warning',layer='scientific')=>result.push({title,detail,rows,column,severity,layer,tableId:table.id});
  table.headers.forEach((h,c)=>{
    const rows=predicate=>table.rows.flatMap((r,i)=>predicate(r[c])?[i]:[]);
    const sentinels=rows(v=>/^(NA|N\/A|NULL|NONE|\.|-|\?|[-]999(?:9)?|9999)$/i.test(v.trim()));
    if(sentinels.length)add(`Suspicious sentinels in ${h}`,'Possible missing markers; literal values remain unchanged until a documented convention is confirmed.',sentinels,c);
    const partial=rows(v=>/^\d{4}$|^\d{4}-\d{2}$|^\d{1,2}\/\d{4}$/.test(v)&&/date|year|^dt$/i.test(h));
    if(partial.length)add(`Partial dates in ${h}`,'Year or month precision is preserved. Do not invent a day.',partial,c,'Information');
    const serials=rows(v=>/^\d+(\.\d+)?$/.test(v)&&Number(v)>20000&&Number(v)<80000&&/date|^dt$/i.test(h));
    if(serials.length)add(`Possible Excel serial dates in ${h}`,'Confirm workbook date system (1900 or 1904) and interpretation before converting.',serials,c);
    const iso=rows(v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!validISO(v));if(iso.length)add(`Impossible calendar dates in ${h}`,'Date-shaped text contains an invalid calendar day.',iso,c);
    const dictionary=table.columns[c];
    if(dictionary.status==='Conflicting')add(`Conflicting interpretation: ${h}`,dictionary.rationale||'Document competing explanations and evidence.',[],c,'Warning','metadata');
    if(dictionary.status==='Inferred')add(`Inferred interpretation: ${h}`,'This definition or mapping is not confirmed by evidence.',[],c,'Information','metadata');
    if(dictionary.dataType==='integer'||dictionary.dataType==='number'){const invalid=rows(v=>v!==''&&!validType(v,dictionary.dataType));if(invalid.length)add(`Declared type mismatch: ${h}`,`Values do not satisfy ${dictionary.dataType}; no coercion was performed.`,invalid,c,'Error','schema');}
    if(dictionary.allowedValues.length){const invalid=rows(v=>v!==''&&!dictionary.allowedValues.includes(v));if(invalid.length)add(`Unexpected category: ${h}`,'Values fall outside the user-declared vocabulary.',invalid,c,'Warning','schema');}
  });
  const [lat,lon]=coordinateColumns(table);
  if(lat>=0&&lon>=0){
    const zero=[],swap=[],numeric=[];table.rows.forEach((r,i)=>{if(!r[lat].trim()||!r[lon].trim())return;const a=Number(r[lat]),b=Number(r[lon]);if(!Number.isFinite(a)||!Number.isFinite(b))return;if(a===0&&b===0)zero.push(i);if(Math.abs(a)>90&&Math.abs(a)<=180&&Math.abs(b)<=90)swap.push(i);if(Math.abs(a)<=90&&Math.abs(b)<=180)numeric.push({i,a,b});});
    if(zero.length)add('Coordinates at 0,0','May be real or a placeholder. Review source evidence.',zero);
    if(swap.length)add('Coordinates may be swapped','Latitude exceeds 90 while longitude could be a latitude. No axes were swapped.',swap);
    if(p.metadata.datum.status!=='Confirmed'||!p.metadata.datum.value)add('Coordinate datum not confirmed','Coordinate previews use reported angular values only. No datum has been assumed.');
    if(numeric.length>=5){const sortedA=numeric.map(n=>n.a).sort((a,b)=>a-b),sortedB=numeric.map(n=>n.b).sort((a,b)=>a-b);const medianA=sortedA[Math.floor(sortedA.length/2)],medianB=sortedB[Math.floor(sortedB.length/2)];const far=numeric.filter(n=>Math.abs(n.a-medianA)>10||Math.abs(n.b-medianB)>10).map(n=>n.i);if(far.length)add('Geographic outlier candidates','More than 10 angular degrees from the dataset median; a heuristic, not a scientific rejection.',far);}
  }
  return result;
}
export function keyCandidates(p){return p.tables.flatMap(t=>profiles(t).filter(c=>c.candidateIdentifier).map(c=>({tableId:t.id,column:t.headers.indexOf(c.name),name:c.name,confidence:/id|key|code/i.test(c.name)?'High':'Low',rationale:'Unique and nonblank in the current data; uniqueness alone does not establish identity.'})));}
export function relationshipCandidates(p){const out=[];for(const parent of keyCandidates(p)){const pt=p.tables.find(t=>t.id===parent.tableId),values=new Set(pt.rows.map(r=>r[parent.column]));for(const t of p.tables){if(t.id===pt.id)continue;for(let c=0;c<t.headers.length;c++){const v=t.rows.map(r=>r[c]).filter(v=>v!=='');const matches=v.filter(v=>values.has(v)).length;if(v.length&&matches/v.length>=.5&&normalName(t.headers[c])===normalName(parent.name))out.push({fromTable:t.id,fromColumn:c,toTable:pt.id,toColumn:parent.column,matched:matches,total:v.length,confidence:'Medium',rationale:'Matching names and overlapping values only. Confirm the real relationship.'});}}}return out;}
export function relationshipIssues(p){const out=[];const add=(title,detail,tableId,rows,severity='Error')=>out.push({title,detail,tableId,rows,severity,layer:'relationships',column:null});
 for(const t of p.tables){if(!t.primaryKey.length)continue;const cols=t.primaryKey.map(h=>t.headers.indexOf(h));if(cols.includes(-1)){add('Primary key field missing','A key references a renamed or absent field.',t.id,[]);continue;}const seen=new Set(),duplicate=[],blank=[];t.rows.forEach((r,i)=>{const values=cols.map(c=>r[c]);if(values.some(v=>v===''))blank.push(i);const k=JSON.stringify(values);if(seen.has(k))duplicate.push(i);seen.add(k);});if(duplicate.length)add('Duplicate primary keys','Declared identifiers repeat. Records remain separate.',t.id,duplicate);if(blank.length)add('Missing primary keys','Declared identifiers contain blanks.',t.id,blank);}
 for(const rel of p.relationships){const child=p.tables.find(t=>t.id===rel.fromTable),parent=p.tables.find(t=>t.id===rel.toTable);if(!child||!parent){add('Relationship table missing','Review the relationship definition.',rel.fromTable,[]);continue;}const c=child.headers.indexOf(rel.fromField),d=parent.headers.indexOf(rel.toField);if(c<0||d<0){add('Relationship field missing','A referenced field was renamed or is absent.',child.id,[]);continue;}const parentValues=new Set(parent.rows.map(r=>r[d])),referenced=new Set(child.rows.map(r=>r[c]).filter(Boolean));const missing=child.rows.flatMap((r,i)=>r[c]&&!parentValues.has(r[c])?[i]:[]),orphans=parent.rows.flatMap((r,i)=>!referenced.has(r[d])?[i]:[]);if(missing.length)add('Missing referenced records',`${rel.fromField} → ${parent.name}.${rel.toField}: ${missing.length} child records have no matching parent.`,child.id,missing);if(orphans.length)add('Unreferenced parent records',`${orphans.length} records in ${parent.name} are not referenced by ${child.name}. May be legitimate unsampled events.`,parent.id,orphans,'Information');const duplicates=parent.rows.length-new Set(parent.rows.map(r=>r[d])).size;if(duplicates)add('Relationship target is not unique','A foreign key cannot unambiguously identify the parent record.',parent.id,[]);}
 return out;
}
export function validation(p){const out=p.tables.flatMap(t=>tableIssues(t,p));out.push(...relationshipIssues(p));for(const [k,v]of Object.entries(p.metadata)){if(!v.value&&v.status!=='Not Applicable')out.push({layer:'metadata',severity:'Information',title:`Unknown ${META_FIELDS.find(m=>m[0]===k)?.[1]||k}`,detail:'No defensible meaning has been recovered.',rows:[]});if(v.status==='Conflicting')out.push({layer:'metadata',severity:'Warning',title:`Conflicting ${k}`,detail:v.rationale,rows:[]});}for(const t of p.tables)for(const c of t.columns)if(c.term&&c.status!=='Confirmed')out.push({layer:'standards',severity:'Warning',title:`Unconfirmed mapping: ${t.name}.${c.workingName}`,detail:`${c.term} is ${c.status}; not asserted as a confirmed standard mapping.`,rows:[]});return out;}
export function validISO(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const [y,m,d]=v.split('-').map(Number);if(m<1||m>12||d<1)return false;return d<=new Date(Date.UTC(y,m,0)).getUTCDate();}
function validType(v,type){if(type==='integer')return /^[+-]?\d+$/.test(v)&&Number.isSafeInteger(Number(v));if(type==='number')return /^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(v)&&Number.isFinite(Number(v));if(type==='boolean')return /^(true|false)$/i.test(v);if(type==='date')return validISO(v);return true;}
export function parseDate(v,format){if(!['ISO','year','month','excel1900','excel1904','DMY','MDY'].includes(format))throw new Error(structuralText('v07.migrated.2717288d5601'));if(v==='')return v;if(format==='ISO'){if(!validISO(v))throw new Error(`Not a valid complete ISO date: ${v}`);return v;}if(format==='year'||format==='month'){if(format==='year'&&/^\d{4}$/.test(v))return v;if(format==='month'&&/^\d{4}-\d{2}$/.test(v)&&+v.slice(5)>=1&&+v.slice(5)<=12)return v;throw new Error(structuralText('v07.migrated.70506097e926'));}if(format==='excel1900'||format==='excel1904'){if(!/^\d+$/.test(v))throw new Error(structuralText('v07.migrated.74b13b76efd8'));const n=Number(v);if(format==='excel1900'&&n===60)throw new Error(structuralText('v07.migrated.63fcbeddc14d'));if(n<0||n>2958465)throw new Error(structuralText('v07.migrated.0a153b192306'));const base=format==='excel1904'?Date.UTC(1904,0,1):Date.UTC(1899,11,31);return new Date(base+(n-(format==='excel1900'&&n>60?1:0))*86400000).toISOString().slice(0,10);}const m=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(!m)throw new Error(`Cannot parse with confirmed ${format}: ${v}`);const day=format==='DMY'?m[1]:m[2],month=format==='DMY'?m[2]:m[1];const iso=`${m[3]}-${month.padStart(2,'0')}-${day.padStart(2,'0')}`;if(!validISO(iso))throw new Error(`Impossible date: ${v}`);return iso;}
export function parseCoordinate(value,axis){if(!value.trim())return '';const m=value.trim().match(/^([+-]?\d+(?:\.\d+)?)\s*(?:°|d|\s)\s*(\d+(?:\.\d+)?)?\s*(?:['′m]|\s)?\s*(\d+(?:\.\d+)?)?\s*(?:["″s])?\s*([NSEW])?$/i);if(!m)throw new Error(`Unsupported degrees/minutes/seconds: ${value}`);const deg=Number(m[1]),minutes=Number(m[2]||0),seconds=Number(m[3]||0),dir=(m[4]||'').toUpperCase();if(minutes>=60||seconds>=60)throw new Error(structuralText('v07.migrated.673043c7d27f'));if(dir&&((axis==='latitude'&&!/[NS]/.test(dir))||(axis==='longitude'&&!/[EW]/.test(dir))))throw new Error(structuralText('v07.migrated.d5d308ff552d'));if(deg<0&&/[NE]/.test(dir))throw new Error(structuralText('v07.migrated.85eba40e97f7'));const sign=/[SW]/.test(dir)||deg<0?-1:1;const n=sign*(Math.abs(deg)+minutes/60+seconds/3600);if(Math.abs(n)>(axis==='latitude'?90:180))throw new Error(structuralText('v07.migrated.9c9546f66f57'));return String(Number(n.toFixed(8)));}
export function transform(table,spec){
  if(['reviewed translation','review field meaning'].includes(spec.op))return translateTable(table,spec);
  const next=structuredClone(table),c=Number(spec.column),op=spec.op;let affected=0;const examples=[];
  if(!Number.isInteger(c)||c<0||c>=table.headers.length)throw new Error(structuralText('v07.migrated.853406772426'));
  if(['parse dates','convert coordinates','convert units','cast type','normalize missing','map codes'].includes(op)&&!spec.confirmed)throw new Error(structuralText('v07.migrated.351c375c757b'));
  const update=(r,i,after)=>{const before=r[c];if(before!==after){affected++;if(examples.length<5)examples.push({row:i+1,before,after});r[c]=after;}};
  if(op==='replace cell'){if(!Number.isInteger(spec.row)||spec.row<0||spec.row>=next.rows.length)throw new Error(structuralText('v07.migrated.65b71322d15e'));update(next.rows[spec.row],spec.row,spec.value);}
  else if(op==='reorder column'){const to=Number(spec.value)-1;if(!Number.isInteger(to)||to<0||to>=next.headers.length)throw new Error(structuralText('v07.migrated.07fb005f30cd'));const move=a=>{const [v]=a.splice(c,1);a.splice(to,0,v);};move(next.headers);move(next.columns);next.rows.forEach(move);affected=next.rows.length;examples.push({before:`column ${c+1}`,after:`column ${to+1}`});}
  else if(op==='rename column'){const name=spec.value.trim();if(!name||next.headers.some((h,i)=>h===name&&i!==c))throw new Error(structuralText('v07.migrated.814fbebfd438'));next.headers[c]=name;next.columns[c].workingName=name;for(const definition of next.columns)if(definition.derivation){definition.derivation.sourceFields=definition.derivation.sourceFields.map(field=>field===table.headers[c]?name:field);if(definition.derivation.outcomeField===table.headers[c])definition.derivation.outcomeField=name;}next.primaryKey=next.primaryKey.map(h=>h===table.headers[c]?name:h);affected=1;examples.push({before:table.headers[c],after:name});}
  else if(op==='remove duplicate rows'){const keys=spec.keys?.length?spec.keys:[...table.headers];const indexes=keys.map(k=>table.headers.indexOf(k));if(indexes.includes(-1))throw new Error(structuralText('v07.migrated.22440d5a400c'));const seen=new Set();const origins=[];next.rows=next.rows.filter((r,i)=>{const k=JSON.stringify(indexes.map(j=>r[j]));if(seen.has(k)){affected++;if(examples.length<5)examples.push({row:i+1,before:JSON.stringify(r),after:'row removed (keep first)'});return false;}seen.add(k);origins.push(next.rowOrigins?.[i]??i);return true;});next.rowOrigins=origins;}
  else if(['derive field','parse dates','convert coordinates','convert units','split column','merge columns'].includes(op)){
    const name=spec.name?.trim();if(!name||next.headers.includes(name))throw new Error(structuralText('v07.migrated.211118a4fd74'));
    let derived;
    if(op==='derive field')derived=next.rows.map(r=>r[c]);
    if(op==='parse dates')derived=next.rows.map(r=>parseDate(r[c],spec.format));
    if(op==='convert coordinates')derived=next.rows.map(r=>parseCoordinate(r[c],spec.axis));
    if(op==='convert units'){const factor=Number(spec.factor),offset=Number(spec.offset||0);if(!Number.isFinite(factor)||!Number.isFinite(offset)||!String(spec.factor).trim())throw new Error(structuralText('v07.migrated.68a23fefee64'));derived=next.rows.map(r=>{if(!r[c])return '';if(!validType(r[c],'number'))throw new Error(`Non-numeric value: ${r[c]}`);const n=Number(r[c])*factor+offset;if(!Number.isFinite(n))throw new Error(structuralText('v07.migrated.7ed34ba1604b'));return String(n);});}
    if(op==='split column'){if(!spec.separator)throw new Error(structuralText('v07.migrated.e1a3d68f0344'));const part=Number(spec.part);if(!Number.isInteger(part)||part<1)throw new Error(structuralText('v07.migrated.61595d74b559'));derived=next.rows.map(r=>r[c].split(spec.separator)[part-1]??'');}
    if(op==='merge columns'){const other=next.headers.indexOf(spec.other);if(other<0)throw new Error(structuralText('v07.migrated.a873fd2437ce'));derived=next.rows.map(r=>[r[c],r[other]].join(spec.separator??' '));}
    next.headers.push(name);const col=field(name);col.description=`Derived from ${table.headers[c]} by ${op}; source field retained.`;col.status=spec.confirmed?'Confirmed':'Inferred';col.rationale=spec.reason||'';col.unit=spec.unit||'';const sourceFields=[table.headers[c],...(op==='merge columns'?[spec.other]:[])];col.derivation={operation:op,sourceFields};col.sensitive=sourceFields.some(h=>{const index=table.headers.indexOf(h);return table.columns[index]?.sensitive||/latitude|longitude|coordinate|easting|northing|geometry|footprint|geohash|(?:^|[^a-z])(?:lat|lon|lng)(?:$|[^a-z])/i.test(h)||['decimalLatitude','decimalLongitude','verbatimLatitude','verbatimLongitude'].includes(table.columns[index]?.term);});next.columns.push(col);next.rows.forEach((r,i)=>{r.push(derived[i]);affected++;if(examples.length<5)examples.push({row:i+1,before:r[c],after:derived[i]});});
  }else if(op==='cast type'){if(!['string','integer','number','boolean','date'].includes(spec.value))throw new Error(structuralText('v07.migrated.91cd1f71a10d'));if(next.rows.some(r=>r[c]!==''&&!validType(r[c],spec.value)))throw new Error(structuralText('v07.migrated.a071656de7fb'));next.columns[c].dataType=spec.value;affected=next.rows.length;}
  else {let mapping;if(op==='map codes'){mapping=JSON.parse(spec.value);if(!mapping||Array.isArray(mapping)||typeof mapping!=='object'||Object.values(mapping).some(v=>typeof v!=='string'))throw new Error(structuralText('v07.migrated.36e7d4991655'));}next.rows.forEach((r,i)=>{let v=r[c];if(op==='trim whitespace')v=v.trim();else if(op==='uppercase')v=v.toUpperCase();else if(op==='lowercase')v=v.toLowerCase();else if(op==='replace value')v=v===spec.match?spec.value:v;else if(op==='normalize missing'){if(!spec.value)throw new Error(structuralText('v07.migrated.c9f43e298d8b'));v=v===spec.value?'':v;}else if(op==='map codes')v=Object.hasOwn(mapping,v)?mapping[v]:v;else throw new Error(structuralText('v07.migrated.dbf97c073d29'));update(r,i,v);});if(op==='normalize missing')next.columns[c].missingToken=spec.value;}
  return {table:next,affected,examples};
}
export function applyRepair(p,tableId,spec,reason){if(spec.op==='reviewed translation')spec={upstreamOutcomePolicy:'propagate',...(spec.action==='date'?{datePolicy:'calendar-v2'}:{}),...spec};if(spec.review)evidenceGuard(p,spec);const t=p.tables.find(t=>t.id===tableId);if(!t)throw new Error(structuralText('v07.migrated.c0ade3b03880'));const preview=transform(t,{...spec,reason});return change(p,spec.op,reason,next=>{next.tables[next.tables.findIndex(t=>t.id===tableId)]=preview.table;if(spec.op==='rename column')for(const r of next.relationships){if(r.fromTable===tableId&&r.fromField===t.headers[spec.column])r.fromField=spec.value.trim();if(r.toTable===tableId&&r.toField===t.headers[spec.column])r.toField=spec.value.trim();}}, {tableId,spec:{...spec,reason},expectedSourceHash:p.resources.find(r=>r.id===t.resourceId).sha256});}
export function recipe(p){const active=new Set(p.undoStack);return {recipeVersion:1,projectSchemaVersion:p.projectSchemaVersion||3,applicationVersion:APP_VERSION,projectId:p.id,sources:p.resources.map(({id,sha256,name,bytes})=>({id,sha256,name,bytes})),tableDefinitions:p.tables.map(t=>({id:t.id,resourceId:t.resourceId,parsing:t.parsing,sheet:t.sheet,expectedOriginalHeaders:t.originalTable.headers})),steps:p.audit.filter(e=>e.operation&&active.has(e.id)).map(e=>({...e.operation,spec:e.operation.spec.op==='reviewed translation'?{upstreamOutcomePolicy:'legacy-literal',...(e.operation.spec.action==='date'?{datePolicy:'legacy-v1'}:{}),...e.operation.spec}:e.operation.spec,reason:e.reason}))};}
export function replay(p,rec){if(rec.recipeVersion!==1)throw new Error(structuralText('v07.migrated.ca5b64f36f10'));for(const src of rec.sources)if(!p.resources.some(r=>r.id===src.id&&r.sha256===src.sha256))throw new Error(structuralText('v07.migrated.319ce52a26ef'));if(rec.projectSchemaVersion!==undefined&&rec.projectSchemaVersion!==(p.projectSchemaVersion||3))throw new Error(structuralText('v07.migrated.5b0f2d33544f'));for(const src of rec.sources)if(src.bytes!==undefined&&p.resources.find(r=>r.id===src.id)?.bytes!==src.bytes)throw new Error(structuralText('v07.migrated.ba45ee201b40'));for(const definition of rec.tableDefinitions||[]){const table=p.tables.find(t=>t.id===definition.id&&t.resourceId===definition.resourceId);if(!table||definition.expectedOriginalHeaders&&JSON.stringify(definition.expectedOriginalHeaders)!==JSON.stringify(table.originalTable.headers)||JSON.stringify(definition.parsing)!==JSON.stringify(table.parsing)||definition.sheet!==table.sheet)throw new Error(structuralText('v07.migrated.b2d51d667c4c'));}let next=structuredClone(p);for(const t of next.tables){t.headers=structuredClone(t.originalTable.headers);t.rows=structuredClone(t.originalTable.rows);t.columns=t.headers.map((h,i)=>field(h,h,i));t.rowOrigins=t.rows.map((_,i)=>i);t.primaryKey=[];}next.relationships=[];next.undoStack=[];next.redoStack=[];for(const step of rec.steps)next=applyRepair(next,step.tableId,step.spec.op==='reviewed translation'?{upstreamOutcomePolicy:'legacy-literal',...(step.spec.action==='date'?{datePolicy:'legacy-v1'}:{}),...step.spec}:step.spec,`Recipe replay: ${step.reason}`);return next;}
export function validateProject(p){
 if(p?.version!==2||typeof p.id!=='string'||!Array.isArray(p.tables)||!Array.isArray(p.resources)||!Array.isArray(p.relationships)||!Array.isArray(p.audit)||!Array.isArray(p.undoStack)||!Array.isArray(p.redoStack)||!p.metadata)throw new Error(structuralText('v07.migrated.5fc235f99213'));
 if(!p.metadata.publicationDate)p.metadata.publicationDate=interpretation();for(const e of p.audit)for(const snap of [e.before,e.after].filter(Boolean))if(snap.metadata&&!snap.metadata.publicationDate)snap.metadata.publicationDate=interpretation();
 const ids=new Set();for(const r of p.resources){if(ids.has(r.id)||typeof r.id!=='string'||typeof r.name!=='string'||typeof r.base64!=='string'||!/^[a-f0-9]{64}$/.test(r.sha256))throw new Error(structuralText('v07.migrated.4d0c3f09d006'));ids.add(r.id);}
 const checkInterpretation=v=>{if(!v||typeof v.value!=='string'||!STATUSES.includes(v.status)||typeof v.rationale!=='string'||!Array.isArray(v.evidence)||!v.evidence.every(e=>typeof e==='string'))throw new Error(structuralText('v07.migrated.cb2fea041fd6'));};for(const [key]of META_FIELDS)checkInterpretation(p.metadata[key]);
 for(const key of ['creator','contributors']){const party=p.metadata[key];if(party.partyType!==undefined&&!['Unknown','Person','Organization'].includes(party.partyType))throw new Error(structuralText('v07.migrated.467d20761b45'));if(party.identifier!==undefined&&(typeof party.identifier!=='string'||party.identifier.length>2000||(party.identifier&&!/^[A-Za-z][A-Za-z0-9+.-]*:[^\s]+$/.test(party.identifier))))throw new Error(structuralText('v07.migrated.26848240f369'));}
 const checkTable=t=>{if(!t||typeof t.id!=='string'||!ids.has(t.resourceId)||!Array.isArray(t.headers)||!t.headers.length||t.headers.length>250||new Set(t.headers).size!==t.headers.length||!t.headers.every(h=>typeof h==='string'&&h.trim())||!Array.isArray(t.rows)||t.rows.length>100000||!t.rows.every(r=>Array.isArray(r)&&r.length===t.headers.length&&r.every(v=>typeof v==='string'))||!Array.isArray(t.columns)||t.columns.length!==t.headers.length||!Array.isArray(t.primaryKey)||!t.originalTable)throw new Error(structuralText('v07.migrated.e6098f5c6d13'));for(const c of t.columns){if(!c||!STATUSES.includes(c.status)||typeof c.description!=='string'||typeof c.term!=='string'||!Array.isArray(c.evidence)||!Array.isArray(c.allowedValues))throw new Error(structuralText('v07.migrated.7382e409a83a'));}if(!Array.isArray(t.originalTable.headers)||!Array.isArray(t.originalTable.rows)||!t.originalTable.rows.every(r=>r.length===t.originalTable.headers.length&&r.every(v=>typeof v==='string')))throw new Error(structuralText('v07.migrated.30d2af255606'));};
 const tableIds=new Set();for(const t of p.tables){checkTable(t);if(tableIds.has(t.id))throw new Error(structuralText('v07.migrated.e513e3d0e974'));tableIds.add(t.id);}for(const rel of p.relationships){if(!tableIds.has(rel.fromTable)||!tableIds.has(rel.toTable)||typeof rel.fromField!=='string'||typeof rel.toField!=='string')throw new Error(structuralText('v07.migrated.dfc391c7c3b8'));}
 for(const event of p.audit){if(typeof event.id!=='string'||typeof event.action!=='string'||typeof event.reason!=='string')throw new Error(structuralText('v07.migrated.e1fcf1d29491'));for(const s of [event.before,event.after].filter(Boolean)){if(!Array.isArray(s.tables)||!s.metadata||!Array.isArray(s.relationships))throw new Error(structuralText('v07.migrated.ff61ddc60396'));for(const t of s.tables)checkTable(t);for(const [k]of META_FIELDS)checkInterpretation(s.metadata[k]);}}
 if(new Set(p.audit.map(e=>e.id)).size!==p.audit.length||[...p.undoStack,...p.redoStack].some(id=>!p.audit.some(e=>e.id===id&&e.before&&e.after)))throw new Error(structuralText('v07.migrated.eeeb26a26b7c'));return p;
}
