import {decorateStudioSettings} from './studio-settings.mjs';
import {saveProjectTemplate,mountTemplateLibrary} from './templates.mjs';
import {t,htmlMessage,languagePreference,setLanguage,productionLocales,language} from './i18n.mjs';
import {localeInfo} from './locales.mjs';import {getProfile,profileLabel,editProfile,setProfile,profileChoicesHtml,bindProfileChoices} from './workspace-profile.mjs';import {getPreferences,setPreferences} from './preferences.mjs';import {APP_VERSION} from './project.mjs';
const h=(key,args)=>htmlMessage('v06.'+key,args);let selected='Home';
const categories=['Home','Appearance','Language','Workspace','Accessibility','Saving','Recovery','Import','Validation','Large','Privacy','Advanced','About'];
export function decorateSettingsV06(context={}){const form=document.querySelector('#preferences-form');if(!form||form.dataset.decorated)return;form.dataset.decorated='true';const originals=[...form.querySelectorAll('fieldset')],groups={Appearance:originals[0],Saving:originals[1],Import:originals[2],Large:originals[3]};
 for(const key of categories)if(!groups[key]){groups[key]=document.createElement('fieldset');form.append(groups[key]);}
 for(const key of categories){let legend=groups[key].querySelector('legend');if(!legend){legend=document.createElement('legend');groups[key].prepend(legend);}legend.textContent=t(key==='Home'?'v062.settingsHome':'v06.settings.'+key);groups[key].id='settings-v06-'+key;}
 const move=(selector,key)=>{const field=form.querySelector(selector);if(field)groups[key].append(field.closest('label'));};move('[name=motion]','Accessibility');move('[name=textSize]','Accessibility');move('[name=locale]','Language');move('[name=showValidationInfo]','Validation');
 const profileHost=document.createElement('div');profileHost.className='settings-profile-header';form.before(profileHost);const home=groups.Home;function homeSummary(){
 const merged=[...home.querySelectorAll('[data-studio-merged-section]')],project=context.getProject?.(),preferences=getPreferences();
 const row=(label,summary,detail,action,caption)=>`<section class="settings-summary-row"><div><span class="eyebrow">${label}</span><h3>${summary}</h3><p>${detail}</p></div><button type="button" class="button secondary" data-settings-jump="${action}">${caption}</button></section>`;
 home.innerHTML=`<legend>${htmlMessage('v062.settingsHome')}</legend><p>${h('settings.explanation')}</p>`+
 row(h('workspace'),profileLabel(),htmlMessage('studio.preview.'+getProfile().experience),'Workspace',htmlMessage('studio.change'))+
 row(h('settings.Appearance'),htmlMessage('studio.appearanceSummary',{theme:t('studio.theme.'+preferences.theme),surface:t('studio.'+preferences.surface)}),htmlMessage('studio.effectsSummary',{ambient:t(preferences.ambient?'studio.on':'studio.off'),motion:t('v06.settings.'+(preferences.motion==='system'?'full':preferences.motion))}),'Appearance',htmlMessage('studio.customize'))+
 row(h('settings.Language'),htmlMessage('v063.literal',{value:localeInfo[language()].name}),h('settings.local'),'Language',htmlMessage('studio.change'))+
 row(h('settings.Saving'),project?htmlMessage('v062.summaryRevision',{revision:project.revision}):htmlMessage('v062.noProject'),htmlMessage('v062.backupHonesty'),'Saving',htmlMessage('studio.openBackups'));
 home.append(...merged);home.querySelectorAll('[data-settings-jump]').forEach(button=>button.onclick=()=>form.querySelector('[data-category='+button.dataset.settingsJump+']').click());profileHost.replaceChildren();
 }homeSummary();const updateHome=()=>{if(!home.isConnected){window.removeEventListener('biorescue-preferences',updateHome);window.removeEventListener('biorescue-profile',updateHome);return;}homeSummary();};window.addEventListener('biorescue-preferences',updateHome);window.addEventListener('biorescue-profile',updateHome);
 const choices=document.createElement('section');choices.className='workspace-profile-cards';choices.dataset.tourId='workspace-profile';choices.innerHTML=profileChoicesHtml()+`<button type="button" class="button primary" data-apply-profile>${htmlMessage('studio.applyProfile')}</button>`;groups.Workspace.append(choices);const readProfile=bindProfileChoices(choices);choices.querySelector('[data-apply-profile]').onclick=()=>{setProfile({...getProfile(),...readProfile(),configured:true});context.notice?.(t('v06.saveProfile'));};

 groups.Workspace.insertAdjacentHTML('beforeend',`<p>${h('presentationOnly')}</p><p><strong>${profileLabel()}</strong></p><button type="button" class="button primary" data-edit-profile>${h('customizeTools')}</button>`);groups.Workspace.querySelector('[data-edit-profile]').onclick=()=>editProfile();groups.Workspace.insertAdjacentHTML('beforeend',`<button type="button" class="button secondary" data-save-template ${context.getProject?.()?'':'disabled'}>${htmlMessage('v062.saveTemplate')}</button>`);const library=document.createElement('section');groups.Workspace.append(library);const refreshLibrary=mountTemplateLibrary(library,context.notice);groups.Workspace.querySelector('[data-save-template]').onclick=async()=>{try{await saveProjectTemplate(context.getProject?.());refreshLibrary();}catch(error){context.notice?.(error.message.startsWith('V062_')?t('v062.error.'+error.message.slice(5)):error.message,true);}};
 const preferences=getPreferences();const yesNo=name=>'<label>'+htmlMessage('v0610.'+name)+'<select name="'+name+'"><option value="true">'+htmlMessage('v063.yes')+'</option><option value="false">'+htmlMessage('v063.no')+'</option></select></label>';groups.Import.insertAdjacentHTML('beforeend','<label>'+htmlMessage('v0610.wizard')+'<select name="importReviewStyle">'+['profile','guided','technical'].map(value=>'<option value="'+value+'">'+htmlMessage('v0610.'+value)+'</option>').join('')+'</select></label>'+yesNo('importTechnicalDetails')+yesNo('rememberImportChoices')+'<p>'+htmlMessage('v0610.rememberSafety')+'</p><label>'+htmlMessage('v0610.header')+'<input type="number" name="importHeaderRow" min="1" max="1000"></label><p>'+htmlMessage('v0610.headerHelp')+'</p><p>'+htmlMessage('v0610.detailsSafety')+'</p>');groups.Validation.insertAdjacentHTML('beforeend',['importCheckDates','importCheckCoordinates','importCheckIdentifiers'].map(yesNo).join('')+'<p>'+htmlMessage('v0610.integrityAlways')+'</p>');for(const key of ['importReviewStyle','importTechnicalDetails','rememberImportChoices','importHeaderRow','importCheckDates','importCheckCoordinates','importCheckIdentifiers'])form.querySelector('[name='+key+']').value=String(preferences[key]);
 const standards=document.createElement('details');standards.dataset.standardsPreferences='';standards.open=getProfile().experience==='advanced';standards.innerHTML='<summary>'+htmlMessage('v0613.title')+'</summary><p>'+htmlMessage('v0613.scope')+'</p><label>'+htmlMessage('v0613.provider')+'<select name="standardsSchemaProvider">'+['guide-only','tdwg-review-2026-07'].map(value=>'<option value="'+value+'">'+htmlMessage('v0613.provider.'+value)+'</option>').join('')+'</select></label><p>'+htmlMessage('v0613.reviewSafety')+'</p><label>'+htmlMessage('v0613.technical')+'<select name="standardsTechnicalDetails"><option value="false">'+htmlMessage('v063.no')+'</option><option value="true">'+htmlMessage('v063.yes')+'</option></select></label><p>'+htmlMessage('v0613.technicalSafety')+'</p><button type="button" class="button secondary" data-section="Standards validation">'+htmlMessage('v0613.openChecks')+'</button>';groups.Validation.append(standards);for(const name of ['standardsSchemaProvider','standardsTechnicalDetails'])standards.querySelector('[name='+name+']').value=String(preferences[name]);
 groups.Privacy.insertAdjacentHTML('beforeend',`<p>${h('settings.local')}</p>`);groups.About.insertAdjacentHTML('beforeend',`<p>${h('settings.about',{version:APP_VERSION})}</p><button type="button" class="button secondary" data-section="About">${h('settings.About')}</button>`);
 for(const [key,message,route]of [['Saving','autosave','Export'],['Recovery','recovery','Storage & Recovery'],['Import','import',null],['Validation','validation','Validate'],['Large','large','Large CSV'],['Advanced','advanced','Standards Center']])groups[key].insertAdjacentHTML('beforeend',`<p>${h('settings.'+message)}</p>${route?`<button type="button" class="button secondary" data-section="${route}">${h('nav.'+route+'.plain')}</button>`:''}`);
 const recovery=document.createElement('section');recovery.dataset.settingsRecovery='';groups.Recovery.append(recovery);const saving=document.createElement('section');saving.dataset.settingsSaving='';groups.Saving.append(saving);
 async function recoverySummary(){const project=context.getProject?.();if(!project){recovery.textContent=t('v062.noProject');saving.textContent=t('v062.noProject');return;}try{const [response,snapshotResponse]=await Promise.all([context.api('/api/recovery?id='+encodeURIComponent(project.id)),context.api('/api/snapshots?id='+encodeURIComponent(project.id))]);const status=await response.json(),snapshots=await snapshotResponse.json();if(!recovery.isConnected||context.getProject?.()?.id!==project.id)return;const line=(key,value)=>`<div><dt>${htmlMessage(key)}</dt><dd><bdi>${htmlMessage('v063.literal',{value:String(value??t('v062.notRecorded'))})}</bdi></dd></div>`;saving.innerHTML=`<dl class="translation-counts">${line('v062.summarySaving',status.revision)}${line('v063.latestAutosave',status.lastAutosave)}${line('v062.summaryBackup',project.recovery?.lastBackup)}</dl>`;recovery.innerHTML=`<dl class="translation-counts">${line('v062.summarySaving',status.revision)}${line('v063.latestAutosave',status.lastAutosave)}${line('v063.snapshotCount',snapshots.length)}${line('v063.pendingRecovery',status.draft? t('v062.draftsPresent'):t('v062.noDrafts'))}${line('v063.previousRecovery',t(status.previousRevisionAvailable?'v063.yes':'v063.no'))}${line('v063.pendingWrite',t(status.incompleteWrite?'v063.yes':'v063.no'))}${line('v062.summaryBackup',project.recovery?.lastBackup)}</dl>`;}catch{if(recovery.isConnected)recovery.textContent=t('v063.recoveryUnavailable');}}
 recoverySummary();
 const label=document.createElement('label');label.textContent=t('v06.settings.Language');const chooser=document.createElement('select');chooser.id='interface-language';for(const code of ['system',...productionLocales()]){const option=document.createElement('option');option.value=code;option.textContent=code==='system'?t('ui.70f401756382'):localeInfo[code].name;chooser.append(option);}chooser.value=languagePreference();chooser.onchange=()=>setLanguage(chooser.value);label.append(chooser);groups.Language.append(label);
 if(new URLSearchParams(location.search).get('i18nDebug')==='1'){const details=document.createElement('details');details.innerHTML='<summary>'+htmlMessage('ui.45def6f09aef')+'</summary>';const preview=document.createElement('select');preview.id='developer-language-preview';preview.setAttribute('aria-label',t('ui.e5b0be530f06'));for(const [code,info]of Object.entries(localeInfo)){const option=document.createElement('option');option.value=code;option.textContent=info.name;preview.append(option);}preview.value=language();preview.onchange=()=>setLanguage(preview.value,{preview:true,persist:false});details.append(preview);groups.Language.append(details);}
 const motion=form.querySelector('[name=motion]');motion.innerHTML=['system','full','reduced','off'].map(value=>`<option value="${value}">${value==='system'?htmlMessage('ui.5b986eb56e1c'):h('settings.'+value)}</option>`).join('');motion.value=getPreferences().motion;motion.onchange=()=>setPreferences({...getPreferences(),motion:motion.value});
 const searchLabel=document.createElement('label');searchLabel.textContent=t('v06.settings.search');const search=document.createElement('input');search.type='search';search.id='settings-search';search.setAttribute('aria-label',t('v06.settings.search'));searchLabel.append(search);form.before(searchLabel);
 const nav=document.createElement('nav');nav.className='settings-nav';nav.dataset.tourId='settings-categories';nav.setAttribute('aria-label',t('ui.b9ed95822f83'));for(const key of categories){const button=document.createElement('button');button.type='button';button.className='button secondary';button.textContent=t(key==='Home'?'v062.settingsHome':'v06.settings.'+key);button.setAttribute('aria-controls',groups[key].id);button.onclick=()=>{selected=key;search.value='';draw();};button.dataset.category=key;nav.append(button);}form.prepend(nav);
 const aliases={Home:'summary current workspace saving backup integrity',Appearance:'theme density',Language:'language region locale',Workspace:'beginner comfortable advanced role experience profile tools',Accessibility:'motion full reduced off text size accessibility',Saving:'backup autosave save',Recovery:'backup snapshots recovery',Import:'import encoding delimiter',Validation:'validation errors checks',Large:'large datasets performance',Privacy:'privacy network services',Advanced:'schemas diagnostics standards',About:'version license'};
 function draw(){const term=search.value.trim().toLocaleLowerCase();let matches=0;for(const key of categories){const group=groups[key],match=term&&(group.innerText.toLocaleLowerCase().includes(term)||aliases[key].includes(term));group.hidden=term?!match:key!==selected;const button=nav.querySelector('[data-category='+key+']');button.setAttribute('aria-current',!term&&key===selected?'page':'false');button.hidden=!!term&&!match;if(match)matches++;}let empty=document.querySelector('#settings-no-matches');if(!empty){empty=document.createElement('p');empty.id='settings-no-matches';empty.role='status';searchLabel.after(empty);}empty.textContent=t('v06.settings.noMatches');empty.hidden=!term||!!matches;}
 search.oninput=draw;draw();
 const theme=form.querySelector('[name=theme]'),grid=document.createElement('div');grid.className='theme-grid';grid.setAttribute('role','group');grid.setAttribute('aria-label',t('ui.d04517ddf23e'));const colors={system:['#f7f8f4','#142b26'],light:['#f7f8f4','#fff'],dark:['#142b26','#203b32'],paper:['#fff','#111'],'mono-dark':['#0b0b0b','#eee'],sand:['#f8f2e9','#76502d'],slate:['#161d2b','#b7d5fa'],ocean:['#f2f7fb','#1a5977'],forest:['#11271e','#d3e7b0']};for(const option of theme.options){const button=document.createElement('button');button.type='button';button.className='theme-card';button.dataset.theme=option.value;button.setAttribute('aria-pressed',String(theme.value===option.value));for(const color of colors[option.value]){const swatch=document.createElement('span');swatch.className='theme-swatch';swatch.style.background=color;swatch.setAttribute('aria-hidden','true');button.append(swatch);}const strong=document.createElement('strong');strong.textContent=option.textContent;button.append(strong);button.onclick=()=>{setPreferences({...getPreferences(),theme:option.value});theme.value=option.value;for(const card of grid.children)card.setAttribute('aria-pressed',String(card===button));};grid.append(button);}theme.closest('label').after(grid);theme.closest('label').hidden=true;
 decorateStudioSettings(form);
}

