import {htmlMessage as tr} from './i18n.mjs';
import {uiLabel,localizeMessage} from './i18n.mjs';
import {esc} from './components.mjs';
export async function standardsCenter({api,project,shell,isCurrent=()=>true}){
 const data=await(await api('/api/standards-center')).json();
 if(!isCurrent())return;
 const statuses={frictionless:'Descriptor validated; value rules partial',darwinCore:'Guide checks available; review schemas selectable; ratified conformance pending',dwcArchive:'Reviewed bounded star export; official XSD import failure and external consumer validation pending',eml:data.validators.lxml?'XSD validation available; generation partial':'XSD validator unavailable: install optional standards dependencies',roCrate:'Partial preservation graph',camtrap:data.validators.jsonschema&&data.validators.referencing?'Official descriptor and table checks; semantics partial':'Descriptor validator unavailable: install optional standards dependencies'};
 shell(`<section class="panel"><div class="eyebrow">${tr("ui.6d793c0a47cb")}</div><h1>${tr("v07x.standardsTitle")}</h1><p>${tr("v07x.standardsIntro")}</p><p data-i18n="ui.b5d0bf4c2179">${tr("ui.b5d0bf4c2179")}</p><div class="standards-grid">${Object.entries(data.profiles).map(([id,profile])=>`<article class="standard-card"><h2>${esc(uiLabel(profile.name))}</h2><p><strong>${esc(localizeMessage(profile.version))}</strong></p><p class="support-level tag">${tr(id==='darwinCore'?'v07x.standardGuide':id==='eml'&&!data.validators.lxml||id==='camtrap'&&(!data.validators.jsonschema||!data.validators.referencing)?'v07x.standardMissing':'v07x.standardPartial')}</p><p>${esc(localizeMessage(statuses[id]))}</p><p>${esc(localizeMessage(profile.capability))}</p><a href="${esc(profile.url)}" target="_blank" rel="noreferrer">${tr("ui.b984222ba928")}</a>${project?`<div class="small-actions"><button class="button secondary" data-section="Map to Standards" data-i18n="ui.98de7c7ee348">${tr("ui.98de7c7ee348")}</button><button class="button secondary" data-section="Standards validation" data-i18n="ui.25970a4446dc">${tr("ui.25970a4446dc")}</button><button class="button secondary" data-section="Export" data-i18n="ui.81dd4c062b3d">${tr("ui.81dd4c062b3d")}</button></div>`:''}</article>`).join('')}</div><details open><summary>${tr("ui.849aba972f6b")}</summary><p>${esc(localizeMessage(data.dwcDP.reason))}</p>${project?`<button class="button primary" data-section="DwC-DP preparation">${tr("ui.325e85978ffb")}</button>`:''}<p>${tr("ui.468998b19c63")} <code>${esc(data.dwcDP.profile)}</code></p><p>${esc(localizeMessage(data.dwcDP.import))} ${esc(localizeMessage(data.dwcDP.export))}</p><p data-i18n="ui.7f7565f5ac6e">${tr("ui.7f7565f5ac6e")}</p></details></section>`);
}
