export const studioCopy={
 'interaction.context':'Context and evidence', 'interaction.reviewCount':'{count} items need your review', 'interaction.nextPriority':'NEXT PRIORITY', 'interaction.prepareShare':'Prepare a defensible package', 'interaction.validationCount':'{count} findings · local check', 'interaction.locations':'Sensitive locations', 'interaction.requiresReview':'Review required', 'interaction.interpretations':'Unresolved interpretation', 'interaction.checkReadiness':'Check package readiness', 'interaction.readinessBoundary':'Local checks are a starting point. Privacy and package acceptance still require explicit review.',

 'rescue.preserved':'{count} preserved files inventoried.','rescue.dependencies':'{count} field-evidence review tasks must be resolved before accepting this mapping.',
 'rescue.timeout':'The local profiler exceeded its time limit. Retry or use manual inspection. Your project remains unchanged.',
 'studio.theme.museum':'Museum',
 'rescue.localHelper':'Deterministic · local · read only','rescue.workspace':'RESCUE WORKSPACE','rescue.hero':'Preserve the record. Understand the evidence. Make each decision visible.','rescue.tables':'tables','rescue.journey':'Your rescue journey','rescue.projectBrief':'PROJECT BRIEF','rescue.decisions':'Decisions ahead','rescue.decisionsBody':'Candidates need a person and a reason. Nothing is confirmed by the assistant.','rescue.reviewNext':'Review the next finding in context',
 'rescue.complete':'Complete','rescue.ready':'Ready','rescue.needsReview':'Needs review','rescue.blocked':'Blocked','rescue.expand':'Expand Rescue Assistant','rescue.minimize':'Minimize Rescue Assistant','rescue.finished':'Finished','rescue.working':'Working now','rescue.waiting':'Not started','rescue.continue':'You can keep working. These checks never edit your project.','rescue.outdated':'Files or evidence changed after this analysis. Analyze again before relying on this plan.','rescue.details':'Failure details','rescue.blockedBody':'Import a source file to begin. Manual tools remain available.','rescue.idle':'Start a local analysis when you are ready. Automatic analysis follows the preference in Settings.','rescue.summary':'{files} preserved files · {rows} of {total} rows checked. Findings are suggestions for review.','rescue.fullPlan':'Open the full rescue plan · {count} tasks','rescue.dependency':'Depends on preserved source evidence and your explicit review. No repair or scientific assignment has been applied.','rescue.openOverview':'Open the full plan','rescue.again':'Analyze again','rescue.safety':'Originals, working values and scientific meanings stay unchanged.','rescue.duplicates':'{name}: {count} repeated rows among {sampled} of {total} rows checked. Repetition may be intentional; no records are removed.',
 'rescue.phase.inventory':'Inventory preserved files','rescue.phase.profile':'Profile values and find patterns','rescue.phase.documentation':'Organize documentation and codebooks','rescue.phase.relationships':'Summarize possible relationships','rescue.phase.dates':'Surface date decisions','rescue.phase.plan':'Prepare the safe rescue plan',
 'rescue.state.idle':'Ready when you are','rescue.state.analyzing':'Analyzing locally','rescue.state.complete':'Analysis complete','rescue.state.needsDecision':'Analysis complete · decisions needed','rescue.state.blocked':'Waiting for source files','rescue.state.outdated':'Analysis is outdated','rescue.state.failed':'Failed safely',
 'rescue.guideLevel':'How much guidance would help?','rescue.guideResult':'Your suggested starting workspace','rescue.navPreview':'Navigation preview','rescue.materialPreview':'Your workspace material','rescue.materialIntro':'Choose how the workspace catches light. Data surfaces remain opaque for reading.',

 'studio.analysisMode':'Rescue Assistant analysis','studio.automatic':'Automatic','studio.askFirst':'Ask first','studio.analysisAsk':'Start a bounded local analysis when you are ready. No scientific decisions will be applied.','studio.analysisOff':'Automatic analysis is off. You can still analyze this project manually.','studio.analyzing':'Analyzing project…','studio.analysisFailed':'Automatic analysis could not finish. Your project is safe; manual workflows remain available.','studio.analysisReady':'Analyzed locally at {time}. Relevant changes require a fresh analysis.','studio.retry':'Retry analysis',
 'studio.choose':'Help me choose','studio.yourWorkbench':'Your Workbench','studio.applyProfile':'Apply workspace profile','studio.profilePreview':'Preview your workspace','studio.choosePrompt':'What will you mainly work with? Choose a starting point; you can change every choice below.',
 'studio.choose.field':'Field observations and surveys','studio.choose.collections':'Collections and historical records','studio.choose.technical':'Schemas, databases and data pipelines','studio.choose.level':'Choose Beginner for explanations, Comfortable for normal terminology, or Advanced for technical detail. Your role never changes scientific truth.',
 'studio.role.field':'Explore survey records, sites and field documentation.','studio.role.wildlife':'Review wildlife observations, effort and uncertainty.','studio.role.curator':'Manage datasets, dictionaries and review decisions.','studio.role.museum':'Connect specimens, collection records and history.','studio.role.archivist':'Preserve documents and trace their evidence.','studio.role.student':'Learn rescue workflows with guided examples.','studio.role.technical':'Inspect schemas, standards and data pipelines.','studio.role.other':'Use a general workspace and choose your own tools.',
 'studio.level.beginner':'Plain language, explanations and technical detail on demand.','studio.level.comfortable':'Scientific and data terminology with guidance where useful.','studio.level.advanced':'Schemas, standards and technical tools visible by default.',
 'studio.preview.beginner':'Example: “What this field means” · Guided workflow · Technical detail on demand.','studio.preview.comfortable':'Example: “Field interpretation” · Normal workflow · Contextual guidance.','studio.preview.advanced':'Example: “Dictionary, schema and term mapping” · Standards and technical tools exposed.',
 'studio.customize':'Customize','studio.change':'Change','studio.openBackups':'Open recovery & backups','studio.appearanceSummary':'{theme} · {surface}','studio.effectsSummary':'Ambient: {ambient} · Motion: {motion}','studio.on':'On','studio.off':'Off','studio.systemAccessibility':'System accessibility preferences take priority: reduced motion, reduced transparency and forced colors.',
 'studio.screenshotReadFailed':'The screenshot could not be read. Choose another image or prepare the request without it.','studio.copyFailed':'Copy is unavailable. Download the prepared request instead.',
 'studio.nav.Sources':'Files','studio.nav.Inspect':'Understand','studio.nav.Review queue':'Review','studio.nav.Repair':'Repair','studio.nav.Translate & standardize':'Standardize','studio.nav.Validate':'Validate','studio.nav.Export':'Package','studio.nav.Metadata':'Metadata','studio.nav.Evidence':'Evidence','studio.nav.Relationships':'Relationships',
 'studio.menu':'Workbench commands','studio.collapse':'Compact sidebar','studio.expand':'Expand sidebar','studio.new':'New project','studio.open':'Open project','studio.window':'Open new window','studio.import':'Import files','studio.package':'Create package','studio.settings':'Settings','studio.help':'Help & learning','studio.close':'Close this window',
 'studio.dataView':'DATA VIEW','studio.source':'Source','studio.working':'Working copy','studio.reviewed':'Reviewed output','studio.layers':'What are these views?','studio.sourceBody':'Exactly what was imported. Preserved bytes and literal source values remain available.','studio.workingBody':'Your reversible, audited repairs. A repair does not establish scientific meaning.','studio.reviewedBody':'Explicitly reviewed interpretations and derived values. Review does not guarantee scientific correctness.',
 'studio.theme':'Theme library','studio.surface':'Window surface','studio.surfaceBody':'Presentation only. Native window controls remain available.','studio.solid':'Solid','studio.frosted':'Frosted','studio.glass':'Glass','studio.minimal':'Minimal','studio.transparency':'Reduce transparency','studio.transparencyBody':'Use opaque surfaces for a calmer, more readable workspace.','studio.ambient':'Ambient background','studio.ambientBody':'Subtle background movement in Full motion; data tables remain stable.','studio.sidebar':'Sidebar','studio.expanded':'Expanded','studio.compact':'Compact','studio.tableDensity':'Data grid density','studio.comfortable':'Comfortable','studio.dense':'Dense','studio.noise':'Visual decoration','studio.normal':'Standard','studio.quiet':'Quiet','studio.focus':'Emphasize keyboard focus','studio.tableAccess':'Expanded accessible tables','studio.tableAccessBody':'Remove the grid height limit and allow literal values to wrap.','studio.auto':'Prepare the Rescue Assistant automatically','studio.autoBody':'Bounded local candidates and previews only. No repairs or scientific confirmations are applied.',
 'studio.assistant':'Rescue Assistant','studio.assistantIntro':'A local, deterministic work plan. You make every scientific decision.','studio.analyze':'Analyze project','studio.coverage':'Sampled {sampled} of {total} rows. {complete}','studio.complete':'Row sampling complete; analysis is still bounded.','studio.sample':'Suggestions are sample-based, not a complete inspection.','studio.candidates':'candidate findings','studio.mechanical':'whitespace-change candidates','studio.unknown':'unknown fields','studio.conflicts':'conflicting fields','studio.plan':'Your next decisions','studio.why':'Why this matters','studio.knows':'What Workbench knows','studio.openTask':'Open workflow','studio.noFindings':'No candidate findings in the bounded analysis. Check source integrity, documentation and privacy before packaging.','studio.never':'No species identification, date convention, datum, unit meaning or missing-token meaning is selected automatically.',
 'studio.stage.sources':'Sources','studio.stage.understand':'Understand','studio.stage.review':'Review','studio.stage.repair':'Repair','studio.stage.standardize':'Standardize','studio.stage.validate':'Validate','studio.stage.package':'Package','studio.recorded':'Inventory recorded','studio.notRecorded':'Not recorded','studio.reviewNeeded':'Needs human review','studio.check':'Run checks','studio.packageCheck':'Review privacy & purpose',
 'studio.helpHome':'Help home','studio.helpTitle':'Make your next decision with confidence','studio.helpIntro':'Practical answers, worked examples and safe practice. Your originals and uncertainty stay visible.','studio.questions':'Questions researchers ask','studio.example':'Worked example','studio.mistake':'Common mistake','studio.related':'Related workflows','studio.learn':'Learn & practice','studio.support':'Get assistance','studio.question':'Ask a question','studio.bug':'Report a bug','studio.improvement':'Suggest an improvement','studio.backup':'Data or backup problem','studio.importProblem':'Import problem','studio.standards':'Standards question','studio.access':'Accessibility issue','studio.desktop':'Desktop problem','studio.trying':'What were you trying to do?','studio.happened':'What happened instead?','studio.screenshot':'Optional screenshot','studio.screenshotHelp':'Only include a screenshot you have reviewed for private values. Images stay local until you choose to share the prepared bundle.','studio.diagnosticPreview':'Diagnostic preview','studio.delivery':'Prepared locally. Workbench has no live support delivery service. Copy or download this request, then share it through a support channel you trust.','studio.saved':'Support bundle saved.','studio.cancelled':'Save cancelled; no delivery was made.','studio.attachmentLimit':'Use a PNG or JPEG screenshot up to 5 MiB.','studio.previewProject':'Project preview','studio.lastOpened':'Last opened','studio.backupState':'Backup request','studio.none':'Not recorded','studio.technical':'Technical details','studio.reviewMode':'Focused review','studio.reviewAll':'Show full queue',
 'studio.theme.system':'System','studio.theme.light':'Light','studio.theme.dark':'Forest Night','studio.theme.forest':'Forest','studio.theme.ocean':'Ocean','studio.theme.aurora':'Aurora','studio.theme.midnight':'Midnight','studio.theme.slate':'Slate','studio.theme.paper':'Paper','studio.theme.field-notes':'Field Notes','studio.theme.sand':'Sand','studio.theme.mono-light':'Monochrome Light','studio.theme.mono-dark':'Monochrome Dark','studio.theme.high-contrast':'High Contrast'
};
