import {buildIdentity} from './build-identity.mjs';
import {getPreferences,setPreferences} from './preferences.mjs';
import {t,htmlMessage as h} from './i18n.mjs';
import {icon,routeIcon} from './studio-icons.mjs';
import {createRescueSession,assistantStateHtml,analyzeInWorker} from './rescue-assistant.mjs';
import {newWindow} from './desktop-bridge.mjs';
import {refreshSelectableSurfaces,motionTiming} from './components.mjs';
export function setupStudio({getProject,getList,closeWindow,notice}){
 const rail=document.querySelector('.sidebar'),indicator=document.createElement('span');indicator.className='navigation-indicator';indicator.setAttribute('aria-hidden','true');rail.append(indicator);
 const tabPositions=new Map();let previousContent,previousChild,pageAnimation;
 const updateInteractions=()=>{refreshSelectableSurfaces();const active=rail.querySelector('.rail-link.active,.nav.active');if(active){const rect=active.getBoundingClientRect(),base=rail.getBoundingClientRect();indicator.style.transform=`translateY(${rect.top-base.top+rail.scrollTop}px)`;indicator.style.height=rect.height+'px';indicator.hidden=false;}else indicator.hidden=true;
  document.querySelectorAll('.settings-nav,.review-filters').forEach(bar=>{const selected=bar.querySelector('[aria-current=page],[aria-pressed=true]');if(!selected)return;let marker=bar.querySelector(':scope > .tab-indicator');if(!marker){marker=document.createElement('span');marker.className='tab-indicator';marker.setAttribute('aria-hidden','true');bar.append(marker);}const box=selected.getBoundingClientRect(),base=bar.getBoundingClientRect(),position=`translate(${box.left-base.left}px,${box.bottom-base.top}px)`,key=bar.className,previous=tabPositions.get(key);marker.style.width=box.width+'px';marker.style.transform=position;if(previous&&previous!==position&&document.documentElement.dataset.motion==='full')marker.animate([{transform:previous},{transform:position}],motionTiming('panel'));tabPositions.set(key,position);});
 };
 document.addEventListener('change',()=>requestAnimationFrame(updateInteractions));
 document.addEventListener('click',event=>{const card=event.target.closest('.review-card:has([data-select-review])');if(card&&!event.target.closest('button,a,input,label,summary,details,select,textarea')){const input=card.querySelector('[data-select-review]');if(!input.disabled)input.click();}requestAnimationFrame(updateInteractions);});
 window.addEventListener('resize',updateInteractions);
 const noticeHost=document.querySelector('#notice');new MutationObserver(()=>{if(noticeHost.classList.contains('visible')&&document.documentElement.dataset.motion!=='off')noticeHost.animate(document.documentElement.dataset.motion==='reduced'?[{opacity:0},{opacity:1}]:[{opacity:0,transform:'translateY(4px)'},{opacity:1,transform:'none'}],motionTiming('standard'));}).observe(noticeHost,{childList:true});
 new MutationObserver(()=>{if(['off','reduced'].includes(document.documentElement.dataset.motion))document.getAnimations().forEach(animation=>animation.cancel());}).observe(document.documentElement,{attributes:true,attributeFilter:['data-motion']});
 const top=document.querySelector('.topbar'),host=document.createElement('div');host.className='studio-app-menu';host.innerHTML=`<button class="icon-button" aria-label="${h('studio.menu')}" aria-expanded="false" aria-controls="studio-menu">${icon('menu')}</button><div id="studio-menu" class="studio-menu-popover" hidden></div>`;top.prepend(host);
 const toggle=host.querySelector('button'),popover=host.querySelector('div');const commands=[['new','plus','new'],['open','library','Projects'],...(window.__TAURI_INTERNALS__?[['window','window','window']]:[]),['import','files','import'],['package','package','Export'],['settings','settings','Settings'],['help','help','Help'],...(window.__TAURI_INTERNALS__?[['close','close','close']]:[])];
 popover.innerHTML=commands.map(([label,glyph,action])=>`<button data-studio-command="${action}">${icon(glyph)}${h('studio.'+label)}</button>`).join('');const shut=()=>{popover.hidden=true;toggle.setAttribute('aria-expanded','false');};
 toggle.onclick=()=>{popover.hidden=!popover.hidden;toggle.setAttribute('aria-expanded',!popover.hidden);if(!popover.hidden)popover.querySelector('button').focus();};
 popover.onclick=async event=>{const button=event.target.closest('[data-studio-command]');if(!button)return;shut();const action=button.dataset.studioCommand;try{if(action==='window')await newWindow();else if(action==='close')await closeWindow();else if(action==='new')document.querySelector('#new-button').click();else if(action==='import'){const importButton=document.querySelector('#main [data-action=import]');if(importButton)importButton.click();else document.querySelector('#new-button').click();}else{const target=document.createElement('button');target.dataset.section=action;document.body.append(target);target.click();target.remove();}}catch(error){notice(String(error),true);}};
 document.addEventListener('click',event=>{if(!host.contains(event.target))shut();});host.onkeydown=event=>{const buttons=[...popover.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(event.key==='Escape'){shut();toggle.focus();}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)&&!popover.hidden){event.preventDefault();buttons[event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}};
 const collapse=document.createElement('button');collapse.className='nav studio-collapse';collapse.title=t('studio.collapse');collapse.setAttribute('aria-label',t('studio.collapse'));collapse.innerHTML=icon('chevron')+`<span>${h('studio.collapse')}</span>`;document.querySelector('.rail-bottom').prepend(collapse);collapse.onclick=()=>setPreferences({...getPreferences(),sidebar:getPreferences().sidebar==='compact'?'expanded':'compact'});
 const pause=()=>{document.documentElement.dataset.animationPaused=String(document.hidden||document.querySelector('[aria-busy=true]')!==null);};document.addEventListener('visibilitychange',pause);
 const sessions=new Map();let expanded=false;let scheduled=false,activeId=null,minimized=sessionStorage.getItem('biorescue-buddy-minimized')!=='false';
 const buddy=document.createElement('aside');buddy.className='rescue-buddy';buddy.setAttribute('aria-label',t('studio.assistant'));document.querySelector('.app-shell').append(buddy);
 function session(p){if(!sessions.has(p.id)){if(sessions.size>=5)sessions.delete(sessions.keys().next().value);sessions.set(p.id,createRescueSession({analyzer:analyzeInWorker,notify:()=>{paint();window.dispatchEvent(new CustomEvent('biorescue-assistant-state',{detail:{projectId:p.id,state:sessions.get(p.id)?.state}}));}}));}return sessions.get(p.id);}
 function paint(){const p=getProject();buddy.hidden=!p||!!document.querySelector('.guided-overview');document.documentElement.dataset.companion=String(!buddy.hidden&&!minimized);if(!p)return;const state=session(p).state;
  const targets=[[buddy,true],...document.querySelectorAll('[data-assistant-workspace]').values()].map(entry=>Array.isArray(entry)?entry:[entry,false]);
  for(const [host,compact]of targets){const stamp=[p.id,state.status,state.stage,state.completed.length,state.finishedAt,minimized,expanded].join(':');if(host.dataset.assistantStamp===stamp)continue;host.dataset.assistantStamp=stamp;host.dataset.assistantState=state.status;host.setAttribute('aria-busy',String(state.status==='analyzing'));host.innerHTML=assistantStateHtml(p,state,{compact:compact||!expanded,minimized:compact&&minimized});if(!compact){const expand=document.createElement('button');expand.type='button';expand.className='text-button';expand.dataset.assistantExpand='';expand.textContent=expanded?'Show summary':'Expand investigation plan';expand.setAttribute('aria-expanded',String(expanded));expand.onclick=()=>{expanded=!expanded;paint();};host.append(expand);}host.querySelector('[data-cancel-analysis]')?.addEventListener('click',()=>session(getProject()).cancel());host.querySelector('[data-analyze-project]')?.addEventListener('click',()=>session(getProject()).run(getProject()));host.querySelectorAll('[data-assistant-category]').forEach(button=>button.onclick=()=>window.dispatchEvent(new CustomEvent('biorescue-review-category',{detail:button.dataset.assistantCategory})));host.querySelector('[data-assistant-minimize]')?.addEventListener('click',()=>{minimized=!minimized;sessionStorage.setItem('biorescue-buddy-minimized',String(minimized));paint();});}
 }
 function enhance(){scheduled=false;if(document.querySelector('[data-about-view]')&&!document.querySelector('[data-build-provenance]')){const box=document.createElement('section');box.dataset.buildProvenance='';const heading=document.createElement('h2');heading.textContent='Build provenance';const pre=document.createElement('pre');pre.className='diagnostic-preview';pre.textContent=JSON.stringify(buildIdentity,null,2);box.append(heading,pre);document.querySelector('[data-about-view]').append(box);}pause();updateInteractions();const content=document.querySelector('.workspace-content');if(content&&(content!==previousContent||content.firstElementChild!==previousChild)){previousContent=content;previousChild=content.firstElementChild;pageAnimation?.cancel();if(document.documentElement.dataset.motion!=='off')pageAnimation=content.animate(document.documentElement.dataset.motion==='reduced'?[{opacity:0},{opacity:1}]:[{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'none'}],motionTiming('panel'));}const p=getProject(),overview=document.querySelector('.guided-overview');
  document.querySelectorAll('.sidebar .nav').forEach(button=>{if(button.dataset.studioIcon)return;const span=button.querySelector('[aria-hidden=true],.nav-icon');if(span){span.outerHTML=icon(routeIcon(button.dataset.section||(button.id==='workstation-home'?'Project':button.id==='home-button'?'Projects':'Sources')));button.dataset.studioIcon='true';}if(!button.getAttribute('aria-label'))button.setAttribute('aria-label',button.textContent.trim());if(!button.title)button.title=button.getAttribute('aria-label');});
  if(overview&&p&&!overview.querySelector('[data-assistant-workspace]')){const panel=document.createElement('section');panel.className='rescue-assistant';panel.dataset.assistantWorkspace='';overview.querySelector('.overview-command-deck')?.append(panel);}
  if(p){const current=session(p);current.sync(p);if(activeId!==p.id){activeId=p.id;if(current.state.status==='idle'&&p.resources.length&&getPreferences().automaticAnalysis===true)current.run(p);}}else activeId=null;
  paint();
  const help=document.querySelector('[data-help-center],.help-center,.help-layout');if(help&&p&&!document.querySelector('#main [data-assistant-help]')){const button=document.createElement('button');button.className='button secondary';button.dataset.assistantHelp='';button.dataset.section='Project';button.textContent=t('studio.assistant');document.querySelector('#main>.page-heading')?.append(button);}
  document.querySelectorAll('.hub-project').forEach(card=>{if(card.querySelector('[data-preview-project]'))return;const id=card.querySelector('[data-hub-open]')?.dataset.hubOpen;if(!id)return;const button=document.createElement('button');button.type='button';button.className='button secondary';button.dataset.previewProject=id;button.textContent=t('studio.previewProject');card.append(button);button.onclick=()=>{const item=getList().find(item=>item.id===id);if(!item)return;document.querySelector('.hub-preview')?.remove();const preview=document.createElement('section');preview.className='hub-preview';const title=document.createElement('h2');title.textContent=item.title;preview.append(title);const text=document.createElement('p');text.textContent=item.description||t('studio.none');preview.append(text);const dl=document.createElement('dl');for(const [label,value]of [[t('studio.nav.Sources'),item.resources||0],[t('studio.unknown'),item.unknowns||0],[t('studio.conflicts'),item.conflicts||0],[t('studio.lastOpened'),item.lastOpened||t('studio.none')],[t('studio.backupState'),item.lastBackupRequested||t('studio.none')]]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);dl.append(div);}preview.append(dl);const open=document.createElement('button');open.className='button primary';open.textContent=t('studio.open');open.dataset.hubOpen=id;open.onclick=()=>card.querySelector('[data-hub-open]').click();preview.append(open);if(window.__TAURI_INTERNALS__&&item.state==='active'){const another=document.createElement('button');another.className='button secondary';another.textContent=t('studio.window');another.onclick=()=>newWindow(id).catch(error=>notice(String(error),true));preview.append(another);}document.querySelector('.hub-toolbar').after(preview);preview.scrollIntoView({block:'nearest'});};});
  const queue=document.querySelector('[data-tour-id=review-queue-panel]');if(queue&&!queue.querySelector('[data-review-focus]')){const button=document.createElement('button');button.className='button secondary';button.dataset.reviewFocus='';button.textContent=t('studio.reviewMode');button.setAttribute('aria-pressed','false');const toolbar=document.createElement('div');toolbar.className='review-focus-controls';toolbar.append(button);queue.prepend(toolbar);let index=0;const navigation=document.createElement('div');navigation.className='small-actions';navigation.hidden=true;const previous=document.createElement('button'),next=document.createElement('button');previous.className=next.className='button secondary';previous.textContent=t('previous');next.textContent=t('next');navigation.append(previous,next);toolbar.append(navigation);const shortcuts=document.createElement('input');shortcuts.type='checkbox';shortcuts.dataset.reviewShortcuts='';const label=document.createElement('label');label.className='checkbox-label';label.append(shortcuts,document.createTextNode(t('workspace.shortcuts')));toolbar.append(label);const progress=document.createElement('span');progress.setAttribute('aria-live','polite');toolbar.append(progress);const drawFocus=()=>{const cards=[...queue.querySelectorAll('.review-card')];cards.forEach((card,i)=>card.hidden=queue.classList.contains('focused-review')&&i!==index);previous.disabled=index===0;next.disabled=index>=cards.length-1;progress.textContent=t('workspace.reviewProgress',{index:cards.length?index+1:0,count:cards.length});};queue.onkeydown=event=>{if(!shortcuts.checked||!queue.classList.contains('focused-review')||event.ctrlKey||event.metaKey||event.altKey||event.target.closest('input,textarea,select,[contenteditable],[role=combobox]')||document.querySelector('dialog[open]'))return;const states={a:'Accepted',u:'Intentionally unresolved',c:'Reviewed',r:'Rejected'},state=states[event.key.toLowerCase()];if(!state)return;const review=queue.querySelector('.review-card:not([hidden]) [data-review]');if(!review||review.disabled)return;event.preventDefault();review.click();const choice=[...document.querySelectorAll('dialog[open] [data-choice]')].find(b=>b.textContent===t('v06.state.'+state));choice?.focus();};previous.onclick=()=>{index=Math.max(0,index-1);drawFocus();};next.onclick=()=>{index=Math.min(queue.querySelectorAll('.review-card').length-1,index+1);drawFocus();};button.onclick=()=>{const focused=queue.classList.toggle('focused-review');navigation.hidden=!focused;button.setAttribute('aria-pressed',focused);button.textContent=t(focused?'studio.reviewAll':'studio.reviewMode');drawFocus();};}
 }
 window.addEventListener('biorescue-import-complete',()=>{const p=getProject();if(p&&getPreferences().automaticAnalysis===true)session(p).run(p);});
 const schedule=()=>{if(!scheduled){scheduled=true;requestAnimationFrame(enhance);}};new MutationObserver(schedule).observe(document.querySelector('#main'),{childList:true,subtree:true});window.addEventListener('biorescue-route',schedule);window.addEventListener('biorescue-preferences',()=>{collapse.setAttribute('aria-label',t(getPreferences().sidebar==='compact'?'studio.expand':'studio.collapse'));collapse.title=collapse.getAttribute('aria-label');schedule();});schedule();
 if(window.__TAURI_INTERNALS__){const updateCaption=()=>window.__TAURI_INTERNALS__.invoke('native_window_action',{action:'theme',title:matchMedia('(forced-colors: active)').matches?'system':document.documentElement.dataset.theme||'light'}).catch(()=>{});new MutationObserver(updateCaption).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});matchMedia('(forced-colors: active)').addEventListener('change',updateCaption);updateCaption();let title='';const updateTitle=()=>{if(title===document.title)return;title=document.title;window.__TAURI_INTERNALS__.invoke('native_window_action',{action:'title',title}).catch(()=>{});};new MutationObserver(updateTitle).observe(document.querySelector('title'),{childList:true});updateTitle();}
}

