// Public destinations verified against the maintainer's GitHub profile/funding metadata.
export const destinations=Object.freeze([
 Object.freeze({id:'github-sponsors',label:'GitHub Sponsors',url:'https://github.com/sponsors/amgedi'}),
 Object.freeze({id:'ko-fi',label:'Ko-fi',url:'https://ko-fi.com/openfhs'})
]);
export const SUPPORT_KEY='biorescue-support';
export const COOLDOWN=90*24*60*60*1000;
export const initialSupport=()=>({enabled:true,eligible:false,lastShown:0,dismissed:0,shown:0});
export function cleanSupport(value){const clean=initialSupport();if(!value||typeof value!=='object')return clean;clean.enabled=value.enabled!==false;clean.eligible=value.eligible===true;for(const key of ['lastShown','dismissed','shown'])clean[key]=Number.isSafeInteger(value[key])&&value[key]>=0?value[key]:0;return clean;}
export function readSupport(storage=localStorage){try{return cleanSupport(JSON.parse(storage.getItem(SUPPORT_KEY)||'null'));}catch{return {...initialSupport(),enabled:false};}}
export function updateSupport(patch,storage=localStorage){const state=cleanSupport({...readSupport(storage),...patch});storage.setItem(SUPPORT_KEY,JSON.stringify(state));return state;}
export function reminderEligible(state,context,now=Date.now()){return state.enabled&&state.eligible&&state.shown<2&&context.route==='Home'&&!context.projectOpen&&!context.busy&&!context.dialogOpen&&!context.errorSeen&&now-Math.max(state.lastShown,state.dismissed)>=COOLDOWN;}
export async function openSupport(id,{invoke=globalThis.window?.__TAURI_INTERNALS__?.invoke,open=globalThis.window?.open?.bind(globalThis.window)}={}){const target=destinations.find(item=>item.id===id);if(!target)throw Error('Unknown support destination.');if(invoke)return invoke('support_open',{destination:id});if(!open)throw Error('The browser could not be opened.');open(target.url,'_blank','noopener,noreferrer');}
export function supportPanel(){return `<p>Bio is free and open source.</p><p>If the Workbench helped you preserve or rescue a dataset, optional support helps fund development, testing, documentation, accessibility, and long-term maintenance.</p><div class="heading-actions">${destinations.map(d=>`<button class="button" data-support-destination="${d.id}">${d.label} ↗</button>`).join('')}</div><p class="muted">Opens the selected page in your browser. Every feature remains free.</p><button class="button" data-action="dismiss">Maybe later</button>`;}
export function mountSupportReminder(host,context,{storage=localStorage,openPanel,now=Date.now()}={}){const state=readSupport(storage);if(!host||!reminderEligible(state,context,now))return false;try{updateSupport({lastShown:now,shown:state.shown+1},storage);}catch{return false;}const card=document.createElement('aside');card.className='support-reminder';card.setAttribute('aria-label','Optional project support');card.innerHTML='<strong>Enjoying Bio?</strong><p>Bio is free and open source. If it has been useful, you can support continued development.</p><div class="heading-actions"><button class="text-button" data-support-yes>Support Bio</button><button class="text-button" data-support-later>Not now</button><button class="text-button" data-support-never>Don’t show this again</button></div>';host.append(card);const dismiss=patch=>{try{updateSupport({dismissed:now,...patch},storage);}catch{}finally{card.remove();}};card.querySelector('[data-support-yes]').onclick=()=>{dismiss({});openPanel();};card.querySelector('[data-support-later]').onclick=()=>dismiss({});card.querySelector('[data-support-never]').onclick=()=>dismiss({enabled:false});return true;}
