const CACHE='biorescue-shell-0.7.0-development-0-workstation-rebuild-1';
// This source-only review module is part of the offline shell, never an API cache.
const ASSETS=['/workbench.css','/build-identity.mjs','/dwca-export.mjs','/ocr-review.mjs','/date-time-review.mjs','/large-encrypted-backup.mjs','/practice-catalog.mjs','/practice-amphibian.json','/practice-museum.json','/practice-camera.json','/tutorial-registry.mjs','/workspace-core.mjs','/workspace-copy.mjs','/context-inspector.mjs','/advanced-workspace.css','/studio.css','/studio.mjs','/studio-copy.mjs','/studio-themes.mjs','/studio-icons.mjs','/studio-settings.mjs','/rescue-assistant.mjs','/knowledge.mjs','/desktop-client-state.mjs','/glossary.mjs','/help-workflows.mjs','/desktop-health.mjs','/experience-copy.mjs','/workflow-experience.mjs','/workflow-experience.css','/biodiversity-icon-32.png','/biodiversity-icon-192.png','/biodiversity-icon-512.png','/first-run.mjs','/table-workbench.mjs','/structural-copy.mjs','/workstation.mjs','/workstation-copy.mjs','/help-center.mjs','/desktop-bridge.mjs','/workstation.css','/coordinate-pair.mjs','/taxonomy-review.mjs','/date-calendar-v2.mjs','/key-comparison-core.mjs','/key-comparison-ui.mjs','/import-screening.mjs','/document-evidence.mjs','/large-restore.mjs','/link-drafts.mjs','/large-links.mjs','/large-metadata.mjs','/analysis-providers.mjs','/mechanical-batch.mjs','/note-targets.mjs','/resume-context.mjs','/comparison.mjs','/biodiversity-mark.svg','/templates.mjs','/evidence-discovery.mjs','/translation-ui.mjs','/translation-core.mjs','/source-integrity.mjs','/import-discovery.mjs','/settings-v06.mjs','/workspace-profile.mjs','/smart-analysis.mjs','/guided-workspace.mjs','/v06.css','/','/app2.mjs','/advanced.mjs','/encryption.mjs','/shell.mjs','/project.mjs','/model.mjs','/styles.css','/upgrade.css','/v03.css','/theme.css','/preferences.mjs','/uploads.mjs','/drafts.mjs','/components.mjs','/management.mjs','/v05.css','/refinement.css','/brand-mark-192-v05.png','/brand-mark-512-v05.png','/manifest-v05.webmanifest','/combobox.mjs','/onboarding.mjs','/tour.mjs','/dwc-preparation.mjs','/window-recovery.mjs','/edit-sessions.mjs','/settings-ui.mjs','/i18n.mjs','/commands.mjs','/standards-center.mjs','/locales.mjs','/icon.svg','/icon-192.png','/icon-512.png','/manifest.webmanifest'];
// No API responses, demo backups, project data, evidence, or exports enter this cache.
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('message',e=>{if(e.data?.type==='ACTIVATE_SAVED_UPDATE')self.skipWaiting();});
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('biorescue-shell-')&&k!==CACHE).map(k=>caches.delete(k))))));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==self.location.origin||!ASSETS.includes(u.pathname)||u.search)return;e.respondWith(fetch(e.request).then(async response=>{if(response.ok)(await caches.open(CACHE)).put(e.request,response.clone());return response;}).catch(()=>caches.match(e.request)));});


