import {field} from './project.mjs';
const fail=key=>{throw new Error('V062_'+key);};
export const TAXONOMY_LIMITS=Object.freeze({referenceRows:10000,referenceCodeUnits:2000000,observationRows:100000});
function shape(reference){if(!reference||reference.policy!=='local-literal-taxonomy-v1'||typeof reference.release!=='string'||!reference.release.trim()||reference.release.length>2000||!Array.isArray(reference.headers)||!Array.isArray(reference.entries)||reference.entries.length>TAXONOMY_LIMITS.referenceRows)fail('TAXONOMY_REFERENCE');let chars=0;for(const row of reference.entries){if(!Array.isArray(row)||row.length!==3||row.some(v=>typeof v!=='string'))fail('TAXONOMY_REFERENCE');chars+=row.reduce((n,v)=>n+v.length,0);}if(chars>TAXONOMY_LIMITS.referenceCodeUnits)fail('TAXONOMY_LIMIT');for(const key of ['recordedColumn','targetColumn'])if(!Number.isInteger(reference[key])||reference[key]<0||reference[key]>=reference.headers.length)fail('TAXONOMY_REFERENCE');if(reference.recordedColumn===reference.targetColumn||reference.identifierColumn!==null&&(!Number.isInteger(reference.identifierColumn)||reference.identifierColumn<0||reference.identifierColumn>=reference.headers.length||[reference.recordedColumn,reference.targetColumn].includes(reference.identifierColumn)))fail('TAXONOMY_REFERENCE');}
export function taxonomyReference(project,tableId,recordedColumn,targetColumn,identifierColumn,release){const table=project.tables.find(t=>t.id===tableId),resource=project.resources.find(r=>r.id===table?.resourceId);if(!table||!resource||table.rows.length>TAXONOMY_LIMITS.referenceRows||!/^([a-f0-9]{64})$/.test(resource.sha256)||!Number.isInteger(resource.bytes))fail('TAXONOMY_REFERENCE');const indices=[recordedColumn,targetColumn,...(identifierColumn===null?[]:[identifierColumn])];const reference={policy:'local-literal-taxonomy-v1',tableId,resourceId:resource.id,sha256:resource.sha256,bytes:resource.bytes,release,headers:[...table.headers],recordedColumn,targetColumn,identifierColumn,selectedDefinitions:indices.map(index=>structuredClone(table.columns[index])),entries:table.rows.map(row=>[row[recordedColumn],row[targetColumn],identifierColumn===null?'':row[identifierColumn]])};shape(reference);return reference;}
export function guardTaxonomyReference(project,reference){shape(reference);const table=project.tables.find(t=>t.id===reference.tableId),resource=project.resources.find(r=>r.id===reference.resourceId);if(!table||!resource||table.resourceId!==reference.resourceId||resource.sha256!==reference.sha256||resource.bytes!==reference.bytes||JSON.stringify(table.headers)!==JSON.stringify(reference.headers))fail('TAXONOMY_CHANGED');const fresh=taxonomyReference(project,reference.tableId,reference.recordedColumn,reference.targetColumn,reference.identifierColumn,reference.release);if(JSON.stringify(fresh.selectedDefinitions)!==JSON.stringify(reference.selectedDefinitions)||JSON.stringify(fresh.entries)!==JSON.stringify(reference.entries))fail('TAXONOMY_CHANGED');return true;}
export function taxonomyTranslate(table,spec){
 if(spec.upstreamOutcomePolicy!==undefined&&!['propagate','legacy-literal'].includes(spec.upstreamOutcomePolicy))fail('OPERATION');
 shape(spec.taxonomy);const column=spec.column,name=spec.name?.trim(),idName=name+'__taxon_id',stateName=name+'__review';if(!Number.isInteger(column)||table.headers[column]!==spec.expectedInputName)fail('FIELD_CHANGED');if(!name||table.headers.length>247||[name,idName,stateName].some(n=>table.headers.includes(n)))fail('DERIVED_NAME');if(!spec.review?.reviewer?.trim())fail('TAXONOMY_REVIEWER');if(table.rows.length>TAXONOMY_LIMITS.observationRows)fail('TAXONOMY_LIMIT');
 const dictionary=new Map();for(const [index,entry]of spec.taxonomy.entries.entries()){if(entry[0]==='')continue;let candidates=dictionary.get(entry[0]);if(!candidates){candidates=new Map();dictionary.set(entry[0],candidates);}const key=JSON.stringify(entry.slice(1)),candidate=candidates.get(key)||{name:entry[1],identifier:entry[2],referenceRecords:[]};candidate.referenceRecords.push(index+1);candidates.set(key,candidate);}
 const next=structuredClone(table),counts={converted:0,unchanged:0,unresolved:0,conflicting:0,empty:0},outcomes=[],examples=[];const upstreamName=table.columns[column].derivation?.outcomeField,upstreamColumn=upstreamName?table.headers.indexOf(upstreamName):-1;
 for(const [index,row]of next.rows.entries()){const before=row[column];let after=before,identifier='',state='unchanged';const candidates=[...(dictionary.get(before)?.values()||[])],upstream=upstreamColumn>=0?row[upstreamColumn]:null;
  if(spec.upstreamOutcomePolicy!=='legacy-literal'&&upstreamName&&(upstreamColumn<0||!Object.hasOwn(counts,upstream)))fail('FIELD_CHANGED');
  if(before==='')state='empty';else if(spec.upstreamOutcomePolicy!=='legacy-literal'&&['unresolved','conflicting'].includes(upstream))state=upstream;else if(!candidates.length)state='unresolved';else if(candidates.length>1)state='conflicting';else if(candidates[0].name===''||spec.taxonomy.identifierColumn!==null&&candidates[0].identifier==='')state='unresolved';else{after=candidates[0].name;identifier=candidates[0].identifier;state=after!==before||identifier!==''?'converted':'unchanged';}
  counts[state]++;outcomes.push(state);row.push(after,identifier,state);if(examples.length<10&&(state!=='unchanged'||index<3))examples.push({row:(table.rowOrigins?.[index]??index)+1,before,after:{name:after,identifier},state,taxonomyCandidates:candidates.slice(0,5).map(c=>({...c,referenceRecords:c.referenceRecords.slice(0,10),omittedReferenceRecords:Math.max(0,c.referenceRecords.length-10)})),omittedTaxonomyCandidates:Math.max(0,candidates.length-5)});
 }
 const common={status:counts.unresolved||counts.conflicting?'Inferred':'Confirmed',rationale:spec.review.reason,evidence:spec.review.evidence.map(r=>r.id),reviewerNotes:spec.review.reviewer,reviewBasis:spec.review.basis,confirmation:structuredClone(spec.review),sensitive:!!table.columns[column].sensitive||/latitude|longitude|coordinate|easting|northing|geometry|footprint|geohash|(?:^|[^a-z])(?:lat|lon|lng)(?:$|[^a-z])/i.test(table.headers[column])||['decimalLatitude','decimalLongitude','verbatimLatitude','verbatimLongitude'].includes(table.columns[column].term),derivation:{operation:'taxonomy',taxonomyPolicy:spec.taxonomy.policy,referenceTable:spec.taxonomy.tableId,referenceSource:spec.taxonomy.resourceId,referenceSha256:spec.taxonomy.sha256,referenceBytes:spec.taxonomy.bytes,referenceRelease:spec.taxonomy.release,referenceColumns:{recorded:spec.taxonomy.recordedColumn,target:spec.taxonomy.targetColumn,identifier:spec.taxonomy.identifierColumn},outcomeField:stateName,sourceFields:[table.headers[column]],coverage:counts,upstreamOutcomePolicy:spec.upstreamOutcomePolicy||'propagate',unresolvedPolicy:'retain recorded name and leave derived identifier empty',scope:'Explicit reviewed local reference matching; no fuzzy matching, scientific currency claim or record identity inference.'}};
 const definition=field(name),idDefinition=field(idName),status=field(stateName);Object.assign(definition,structuredClone(common),{description:spec.description||'Reviewed name from an explicitly selected local taxonomy reference; historical name retained.'});Object.assign(idDefinition,structuredClone(common),{description:'Literal identifier from the reviewed local reference, empty for unresolved/ambiguous records; not a validated resolver URL.'});Object.assign(status,{status:'Confirmed',description:'Per-row outcome of reviewed local taxonomy matching.',allowedValues:Object.keys(counts),rationale:spec.review.reason});next.headers.push(name,idName,stateName);next.columns.push(definition,idDefinition,status);return {table:next,affected:counts.converted,examples,counts,outcomes};
}
