import {toolLabel} from './workspace-profile.mjs';
import {uiLabel} from './i18n.mjs';
import {htmlMessage as uiText,t as uiValue} from './i18n.mjs';
import {esc,motionTiming} from './components.mjs';
import {lessonFor,meetsRequirements} from './tutorial-registry.mjs';
export const TOUR_VERSION=3;
export const productSteps=[
 {id:'projects',target:'projects',get title(){return uiValue("ui.e82a6eb21afd");},get text(){return uiValue("ui.e32bb59f55c3");},action:'click',route:'Projects'},
 {id:'mode',target:'workspace-mode',route:'Settings',category:'Workspace',get title(){return uiValue("ui.93e1e1234a43");},get text(){return uiValue("ui.202c3e907b32");},action:'change'},
 {id:'settings',target:'settings',get title(){return uiValue("ui.3f940108cb1e");},get text(){return uiValue("ui.fc17ed707a8b");},action:'click'},
 {id:'categories',target:'settings-categories',get title(){return uiValue("ui.f27afa06cc0c");},get text(){return uiValue("ui.ee3bcd0c35ad");},route:'Settings',action:'click'},
 {id:'status',target:'local-status',get title(){return uiValue("ui.706005c0492d");},get text(){return uiValue("ui.e4b4f29230d8");}},
 {id:'profile',target:'workspace-profile',get title(){return uiValue('v062.tour.profile.title');},get text(){return uiValue('v062.tour.profile.text');},action:'click',route:'Settings',category:'Workspace'},
 {id:'profile-edit',target:'profile-form',get title(){return uiValue('v062.tour.profile-edit.title');},get text(){return uiValue('v062.tour.profile-edit.text');},action:'submit'},
 {id:'overview',target:'overview-panel',get title(){return uiValue('v062.tour.overview.title');},get text(){return uiValue('v062.tour.overview.text');},route:'Project'},
 {id:'review',target:'review-queue-panel',get title(){return uiValue('v062.tour.review.title');},get text(){return uiValue('v062.tour.review.text');},route:'Review queue'},
 {id:'translation',target:'translation-workflow',get title(){return uiValue('v062.tour.translation.title');},get text(){return uiValue('v062.tour.translation.text');},route:'Translate & standardize'},
 {id:'evidence',target:'section-evidence',get title(){return uiValue('v062.tour.evidence.title');},get text(){return uiValue('v062.tour.evidence.text');},route:'Evidence'},
 {id:'validation',target:'section-validate',get title(){return uiValue('v062.tour.validation.title');},get text(){return uiValue('v062.tour.validation.text');},route:'Validate'},
 {id:'export',target:'section-export',get title(){return uiValue('v062.tour.export.title');},get text(){return uiValue('v062.tour.export.text');},route:'Export'},
 {id:'help',target:'help-search',get title(){return uiValue('v062.tour.help.title');},get text(){return uiValue('v062.tour.help.text');},route:'Help'},
 {id:'import',target:'import',get title(){return uiValue("ui.27c67c8371f6");},get text(){return uiValue("ui.3e4ba6549477");},action:'click'},
 {id:'import-zone',target:'import-zone',get title(){return uiValue("ui.6a85d53279b1");},get text(){return uiValue("ui.8dd9a213b0e7");},action:'optional'}
];
export function tourPlacement(target,size,viewport){
 const edge=12,gap=16,width=Math.min(size.width,viewport.width-edge*2),height=Math.min(size.height,viewport.height-edge*2);
 const below=viewport.height-target.bottom-edge,above=target.top-edge;
 let top=target.bottom+gap,side='below';
 if(below<height+gap&&above>=height+gap){top=target.top-height-gap;side='above';}
 else if(below<height+gap){top=Math.max(edge,(viewport.height-height)/2);side='beside';}
 let left=target.left+(target.width-width)/2;
 if(side==='beside')left=target.right+gap+width<=viewport.width-edge?target.right+gap:target.left-gap-width;
 return {left:Math.max(edge,Math.min(left,viewport.width-width-edge)),top:Math.max(edge,Math.min(top,viewport.height-height-edge)),width,height,side};
}
export function tourProgress(saved,length=productSteps.length){return saved?.version===TOUR_VERSION?{version:TOUR_VERSION,index:Math.max(0,Math.min(length-1,Number(saved.index)||0)),state:['paused','complete','skipped'].includes(saved.state)?saved.state:'paused',observed:Array.isArray(saved.observed)?saved.observed.filter(x=>typeof x==='string').slice(0,100):[],failed:Array.isArray(saved.failed)?saved.failed.filter(x=>typeof x==='string').slice(0,100):[]}:{version:TOUR_VERSION,index:0,state:'paused',observed:[],failed:[]};}
export function createProductTour({navigate,notice,getProject}){
 let key='biorescue-product-tour-v'+TOUR_VERSION,activeSteps=productSteps;let state,root,card,target,observer,resize,oldFocus,described,describedNode,frame,busy=false,navigationWasOpen=false;
 const read=()=>{try{return tourProgress(JSON.parse(localStorage.getItem(key)),activeSteps.length);}catch{return tourProgress(null,activeSteps.length);}};
 const findTarget=step=>{if(!meetsRequirements({...step,requirements:step.requirements||[]},getProject?.()))return null;const nodes=[...document.querySelectorAll(step.target.startsWith('#')||step.target.startsWith('.')||step.target.startsWith('[')?step.target:`[data-tour-id="${step.target}"]`)];return nodes.find(n=>n.getBoundingClientRect().width>0&&n.getBoundingClientRect().height>0)||nodes[0]||null;};
 function store(status='paused'){state.state=status;try{localStorage.setItem(key,JSON.stringify(state));}catch(error){notice(uiValue("ui.09f2f4c88d1b",{p0:(error.message)}),true);}}
 function unlink(){if(target){target.classList.remove('tour-target');if(described===null)describedNode?.removeAttribute('aria-describedby');else if(described!==undefined)describedNode?.setAttribute('aria-describedby',described);}target=null;described=undefined;}
 function cleanup(){if(!navigationWasOpen&&document.body.classList.contains('navigation-open'))document.querySelector('#navigation-toggle')?.click();window.removeEventListener('biorescue-language',relabel);unlink();observer?.disconnect();resize?.disconnect();cancelAnimationFrame(frame);window.removeEventListener('resize',schedule);document.removeEventListener('scroll',schedule,true);document.removeEventListener('keydown',keyboard,true);document.removeEventListener('click',interact,true);document.removeEventListener('change',interact,true);document.removeEventListener('submit',interact,true);root?.remove();root=null;card=null;}
 function exit(status='paused'){store(status);cleanup();if(oldFocus?.isConnected)oldFocus.focus();else document.querySelector('[data-tour-id=projects]')?.focus();}
 function schedule(){cancelAnimationFrame(frame);frame=requestAnimationFrame(position);}
 function position(){if(!root||!card?.querySelector('[data-tour-next]'))return;const step=activeSteps[state.index],found=findTarget(step);if(found!==target){if(target&&document.documentElement.dataset.motion!=='off')root.animate([{opacity:.35},{opacity:1}],{duration:document.documentElement.dataset.motion==='reduced'?120:260,easing:'cubic-bezier(.2,.8,.2,1)'});unlink();target=found;if(target){describedNode=target.matches('button,input,[role=combobox],[tabindex]')?target:target.querySelector('[role=combobox],button,input:not(.choice-native)')||target;described=describedNode.getAttribute('aria-describedby');describedNode.setAttribute('aria-describedby',[described,'product-tour-description'].filter(Boolean).join(' '));target.classList.add('tour-target');}}
  const visible=target&&target.getBoundingClientRect().width>0&&target.getBoundingClientRect().height>0;if(!visible&&!busy&&!state.failed.includes(step.id)){state.failed.push(step.id);store();}root.dataset.missing=String(!visible);root.querySelector('[data-tour-missing]').hidden=!!visible;root.querySelector('[data-tour-next]').disabled=busy||!visible||!!step.action&&step.action!=='optional';root.querySelector('#product-tour-description').textContent=visible?step.text:uiValue('ui.34422d530930');
  const parent=target?.closest('dialog[open]')||document.body;if(root.parentElement!==parent)parent.append(root);
  let rect=visible?target.getBoundingClientRect():{top:innerHeight/2,left:innerWidth/2,bottom:innerHeight/2,right:innerWidth/2,width:0,height:0};const opened=target?.querySelector('.choice-list:not([hidden])');if(opened){const menu=opened.getBoundingClientRect();rect={left:Math.min(rect.left,menu.left),top:Math.min(rect.top,menu.top),right:Math.max(rect.right,menu.right),bottom:Math.max(rect.bottom,menu.bottom)};rect.width=rect.right-rect.left;}const pad=6,l=Math.max(0,rect.left-pad),r=Math.min(innerWidth,rect.right+pad),t=Math.max(0,rect.top-pad),b=Math.min(innerHeight,rect.bottom+pad);
  const areas=[[0,0,innerWidth,t],[0,b,innerWidth,innerHeight-b],[0,t,l,b-t],[r,t,innerWidth-r,b-t]];
  root.querySelectorAll('.tour-shade').forEach((shade,i)=>{const[x,y,w,h]=areas[i];Object.assign(shade.style,{left:x+'px',top:y+'px',width:Math.max(0,w)+'px',height:Math.max(0,h)+'px'});});
  const p=tourPlacement(rect,{width:360,height:card.offsetHeight},{width:innerWidth,height:innerHeight});Object.assign(card.style,{left:p.left+'px',top:p.top+'px',width:p.width+'px',maxHeight:(innerHeight-24)+'px'});card.dataset.side=p.side;
 }
 async function waitForTarget(step){if(findTarget(step)?.getClientRects().length)return;await new Promise(resolve=>{const pending=new MutationObserver(()=>{if(findTarget(step)?.getClientRects().length){clearTimeout(timeout);pending.disconnect();resolve();}});pending.observe(document.body,{childList:true,subtree:true});const timeout=setTimeout(()=>{pending.disconnect();resolve();},4000);});}
 async function show(){if(!root)return;busy=true;root.dataset.loading='true';const previousRoot=root,transitioning=!!target&&document.documentElement.dataset.motion!=='off';if(transitioning){const fade=root.animate([{opacity:1},{opacity:0}],motionTiming('fast'));try{await fade.finished;}catch{}if(root!==previousRoot)return;root.style.opacity='0';}unlink();const step=activeSteps[state.index];if(step.route)await navigate(step.route);if(step.category)document.querySelector('[data-category="'+step.category+'"]')?.click();await waitForTarget(step);const visibleTarget=findTarget(step);if(!visibleTarget?.closest('.sidebar')&&!navigationWasOpen&&document.body.classList.contains('navigation-open'))document.querySelector('#navigation-toggle')?.click();if(visibleTarget?.closest('.sidebar')&&innerWidth<900&&!document.body.classList.contains('navigation-open'))document.querySelector('#navigation-toggle')?.click();if(root&&!findTarget(step)?.getClientRects().length&&!state.failed.includes(step.id)){state.failed.push(step.id);store();}if(!root){busy=false;return;}card.innerHTML=`<p class="eyebrow">${uiText("ui.0d907a988cb8",{p0:(state.index+1),p1:(activeSteps.length)})}</p><h2 id="product-tour-title">${esc(step.title)}</h2><p id="product-tour-description">${target?.getClientRects().length?esc(step.text):uiText("ui.34422d530930")}</p><p data-tour-missing hidden role="status">${uiText("ui.34422d530930")}</p><div class="tour-actions"><button type="button" data-tour-back ${state.index?'':'disabled'}>${uiText("ui.76900f1bfd16")}</button><button type="button" data-tour-next ${target?.getClientRects().length?'':'disabled'}>${esc(uiLabel(state.index===activeSteps.length-1?'Finish':'Next'))}</button><button type="button" data-tour-retry>${uiText('workspace.retryTarget')}</button><button type="button" data-tour-pause>${uiText("ui.b6f1c55055ae")}</button><button type="button" data-tour-restart>${uiText("ui.6b983a81e5e8")}</button><button type="button" data-tour-skip>${uiText("ui.5ac614dee51b")}</button><button type="button" data-tour-exit>${uiText("ui.d17d84a60499")}</button></div>`;
  card.querySelector('[data-tour-retry]').onclick=()=>show();card.querySelector('[data-tour-back]').onclick=()=>move(-1);card.querySelector('[data-tour-next]').onclick=()=>move(1);card.querySelector('[data-tour-pause]').onclick=()=>exit();card.querySelector('[data-tour-exit]').onclick=()=>exit();card.querySelector('[data-tour-skip]').onclick=()=>exit('skipped');card.querySelector('[data-tour-restart]').onclick=()=>{state.index=0;show();};position();target?.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});position();const focus=target?.matches('button,input,select,[tabindex]')?target:target?.querySelector('button,input:not(.choice-native),[role=combobox]');(focus||card.querySelector('[data-tour-next]')).focus();store();busy=false;root.dataset.loading='false';root.dataset.step=String(state.index);position();root.style.opacity='';if(transitioning)root.animate([{opacity:0},{opacity:1}],motionTiming('panel'));
 }
 function move(delta){if(busy)return;if(delta>0){const step=activeSteps[state.index];if(!findTarget(step)?.getClientRects().length)return;if(!state.observed.includes(step.id))state.observed.push(step.id);}if(delta>0&&state.index===activeSteps.length-1)return exit(state.failed.length?'skipped':'complete');state.index=Math.max(0,Math.min(activeSteps.length-1,state.index+delta));show();}
 function interact(event){if(busy||!target||!target.contains(event.target)||!root)return;const step=activeSteps[state.index];if(step.action===event.type){busy=true;setTimeout(()=>{busy=false;move(1);},0);}}
 function keyboard(event){if(!root)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();exit();return;}if(event.key!=='Tab')return;const selectors='button:not(:disabled),input:not(:disabled):not(.choice-native),[role=combobox]:not(:disabled),[tabindex="0"]';const allowed=[...(target?.matches(selectors)?[target]:target?.querySelectorAll(selectors)||[]),...card.querySelectorAll('button:not(:disabled)')].filter(node=>node.getClientRects().length);if(!allowed.length)return;event.preventDefault();const i=allowed.indexOf(document.activeElement);allowed[(i+(event.shiftKey?-1:1)+allowed.length)%allowed.length].focus();}
 function relabel(){if(root)show();}
 async function start({restart=false,module=null}={}){if(root)cleanup();activeSteps=lessonFor(module)?.steps.map(s=>({...s,title:uiValue('lesson.step.'+s.id+'.title'),text:uiValue('lesson.step.'+s.id+'.body')}))||(module==='interface'?productSteps.filter(step=>(getProject?.()?['projects','overview','review','settings','categories','status','profile']:['projects','settings','categories','status','profile']).includes(step.id)).map(step=>({...step,action:undefined})):module?[{id:'context',target:'project-context',route:module,title:toolLabel(module),text:uiValue('v06.help.'+module)},{id:'workspace',target:'workflow-content',route:module,title:uiValue('v07.showMe'),text:uiValue('v06.help.'+module)},{id:'meaning',target:'workflow-explanation',route:module,title:uiValue('v07.layers'),text:uiValue('v06.helpUnknown')}]:productSteps);key='biorescue-product-tour-v'+TOUR_VERSION+(module?'-'+module:'')+'-'+(getProject?.()?.id||'workspace');state=restart?tourProgress(null):read();state.index=Math.min(state.index,activeSteps.length-1);if(state.state==='complete'||state.state==='skipped')state=tourProgress(null);oldFocus=document.activeElement;navigationWasOpen=document.body.classList.contains('navigation-open');root=document.createElement('div');root.className='product-tour';root.innerHTML=`<div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><section class="tour-card" role="dialog" aria-modal="false" aria-labelledby="product-tour-title" aria-describedby="product-tour-description"></section>`;card=root.querySelector('.tour-card');document.body.append(root);observer=new MutationObserver(records=>{if(records.some(r=>!root.contains(r.target)))schedule();});observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('biorescue-language',relabel);window.addEventListener('resize',schedule);document.addEventListener('scroll',schedule,true);document.addEventListener('keydown',keyboard,true);document.addEventListener('click',interact,true);document.addEventListener('change',interact,true);document.addEventListener('submit',interact,true);await show();}
 return {start,exit,get active(){return !!root;}};
}

