import {t} from './i18n.mjs';import {esc} from './components.mjs';import {icon} from './studio-icons.mjs';
export const ROLES=['field','wildlife','curator','museum','archivist','student','technical','other'];
export const EXPERIENCES=['beginner','comfortable','advanced'];
export const TOOLS=['Project','Sources','Inspect','Metadata','Relationships','Evidence','Repair','Review queue','Translate & standardize','Map to Standards','Validate','Export','Audit / Report','Snapshots','Storage & Recovery','Large CSV','Standards validation','DwC-DP preparation','Standards Center','Saved for later','Settings','Help','About'];
const basic=['Project','Sources','Inspect','Metadata','Evidence','Repair','Review queue','Translate & standardize','Validate','Export','Settings','Help'];
const technical=['Map to Standards','Standards validation','DwC-DP preparation','Large CSV'];
export function sanitizeProfile(value){return {version:2,role:ROLES.includes(value?.role)?value.role:'other',experience:EXPERIENCES.includes(value?.experience)?value.experience:'beginner',configured:!!value?.configured,technicalLabels:!!value?.technicalLabels,explanations:value?.explanations!==false,recommendations:value?.recommendations!==false,visibility:Object.fromEntries(TOOLS.map(name=>[name,['shown','relevant','hidden'].includes(value?.visibility?.[name])?value.visibility[name]:'relevant']))};}
export function getProfile(){try{const stored=JSON.parse(localStorage.getItem('biorescue-workspace-profile')),next=sanitizeProfile(stored);if(stored&&(stored.role==='unsure'||stored.experience==='unsure'))localStorage.setItem('biorescue-workspace-profile',JSON.stringify(next));return next;}catch{return sanitizeProfile(null);}}
export function setProfile(value){const next=sanitizeProfile(value);localStorage.setItem('biorescue-workspace-profile',JSON.stringify(next));window.dispatchEvent(new CustomEvent('biorescue-profile',{detail:next}));return next;}
export function recommendedTools(profile,project){const advanced=profile.experience==='advanced';const set=new Set(advanced?TOOLS:basic);if(['curator','museum','technical'].includes(profile.role))for(const tool of ['Relationships','Map to Standards','Standards Center'])set.add(tool);if(profile.role==='archivist')for(const tool of ['Sources','Evidence','Audit / Report','Snapshots','Storage & Recovery','Standards Center'])set.add(tool);if(profile.role==='technical')technical.forEach(t=>set.add(t));if(project?.tables?.length>1)set.add('Relationships');return TOOLS.filter(tool=>profile.visibility[tool]==='shown'||profile.visibility[tool]==='relevant'&&set.has(tool));}
export function toolLabel(name,profile=getProfile()){const plain=t('v06.nav.'+name+'.plain'),technical=t('v06.nav.'+name+'.technical');return profile.experience==='advanced'?technical:profile.technicalLabels&&plain!==technical?plain+' · '+technical:plain;}
export function profileLabel(profile=getProfile()){return t('v06.role.'+profile.role)+' · '+t('v06.experience.'+profile.experience);}
export function profileChoicesHtml(profile=getProfile()){
 const glyphs={field:'home',wildlife:'review',curator:'grid',museum:'library',archivist:'files',student:'help',technical:'settings',other:'window'};
 const cards=(keys,name,prefix)=>keys.map(key=>`<label class="profile-choice"><input type="radio" name="v3-${name}" value="${key}" ${profile[name]===key?'checked':''}><span>${name==='role'?icon(glyphs[key]):''}<strong>${esc(t('v06.'+name+'.'+key))}</strong><small>${esc(t('studio.'+(name==='role'?'role':'level')+'.'+key))}</small></span></label>`).join('');
 return `<div class="profile-choices" data-tour-id="workspace-mode"><div class="profile-choice-heading"><h3>${esc(t('v06.role.question'))}</h3><button type="button" class="text-button" data-help-choose>${esc(t('studio.choose'))}</button></div><section class="profile-guide" data-profile-guide hidden><p>${esc(t('studio.choosePrompt'))}</p><div class="small-actions">${['field','collections','technical'].map(key=>`<button class="button secondary" type="button" data-role-guide="${key}">${esc(t('studio.choose.'+key))}</button>`).join('')}</div><p>${esc(t('studio.choose.level'))}</p></section><div class="role-cards" role="group" aria-label="${esc(t('v06.role.question'))}">${cards(ROLES,'role')}</div><h3>${esc(t('v06.experience.question'))}</h3><div class="experience-cards" role="group" aria-label="${esc(t('v06.experience.question'))}">${cards(EXPERIENCES,'experience')}</div><section class="profile-live-preview" aria-live="polite"><span class="eyebrow">${esc(t('studio.yourWorkbench'))}</span><h3 data-profile-selection></h3><p data-profile-example></p><nav class="profile-nav-preview" data-profile-nav aria-label="${esc(t('rescue.navPreview'))}"></nav><small>${esc(t('v06.presentationOnly'))}</small></section></div>`;
}
export function bindProfileChoices(host){
 const read=()=>({role:host.querySelector('[name=v3-role]:checked')?.value||'other',experience:host.querySelector('[name=v3-experience]:checked')?.value||'beginner'});
 const draw=()=>{const selected=read();host.querySelector('[data-profile-selection]').textContent=profileLabel(selected);host.querySelector('[data-profile-example]').textContent=t('studio.preview.'+selected.experience);host.querySelector('[data-profile-nav]').innerHTML=recommendedTools(sanitizeProfile(selected),null).filter(name=>!['Help','Settings','About'].includes(name)).slice(0,8).map(name=>`<span>${esc(toolLabel(name,sanitizeProfile(selected)))}</span>`).join('');};
 host.querySelectorAll('[name^=v3-]').forEach(input=>input.addEventListener('change',draw));
 host.querySelector('[data-help-choose]').onclick=()=>{const guide=host.querySelector('[data-profile-guide]');guide.hidden=!guide.hidden;host.querySelector('[data-help-choose]').setAttribute('aria-expanded',String(!guide.hidden));};
 host.querySelectorAll('[data-role-guide]').forEach(button=>button.onclick=()=>{const role={field:'field',collections:'museum',technical:'technical'}[button.dataset.roleGuide],input=host.querySelector('[name=v3-role][value='+role+']');input.checked=true;draw();let step=host.querySelector('[data-guide-level]');if(!step){step=document.createElement('section');step.dataset.guideLevel='';host.querySelector('[data-profile-guide]').append(step);}step.innerHTML=`<h3>${esc(t('rescue.guideLevel'))}</h3><div class="small-actions">${EXPERIENCES.map(level=>`<button type="button" class="button secondary" data-guide-experience="${level}">${esc(t('v06.experience.'+level))}</button>`).join('')}</div><p data-guide-result></p>`;step.querySelectorAll('[data-guide-experience]').forEach(choice=>choice.onclick=()=>{host.querySelector('[name=v3-experience][value='+choice.dataset.guideExperience+']').checked=true;draw();step.querySelector('[data-guide-result]').textContent=t('rescue.guideResult')+' · '+profileLabel(read());});step.querySelector('button').focus();});draw();return read;
}
export function editProfile(first=false){
 const old=getProfile(),focus=document.activeElement,dialog=document.createElement('dialog');dialog.className='workbench-dialog profile-dialog';dialog.setAttribute('aria-labelledby','profile-title');
 dialog.innerHTML=`<form data-tour-id="profile-form"><h2 id="profile-title">${esc(t(first?'v06.welcome':'v06.workspace'))}</h2>${profileChoicesHtml(old)}<details><summary>${esc(t('v06.customizeTools'))}</summary>${TOOLS.map((name,i)=>`<label>${esc(toolLabel(name,old))}<select name="tool-${i}">${['shown','relevant','hidden'].map(v=>`<option value="${v}" ${old.visibility[name]===v?'selected':''}>${esc(t('v06.visibility.'+v))}</option>`).join('')}</select></label>`).join('')}<label class="checkbox-label"><input name="technicalLabels" type="checkbox" ${old.technicalLabels?'checked':''}>${esc(t('v06.technicalLabels'))}</label>${['explanations','recommendations'].map(key=>`<label class="checkbox-label"><input name="${key}" type="checkbox" ${old[key]?'checked':''}>${esc(t('v06.'+key))}</label>`).join('')}</details><div class="small-actions"><button class="button primary" type="submit">${esc(t('studio.applyProfile'))}</button><button type="button" class="button secondary" data-all>${esc(t('v06.showAll'))}</button><button type="button" class="button secondary" data-reset>${esc(t('v06.restoreProfile'))}</button><button class="button secondary" type="button" data-cancel>${esc(t('cancel'))}</button></div></form>`;
 document.body.append(dialog);const read=bindProfileChoices(dialog),close=()=>{dialog.close();dialog.remove();focus?.isConnected&&focus.focus();};
 dialog.querySelector('[data-all]').onclick=()=>dialog.querySelectorAll('[name^=tool-]').forEach(x=>{x.value='shown';});dialog.querySelector('[data-reset]').onclick=()=>dialog.querySelectorAll('[name^=tool-]').forEach(x=>{x.value='relevant';});
 dialog.querySelector('[data-cancel]').onclick=()=>{if(first)setProfile({...old,configured:true});close();};
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);setProfile({...old,...read(),configured:true,technicalLabels:f.has('technicalLabels'),explanations:f.has('explanations'),recommendations:f.has('recommendations'),visibility:Object.fromEntries(TOOLS.map((name,i)=>[name,f.get('tool-'+i)]))});close();};
 dialog.oncancel=()=>{if(first)setProfile({...old,configured:true});dialog.remove();focus?.isConnected&&focus.focus();};dialog.showModal();return dialog;
}
